### ISSUE TITLE
FireBase ネストが深くなると死ぬ

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#108]
@Ayato-kosaka

**Comment by Ayato-kosaka** [comment]
Readの引数でパスをもらう？
例）
Plan.read(Id, collectionPath){
 collection(db, collectionPath)
}

**Comment by Ayato-kosaka** [comment]
updateとかもいちいち指定するのは面倒
→フロントで保持とDBで保持は分けるべきか？

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ERDがちゃんと固まってないから検討は難しいからとりあえず今のままtypescript化でOK
本課題はver1.2に持ち越す！
