### ISSUE TITLE
FireStoreからデータ取得の際に型がUnknownになってしまう件

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#110]

**Comment by Takapy1** [comment]
https://github.com/Ayato-kosaka/react-itinerary/pull/60#pullrequestreview-1064313494
> docSnap.data()にDB0002ItineraryTypeに含まれないプロパティが含まれた時に除外してくれる？
> 調べた感じ恐らく除外してくれるけど、念の為確認してほしい！

上記のレビューでFireStoreからデータ取得した際に、型がUnknownになってしまい、
無駄なフィールドが含まれていると、除外できない。

**方法①　as で型アサーションを使用する**
これは取得したデータを強制的に型変更しているだけなので、エラーは消えるけど、
無駄なフィールドは残るため、根本的な解決になっていない

方法② [FireStoreDataConverter](https://firebase.google.com/docs/reference/node/firebase.firestore.FirestoreDataConverter)を使用する
getDoc().withConverter(ItinerariesType)みたいにすることで、
データ取得の際にItinerariesTypeで返してくれるから、必要なフィールドのみ抽出かつ型安全
→どこのファイルにConverterを記述するか

[わかりやすい記事１](https://qiita.com/FAL-coffee/items/3496036b7acbb3493bc1)
[わかりやすい記事２](https://www.gixo.jp/blog/15372/#_Firestore)

**Comment by Ayato-kosaka** [comment]
@Takapy1 
すげー、超良さそう！これが使えたらいろんな課題が消えそう！

ただ、これにすると、オブジェクトじゃなくて、クラスになっちゃうよね、、
そうするとリアクトとの相性が悪いイメージなんだけど問題ないのかな。

**Comment by Takapy1** [comment]
@Ayato-kosaka 
> @Takapy1 すげー、超良さそう！これが使えたらいろんな課題が消えそう！
> 
> ただ、これにすると、オブジェクトじゃなくて、クラスになっちゃうよね、、 そうするとリアクトとの相性が悪いイメージなんだけど問題ないのかな。

関数コンポーネントで実装されているものもありそう！
[FireStoreDataConverTer 関数コンポーネントの例](https://qiita.com/github0013@github/items/0d80c4987da7bbdb3c8f)

**Comment by Ayato-kosaka** [comment]
@Takapy1 
おおお、これだったら、うまくいきそうだね！
これ使えるんだったらapiフォルダいらない説出てきた、、contextで、snapshot管理してーみたいな！
ちょっと今週の土日で話し合うか！

**Comment by Takapy1** [comment]
> @Takapy1 おおお、これだったら、うまくいきそうだね！ これ使えるんだったらapiフォルダいらない説出てきた、、contextで、snapshot管理してーみたいな！ ちょっと今週の土日で話し合うか！

おk

**Comment by Ayato-kosaka** [comment]
**FirestoreDataConverterを用いた場合のAPI,Contextファイルを検討する**

**Comment by Ayato-kosaka** [comment]
#Convereterを使ってnullチェック、データ不足チェックは可能
```
const postSnap = await firebase.firestore()
  .collection('posts')
  .withConverter(postConverter)
  .doc().get();
const post = postSnap.data();
if (post !== undefined) {
  post.title; // string
  post.toString(); // Should be defined
  post.someNonExistentProperty; // TS error
}
```

**Comment by Ayato-kosaka** [comment]
@Takapy1 
https://github.com/Ayato-kosaka/react-itinerary/issues/110#issuecomment-1211544301
みたいにすれば、contextでsnapshot管理して、apiファイル消せそう！
itineraryのcontextを追加で作成が必要だけど
よくわからんかったら明後日話すわ！
