### ISSUE TITLE
リント & フォーマット

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#126]
ESLint と Prettierを使ってどこまでやる？
を話し合うスレッド

**Comment by Ayato-kosaka** [comment]
@Takapy1 
Eslintって保存時に走るで合ってる？
また、強制フォーマットのタイミングは、保存時かコミット時かどっちがいいと思う？

**Comment by Takapy1** [comment]
@Ayato-kosaka 
調べてみた感じ、ファイル保存時に警告出してくれた方がすぐに修正できていいと思う。

デメリットに開発者がリントの警告気にしない
とかあるけど、今少人数だから2人で徹底すれば保存時に確認できるのがベストだと思う。

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ESlintを保存時にして、警告出すのは認識あってるだけど、
ESlintの内容に合わせて強制的に修正する機能があって（例えばダブルクォーテーションをシングルクォーテーションに直す）
それを保存時にやるか、git commit 時にやるか迷ってる（もしくはやらないか）

**Comment by Ayato-kosaka** [comment]
ESlintがうるさすぎたら消す。
保存時のフォーマットは各々
commit 時にするかは必要に応じる
