### ISSUE TITLE
Expo でのルート管理どうする？

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#146]
# React Navigation
[React Navigationの基本](https://fintan-contents.github.io/mobile-app-crib-notes/react-native/learn/basic-concepts/react-navigation-basics/)

# 構成
Tab(Service)
-- Stack(Page)
-- -- Drawer (Modal等)

## Tab
App.tsx に定義する
[createMaterialBottomTabNavigator](https://reactnavigation.org/docs/material-bottom-tab-navigator)
![image](https://user-images.githubusercontent.com/53715839/198994341-8b1d348f-942b-4446-a5cd-10e8f629a300.png)

## Stack
Servise/Page ディレクトリ配下に`${ServiceName}PageNavigator.tsx`を作成し、Pageへのルーティングを定義する

## Drawer
未検討

# 利用ガイド

## Page コンポーネントのスケルトン
```
export function()({ route, navigation }: NativeStackScreenProps<BottomTabParamList, '${PageName}'>) {
  // Parameter の受け取り
}
```
## Parameter の受け取り
```
const { messgae } = route.params
```
※undifined を考慮し、Stack.Screen で `initialParams`を付与する、もしくは Page コンポーネント内で制御する

## 画面遷移
```
navigation.navigate('${ServiceName}', {
	screen: '${PageName}',
	params: { message: 'Hello'},
}
```

## 残課題
- [ ] #287

**Comment by Ayato-kosaka** [comment]
react-navigationでできそう
https://qiita.com/hitotch/items/0ceca6eb440c06512c51
https://zenn.dev/kakimoty/scraps/cbbe4a0e6bd9f1

@Takapy1 
読んでみたけどよくわからないから、App.tsxをどう書けばルーティングできて、どうすれば画面遷移出来るか整理してほしい。

**Comment by Ayato-kosaka** [comment]
@Takapy1 
react-navigation について調べ直して、まとめた
https://github.com/Ayato-kosaka/spelieve/issues/146#issue-1350898125

↓のマージリクエストででもページと App.tsx 修正しているから確認して問題なければマージしてほしい！（タスクチケット起票済）
https://github.com/Ayato-kosaka/spelieve/pull/288

**Comment by Takapy1** [comment]
@Ayato-kosaka 
ありがとう！無限スクロール終わり次第、
countryとかもsetAddressではなく、自分のページ遷移に変更できるか試してみるわ！
