### ISSUE TITLE
Firestore の型に array あるけど typescript との相性どう？

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#148]
PlanGroup の plans とか array の方が良さそう。
でも、array <=> Array<string> の変換とか typescript 大丈夫？

**Comment by Ayato-kosaka** [comment]
Array<number>とかOK?

**Comment by Takapy1** [comment]
コードサンドボックスとかで明日動かしてみるしかないかな

**Comment by Ayato-kosaka** [comment]
これは俺がやっとく！

**Comment by Ayato-kosaka** [comment]
Arrayもちゃんと使える。
Arrayの中の型も検知してくれてるから、`Array<string>`, `Array<number>`も区別できそう

![Image](https://user-images.githubusercontent.com/53715839/197374834-51f0b160-080d-426a-94c9-76f922fd2c0a.png)

**Comment by Ayato-kosaka** [comment]
Object も同様に、中身まで型を検知してるから{[id:string]: any}でいけそう
なんなら、Array<Object>も{[id:string]: Object}も出来そう！

@Takapy1 
他に気になるところ無ければCloseするけどどうかな

**Comment by Takapy1** [comment]
@Ayato-kosaka 
なるほど、そこはちゃんと検知してくれるんか
ならもうクローズして良いと思う
