### ISSUE TITLE
Tags の集計

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#207]
## 集計方法
Tags はItineraries や Plans から集計する。
実現方法としては、Itineraty サービスのCloud Functions を用いて、データ集計し、Tags に挿入する形に整形しレスポンスするAPIを作成する。
※出来ればセキュアでありたい

## 環境
#223 に定める

## 子issue

- [x] #223

**Comment by Ayato-kosaka** [comment]
サブネットが同じならGoから直接firestoreアクセスできないかな

**Comment by Ayato-kosaka** [comment]
[GolangとClean ArchitectureでAPIサーバーを構築してみた](https://zenn.dev/yantera/articles/524591655e3244)

**Comment by Takapy1** [comment]
Tagのautocompleteを作るイメージ
- firebase-admin→Elastic searchにItineraries, Plansのデータ投入（バッチフィーズ:BL）
  - Itineraries, Plansのデータ集計→同じタグの数でrankingにした状態
- UserがTagsの検索のときにElastic Searchから高速でReadする

**Comment by Takapy1** [comment]
同じタグ数でランキング化はまだできていない状態
