### ISSUE TITLE
Firebase 全文検索

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#223]
## 方針
検索プロバイダを利用する

## 利用する検索プロバイダ：Elasticsearch 
＋　安い、日本語対応
ー　難易度高い

## Tag の実装方針
Scheduler + Cloud Funtions で、Elastic Search に日時で洗い替え。
検索はCloud Function でAPI通して、全文検索

## 作成ファイル役割
[Funclist](https://docs.google.com/spreadsheets/d/107f2L_2REDahiB-T8hWvKK8tHgqPog-_GM_DrS0aWYs/edit#gid=542225782)
- Itinerary
  -  MItineraryHashtag: ビューで使用、ElasticSearch→フロント
  - SetMItineraryTagData: 定期実行、FireStore→ElasticSearch
- Place
  - MPlanTag
  - SetMPlanTagData

[PG_DATA, COLUMN](https://docs.google.com/spreadsheets/d/1dQI70w__2fQ2u84uHHP5ASZNQJmMAb3G8MYZ_wDcsQ8/edit#gid=1739150437)
- ２つのテーブル(index)を作成(Itinerary, Plan用）
- 

## Firestore→ESにデータ投入流れ(バッチ処理）
- tagsデータ取得
- Analyzerで形態素解析（日本語の場合）
- ranking化(各単語が何個出てきているかどうか, attachedCountカラム）
- ESに登録されているTagデータ削除
- 新しいものを登録

## ES→Firestoreのデータ取得
- フロントからクエリ投げる
- ESからレスポンス（attachedCountでソート、limit指定）
- データ加工

### ルール
backend-tagからしかESが動かないようにする

### テスト
curlコマンドで適切なレスポンスが返るか確認

**Comment by Ayato-kosaka** [comment]
Firebase extension に　Search with Elastic App Search がある

**Comment by Ayato-kosaka** [comment]
@Takapy1 
タグを検索する時にオートコンプリートのために全文検索するだけど、
なんかよくよく調べてたら、全文検索って、結構むずいっぽくて、
そもそもRDBが向いてないっぽい。
アプリに導入するなら、Elastic Searchとか、Algolila みたいな検索プロバイダが最終的には良いらしい（お金はかかる）
Spelieve-backend-tag で、node jsバックエンド作ろうと思ってたけどやめて、検索プロバイダ任せにしようと思うけどどうかな？

**Comment by Ayato-kosaka** [comment]
いや、nodejs はやっぱり作って、
Cloud function をやめて、nodejsのDBをMySQL想定からElastic Searchに変更でもいいな。

どちらにせよ、Cloud Function の中身はnodejsやから、以降簡単やからとりあえずどっちでもできるようにするでいいかも

**Comment by Ayato-kosaka** [comment]
@Takapy1 
https://nipo-plus-doc.sndbox.jp/tech/elasticsearch/
こんな感じでfirestoreと絡めながら調べてほしい！

**Comment by Takapy1** [comment]
## 想定
例) itinerary tagsの場合
### firestoreのデータ
[["夜景綺麗", "デートに最適"], ["食事が美味", "いい夜景"], ["食べ歩き"],,,]
↓
## Elastic Searchにそのままtagsを保存
データ型
tags: text[]
↓
### 形態素解析
kuromojiを使用して、単語に分けてくれる
### インデックス作成
単語ごとにどのtagに含まれているのかを保持し、クエリがきたら、
多い順に単語を返す


## ユーザ検索時ユースケース
「夜景」などのキーワード入力→？？？
