### ISSUE TITLE
Place設計見直し

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#238]
Collection からの Query
地名に該当するPlaceを取得（["日本"、"奈良"]等）
評価（rating）でソートする

検索時の絞り込み
今までと変わらず、場所なら遷移、市町村なら検索

検索キーのDB保持情報
postal_code
country
administrative_area_level_1
administrative_area_level_2
locality
route
street_number
※要吟味

[
          { "long_name": "48", "short_name": "48", "types": ["street_number"] },
          {
            "long_name": "Pirrama Road",
            "short_name": "Pirrama Rd",
            "types": ["route"],
          },
          {
            "long_name": "Pyrmont",
            "short_name": "Pyrmont",
            "types": ["locality", "political"],
          },
          {
            "long_name": "City of Sydney",
            "short_name": "City of Sydney",
            "types": ["administrative_area_level_2", "political"],
          },
          {
            "long_name": "New South Wales",
            "short_name": "NSW",
            "types": ["administrative_area_level_1", "political"],
          },
          {
            "long_name": "Australia",
            "short_name": "AU",
            "types": ["country", "political"],
          },
          {
            "long_name": "2009",
            "short_name": "2009",
            "types": ["postal_code"],
          },
        ]
絞り込み方法
上記のフィールドを administrative_area_level_2 くらいまで絞り込む

**Comment by Ayato-kosaka** [comment]
こんな感じらしい @Takapy1 

![Image](https://user-images.githubusercontent.com/53715839/195955821-3e1a31fb-0cbd-4147-a611-aeaa98f27eb3.png)


Createする時に↓らへんをDBに保持して、
- country
- administrative_area_level_1
- administrative_area_level_2
- locality
- sublocality_level_1
- sublocality_level_2
- sublocality_level_3
- sublocality_level_4
- premise

検索するときは↓らへんをstateで持ってand where でつなげる感じになると思う。イメージつく？
- country
- administrative_area_level_1
- administrative_area_level_2
- locality

**Comment by Ayato-kosaka** [comment]
@Takapy1 
geopoint+lengthじゃなくなったから、スライダーは廃止でいいかも

**Comment by Takapy1** [comment]
@Ayato-kosaka 
たしかに使用用途ないから要らないね！
