### ISSUE TITLE
外国語化対応

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#249]
## 子issue
- [x] - #429 
- [x] - #430 
- [x] - #431

**Comment by Ayato-kosaka** [comment]
i18n-js key extract
みたいにググると json の自動生成できるはず

**Comment by Takapy1** [comment]
https://www.npmjs.com/package/i18n-extract

**Comment by Takapy1** [comment]
@Ayato-kosaka 
仮にi18n.tのキーを上記のi18n-extractで抽出した場合、
- コード解析するファイルはどこに配置するのか
　- 開発環境用フォルダ作成し、.gitignoreに追加する
- 抽出してLangIf.tsに書き出す→ja.ts, es.tsで過不足があればエラーになる

上記の２つが分からない点です

**Comment by Ayato-kosaka** [comment]
@Takapy1 
> コード解析するファイルはどこに配置するのか

プロジェクト配下とかでいいんじゃない？
.gitignore する必要あるの？
git で管理したいと思ったけど

> 抽出してLangIf.tsに書き出す→ja.ts, es.tsで過不足があればエラーになる

LangIf に書き出せば、ja.ts, es.tsがtypescript でエラーになるってことだよね。
それでいいんじゃない？
そうすることで、差分がわかるから、そこを修正するで良いと思う！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
プロジェクト直下でええか
