### ISSUE TITLE
iOS, Android へのデプロイ

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#250]
# 手順
- [x] eas.json作成
- [x] Credentials作成権限をもらう
- [x] Credentials作成
- [x] EASにCredentials登録
- [x] build
  - [x] [Internal distribution](https://docs.expo.dev/build/internal-distribution/)試す
- [ ] [App Storeへ提出](https://docs.expo.dev/submit/ios/)
- [ ] [Google play Store へ提出](https://docs.expo.dev/submit/android/)

- [全体の流れ](https://docs.expo.dev/build/setup/#build-for-app-stores)
- [EASの前準備](https://docs.expo.dev/build/setup/)を参考にEAS-cliなどの準備

## ③ eas.json作成
```
$ eas build:configure
```
(app.json)
owner: "spelieve"追加して上記のコマンド打つと、expoのdashboardにプロジェクトが登録された
→app.jsonをもとにEAS用プロジェクト設定ファイルeas.jsonを作成

## ④ Credentialsの作成
- eas buildするにはcredentialsが必要 [公式記事](https://docs.expo.dev/app-signing/managed-credentials/)参考
  - buildする時に新たに作る促しされるが、Account Holderでない人がやる場合先に作っておく
- Apple Developer accountと紐づいている
### 3つ必要なものがある
- Distribution Certificate
- Provisioning Profiles
- Push Notification Keys

### IOSの場合
（[公式最初の説明](https://docs.expo.dev/build/setup/#ios-app-signing-credentials)）→[App Store ConnectでのCredentialsの作成方法、手順](https://qiita.com/c_tomioka/items/af5942b7031962c3faff)

### Distribution Certificate
自分（開発者）の証明書的なもの（？）
そのため、複数アプリをデプロイしても、同じDistribution Certificateとなる
期限切れてもデプロイ済みアプリに影響ないけど、新しいアプリをデプロイ時に更新必須
=> 野口のMacで登録できなかったため、[こちら](https://gist.github.com/boodle/77436b2d9facb8e938ad)を参考にlinuxを登録した。

### Provisioning Profiles
- １アプリにつき、１Provisioning Profiles
- 期限切れたら、更新必要！（12ヶ月で切れる）
- 期限切れてもデプロイ済みアプリに影響ないけど、新しいアプリデプロイ時に更新必須
```
$ eas build -p ios
or
$ eas credentials
```

## Internal Distribution([参照](https://docs.expo.dev/build/internal-distribution/))
チームメンバーの実機などにinstallする機能

1. eas.jsonの編集
2. Apple Developerへの登録
3. Credentialsの設定（Configure app signing）
4. buildコマンド(未達成)
```
$ eas build --profile preview ...
```

# その他
## チームメンバーとのExpo Projectの共有

- [x] Expo にorganization作成
- [x] 招待

[Sharing credentials with your team](https://docs.expo.dev/app-signing/managed-credentials/#sharing-credentials-with-your-team)参照

## App Store Connectにおける権限
***
注意：**個人**として登録したデベロッパがApp Store Connectにユーザーを追加した場合、追加されたユーザーはApp Store Connect内にある**デベロッパのコンテンツにのみ**アクセスでき、Apple Developer Programにおけるデベロッパのチームメンバーとはみなされません。
***
[参考記事](https://developer.apple.com/jp/support/roles/)

[AdminにCertificate作成ページへの権限与える方法](https://www.hnut.co.jp/entry/2019/02/23/122156)

### 料金
- a one-time $25 USD fee.

## 注意点
- EASは商用利用の場合は、毎月 $1,500 超の売上を稼いでいるプロジェクトは無料プランを使うことはできない（[EAS Fair Use Policy](https://expo.dev/eas/fair-use) を参照）。
- App IDとBundle IDは同じもの！(Apple DeveloperではApp IDと表示されていたり、AppStore ConnectではBundle IDと表示([参考](https://zenn.dev/moutend/articles/feebf0120dce6e6426fa)))
- profile(build profile)toha
  - ある特定のビルドを実行するために必要なパラメータを記述した、名前付きの設定グループ、
  - デフォルトでdevelopment, preview, productionがあり、自分でfoobarとか作れる
  - `eas build --profile foobar`とかで指定できる、指定しなければproductionになる
- 

## 参考記事
- [iosスクショ画像作り方](https://zenn.dev/kazuki23/articles/4c814b1f722669)
EAS(Expo Application Servise)のinternal distributionがいい(デプロイなどが楽）
（その他の選択肢としては Testflightなどがあるが、面倒）
- [証明書周り図解](https://zenn.dev/mhackit/scraps/355fe56dc7b4c8)
- [EASの前準備](https://docs.expo.dev/build/setup/)
- [expo internal distribution (英語）](https://docs.expo.dev/build/internal-distribution/)
- [EASからのリリース方法](https://zenn.dev/ryonakae/articles/be8373e700f26a) 
- [eas.jsonの設定](https://docs.expo.dev/submit/eas-json/)
- [Making Apple Developer certificates on Linux](https://gist.github.com/boodle/77436b2d9facb8e938ad)

### App Store Connect関連
- [App store connect 概要まとめ[日本語]（公式）](https://help.apple.com/app-store-connect/#/dev8bd4848f9)
### 古いバージョン
[simulator, リリース環境ともに説明あり](https://tetoblog.org/2021/07/%E3%80%90reactnative%E3%80%91expo%E3%81%AB%E3%82%88%E3%82%8Bios%E3%81%AE%E3%83%AA%E3%83%AA%E3%83%BC%E3%82%B9%E6%89%8B%E9%A0%86%E3%80%90%E3%83%93%E3%83%AB%E3%83%89%E3%81%8B%E3%82%89%E5%85%AC%E9%96%8B/)

**Comment by Takapy1** [comment]
@Ayato-kosaka 
iosアプリのビルドのためには[Apple developer program](https://developer.apple.com/jp/programs/)の登録が必要
これの年会費が高い($99/year、1万くらい)

**Comment by Ayato-kosaka** [comment]
@Takapy1 
おけー、App storeにデプロイするのが高いのは仕方ないから問題ない！
どこにクレジットカード登録すれば良いかわかる？？

**Comment by Takapy1** [comment]
@Ayato-kosaka 
証書お待ちを

**Comment by Takapy1** [comment]
@Ayato-kosaka 
リンク押して、Apple IDでサインインすれば
「Apple Developer Programにご登録ください」っていう表示が出るからそこから登録する

個人として登録する

**Comment by Takapy1** [comment]
[[Apple developer program登録後メンバー招待方法](https://developer.apple.com/jp/programs/)](https://www.zaico.co.jp/engineer/apple-developer-program-howto-add-member/)

**Comment by Takapy1** [comment]
[Apple developer program登録後メンバー招待方法](Apple developer program登録後メンバー招待方法)

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ありがとうー！
とりあえず金は払っといたけど、別途メールきたら言うわ！
野口のアカウントとの紐付けもわかったら教えてー

**Comment by Takapy1** [comment]
[Apple developer program登録後メンバー招待方法](https://www.zaico.co.jp/engineer/apple-developer-program-howto-add-member/)この方法でどうかな？

**Comment by Takapy1** [comment]
登録後の画面にいけないから、俺の方で試せなくて、記事が通りか試せない
すまん

**Comment by Ayato-kosaka** [comment]
@Takapy1 
全然問題ない〜
調べてくれてありがと！
メアドはどうすればいい？

**Comment by Takapy1** [comment]
@Ayato-kosaka 
Spelieve用gmail作る？

**Comment by Ayato-kosaka** [comment]
@Takapy1 
組織ごとに作るべきなら作ってもいいけど、
俺の個人のアップルIDで課金しちゃったから、
野口の個人のアップルIDでデベロッパー登録してくれればそれと紐付けできると思うよ

**Comment by Takapy1** [comment]
sonezakikaoru@gmail.comです

**Comment by Takapy1** [comment]
Apple用

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ありがとう！！
まだ本登録されてないからか、ユーザー登録できないから少々お待ちを

**Comment by Ayato-kosaka** [comment]
https://docs.expo.dev/eas-update/github-actions/
https://zenn.dev/hal1986/articles/20211225-eas-build-and-submit

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ごめん、電話したらiCloudメールに来てるって言う罠だったわ！
免許証の登録の必要があったみたいで申請したからもう直ぐ承認されると思う！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ついに通ったから招待送った！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
ついに来たか！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
https://expo.dev/accounts/spelieve/projects/Spelieve/builds/2fdad473-9e64-4bc9-958e-97a1ca768869
別のエラーが出てしまった。

```
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace ./Spelieve.xcworkspace -scheme Spelieve -configuration Release -destination generic/platform=iOS -archivePath "/Users/expo/Library/Developer/Xcode/Archives/2022-12-18/Spelieve 2022-12-18 07.06.34.xcarchive" archive
User defaults from command line:
    IDEArchivePathOverride = /Users/expo/Library/Developer/Xcode/Archives/2022-12-18/Spelieve 2022-12-18 07.06.34.xcarchive
    IDEPackageSupportUseBuiltinSCM = YES
Prepare packages
Computing target dependency graph and provisioning inputs
Create build description
Build description signature: 4e355e860f401df65cda6b9f81776d10
Build description path: /Users/expo/Library/Developer/Xcode/DerivedData/Spelieve-gsjalpxzxtdloeeimhjzkddgcnfm/Build/Intermediates.noindex/ArchiveIntermediates/Spelieve/IntermediateBuildFilesPath/XCBuildData/4e355e860f401df65cda6b9f81776d10-desc.xcbuild
note: Building targets in dependency order
warning: Run script build phase '[CP-User] Generate app.config for prebuilt Constants.manifest' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXConstants' from project 'Pods')
/Users/expo/workingdir/build/ios/Spelieve.xcodeproj: error: Provisioning profile "spelieve-apple-developer-prod" has app ID "com.spelieve", which does not match the bundle ID "com.example.Spelieve". (in target 'Spelieve' from project 'Spelieve')
/Users/expo/workingdir/build/ios/Spelieve.xcodeproj: error: Provisioning profile "spelieve-apple-developer-prod" doesn't support the Push Notifications capability. (in target 'Spelieve' from project 'Spelieve')
/Users/expo/workingdir/build/ios/Spelieve.xcodeproj: error: Provisioning profile "spelieve-apple-developer-prod" doesn't include the aps-environment 
```

う〜ん、"com.example.Spelieve" とか出てきてるのが怪しい気がするなぁ

**Comment by Takapy1** [comment]
@Ayato-kosaka 
app.jsonのbundleIDのせいだ！

**Comment by Takapy1** [comment]
iOSの中に適当に設定しちゃってると思う

**Comment by Ayato-kosaka** [comment]
おお〜
なるほど！
試してみる！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
試してみたら別のエラーが出たけど、mobileprovisionの設定する必要なくなった〜

https://expo.dev/accounts/spelieve/projects/Spelieve/builds/d41db830-4b02-4b40-83a5-b59aebc5a5d5

```
Error: Unable to resolve module ../../ENV from /Users/expo/workingdir/build/src/Place/Endpoint/PlaceHttpPost.ts: 
None of these files exist:
  * src/ENV(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  * src/ENV/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
```
import ENV が死んでるみたい。
他のログとか見てみて、恐らくローカルのソースコード見てるんじゃなくて、Github のソース取得していると思う。
だから、ENV.ts が無いと思う。

これどうすればいいんやろ〜〜〜 :thinking:

**Comment by Takapy1** [comment]
@Ayato-kosaka 
なるほどぅ、ENVはexpoのsecret画面から登録するのかなー

**Comment by Ayato-kosaka** [comment]
@Takapy1 
まじか、、、
それだと、環境変数が typescript として認識されなくなっちゃうから渋いなぁ〜
ローカルのコードでビルド出来るのが一番ベストやねんけどなぁ、、

**Comment by Ayato-kosaka** [comment]
ゴメン、俺の仮説が間違ってた。
.igitignore を参照してローカルから Expo build してるから、ENV.ts が消えてたみたい。
https://www.wheatandcat.me/entry/2022/05/26/091557
これを参考に、.easignore を .igitignore から、 ENV.ts を除いて作成したら、出来た〜〜〜〜〜〜〜〜〜〜〜〜〜〜〜〜〜〜〜〜

https://expo.dev/accounts/spelieve/projects/Spelieve/builds/b720152c-2111-43c3-bb7f-f4b74edd921f
![image](https://user-images.githubusercontent.com/53715839/208308175-21d414be-5ff5-4255-a3af-8d303f752308.png)

**Comment by Ayato-kosaka** [comment]
@Takapy1 

30f74a5 で取り合えず、ビルド成功したところまでのソースコードをdevelopにプッシュしておいた！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
ありがとうすぎた

**Comment by Takapy1** [comment]
@Ayato-kosaka 
[Google Developerページ](https://developer.android.com/)に行って、
[Google devleper登録方法](https://smilekao.com/news/3422#:~:text=https%3A%2F%2Fplay.google.com,%E3%81%97%E3%81%A6%E6%94%AF%E6%89%95%E3%81%86%E3%80%8D%E3%82%92%E3%82%AF%E3%83%AA%E3%83%83%E3%82%AF%E3%80%82)を参考に登録してもらえると助かります！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
個人用と組織用どっちがいいの？

**Comment by Ayato-kosaka** [comment]
あ、組織用だと組織の証明がいるのか

**Comment by Ayato-kosaka** [comment]
@Takapy1 
個人で作って金払うけど問題なければ返信お願い〜

**Comment by Takapy1** [comment]
@Ayato-kosaka 
組織の情報とかないから個人用じゃないと作れないから個人用でおっけー！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ユーザー作成・支払い:完了
アプリの追加:完了
野口招待:承認待ち

↑で対応したー

**Comment by Takapy1** [comment]
@Ayato-kosaka 
ありがとう承認した。
Appleと違って有効化は即時なのかな

**Comment by Ayato-kosaka** [comment]
@Takapy1 
AIで免許証とか確認してた。やっぱGoogleちげえ

**Comment by Ayato-kosaka** [comment]
@Takapy1 
GithubActions の EAS Build Preview Release でブランチ選択出来るから、適当なブランチ切ってJOB流せば、一旦野口の環境でも Preview 環境に持っていけるはず！

![Image](https://user-images.githubusercontent.com/53715839/209418731-7091723d-e00b-42f4-9c01-2d0e3221150c.png)

**Comment by Ayato-kosaka** [comment]
@Takapy1 
`eas build --profile development --platform ios`
と
`eas build --profile preview --platform ios`
の違いってわかる？
→恐らく eas.json の build.development か build.preview のどっちを使うかの違いだと思う

eas build --profile development --platform ios でビルドして、
ローカルのターミナルで、`expo start --dev-client`
ログ見れた！！！

↓参考
https://docs.expo.dev/development/create-development-builds/

![image](https://user-images.githubusercontent.com/53715839/209424175-974762e5-7965-491e-9d0f-c9cd767d531f.png)

**Comment by Ayato-kosaka** [comment]
Sentryでログ見る必要はなくなったね

**Comment by Takapy1** [comment]
@Ayato-kosaka 
なるほどぅ、家帰ったらやってみる

**Comment by Ayato-kosaka** [comment]
eas build development は、app.json 変えたときくらいしか流さなくて良いみたいだから、一応 GithubActions 作って夜間JOBにしておいた〜

**Comment by Ayato-kosaka** [comment]
@Takapy1 
GoogleMapが起動出来ないのは、
https://docs.expo.dev/versions/latest/sdk/map-view/#add-the-api-key-to-your-project-1
多分やってないからだね。（web 以外、GoogleMapのAPIキー入れてない。。逆に今までなんで起動できてたんだ、、）

-> iOS 用の API_KEY 作って、eas secret に入れた。
その影響で、app.json => app.config.ts に変えたら動いた〜〜〜〜

TODO:

- [ ] Android も設定する（https://docs.expo.dev/versions/latest/sdk/map-view/#copy-your-apps-sha-1-certificate-fingerprint）

**Comment by Ayato-kosaka** [comment]
@Takapy1 
Itinerary が映らないバグは巻き取るわ

**Comment by Ayato-kosaka** [comment]
@Takapy1 
治った！！！！！
原因は material-top-tabs で、
https://reactnavigation.org/docs/getting-started/#installation
↑の Installation に沿って依存関係の install が出来ていなかった、、（大反省、、 :cry:  ）

**Comment by Ayato-kosaka** [comment]
6時間くらいかかったｗｗｗｗ

**Comment by Takapy1** [comment]
@Ayato-kosaka 
ありがとうすぎる

**Comment by Takapy1** [comment]
> -> iOS 用の API_KEY 作って、eas secret に入れた。
> その影響で、app.json => app.config.ts に変えたら動いた〜〜〜〜

ここがまだ理解できてないわ
- app.jsonは名前変えるだけでいいのか？
- secretはdevelopmentの方をコピればいいんだよね

**Comment by Ayato-kosaka** [comment]
@Takapy1 
明日対面で伝えるわ！
Android 進めるためだったら、Android もGCPのAPIKYEの設定自体はしておいたよ！

2の
Copy your app's SHA-1 certificate fingerprint
ができなかった！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
すまん、お願いします！！！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
App Store Connectにアップロードの時になぜか認証の部分でエラーになるなー
```
[stderr] [!] Error uploading ipa file: 
[stderr]  [Application Loader Error Output]: Error uploading '/var/folders/h2/gp9wlkv11lg0qj6y2mnqgc_40000gn/T/cbbc9936-977f-4d88-8967-ae5d0b5deca8.ipa'.
[stderr] [Application Loader Error Output]: Unable to upload archive. Failed to authenticate for session: (
[stderr] [Application Loader Error Output]: The call to the altool completed with a non-zero exit status: 1. This indicates a failure.
Fastlane pilot failed
fastlane exited with non-zero code: 1
Failed to submit the app
Invalid ASC API JSON key - check your key ID, issuer ID and private key
```

**Comment by Takapy1** [comment]
@Ayato-kosaka 
[Expo のCredentials](https://expo.dev/accounts/spelieve/projects/Spelieve)の一番下のApp Store Connect API Key部分の情報と
App Store ConnectのAPI Keyの情報が一致しているか確認してほしい(issuer IDとか)

App Store Connectの方が俺の権限だと見れないから

**Comment by Ayato-kosaka** [comment]
@Takapy1 
確認したら違うみたいだった！
再登録したいけどやり方わからんくなっちゃったから、今晩教えて〜

**Comment by Takapy1** [comment]
@Ayato-kosaka 
確認ありがとー！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ゴール：審査してもらえるまで

# 手順まとめ

## 準備
- [x] Developer登録
- [x] eas-cliとかのinstall

## 1. アプリのビルド
1. - [x] eas buildを実行(binaryファイルの作成)
2. - [x] eas.json をsubmit部分を修正([参考](https://docs.expo.dev/submit/eas-json/))
3. - [x] App Store Connect API Key 生成、設定

## EAS→App Store Connect(ASC)へ提出
  - [ ] appleId, appleTeamId, EXPO_APPLE_PASSWORDがapp.jsonに設定されている
  - [ ] どのbinaryファイルを提出するのか(submitコマンド時に --latestすればskipされる)
5. - [ ] `$ eas submit --platform ios`の実行  

⚠️EASはASCへの提出を簡単にできるだけ！最終的な提出はASCの画面で行う

## ASC→App Storeへ提出
### iOS App 画面
- [x] スクショとかを撮ってupload(審査の時に使用)
- [x] プロモーション用説明
- [x] 概要(**必須**)
- [x] キーワード(**必須**): 検索時にヒットさせるため
- [x] サポートURL(**必須**): 開発者への連絡のために必要（お問い合わせフォーム的な）
- [x] 著作権設定(**必須**)
- [ ] ビルド(**必須**):　ここにビルドファイルupload

[上記項目の意味参考](https://www.bravesoft.co.jp/blog/archives/4838)

### [一般] App情報
- [x] アプリ名(**必須**)
- [x] サブタイトル(アプリのキャッチコピー)
- [x] コンテンツ配信権(**必須**)
（外部API使用しているので、最初の質問は**はい**([参考](https://kinsentansa.blogspot.com/2016/03/ios-20163.html)))
- [x] アプリの対象年齢(質問にいくつか答えるだke)
- [x] カテゴリー

### [一般] 価格および配信状況
- [x] 価格はFreeにした

### [一般] Appのプライバシー
- [ ] 

## CI使う場合
- eas.jsonに必要な情報の記述
- 環境変数

## 参考
- [[JP]公開までの流れ、App Store Connectなどの設定項目](https://zenn.dev/moutend/articles/feebf0120dce6e6426fa#%E3%81%AF%E3%81%98%E3%82%81%E3%81%AB)
- [App Store Connectの設定項目、流れ、わかりやすい](https://www.create-forever.games/unity-ios-app-store-ipa5/)

**Comment by Ayato-kosaka** [comment]
@Takapy1 
# デプロイ手順

## 全体
- [x] 1. Google Play Developer accountの登録（有料）
- [x] 2. [Google Play Console](https://play.google.com/apps/publish/)画面でApp作成
- [x] 3. eas cliのinstall
- [x] 4. keyStoreの作成(`eas build --platform android`から自動で生成された)
- [x] 5. [Google Service Account](https://cloud.google.com/iam/docs/creating-managing-service-accounts)を作成([方法参照](https://github.com/expo/fyi/blob/main/creating-google-service-account.md)), privatekey
- [x] 6. 2で作成したAPI keyをGoogle Service Account Key(Expo のCredentialsの一番下)に設定
- [x] 7. ビルド
- [ ] 8. EAS→Google Play Storeへ提出
- [ ] 9. Google Play Storeからデプロイ


## 4. ビルド（[公式](https://docs.expo.dev/build-reference/android-builds/))([日本語解説版](https://qiita.com/nyankiti/items/f8316bd426a2f9c6625c))

### local step
- [x] 1. cli.requireCommit設定→無視
- [x] 2. Credentialの設定([Android Credential設定](https://docs.expo.dev/app-signing/app-credentials/#android))
- [x]   2.2. `builds.android.PROFILE_NAME.credentialsSource`にすると、EAS serverの方のCredential使ってくれる!

- [x] keyStoreの作成

### remote step
(必要ないのか???)

## 8. EAS→Google Play Storeへ提出
- EASに自分のアプリが存在するか確認
- android packageの確認？？？
- [ ] `eas submit -p android`で提出

## Google Play Storeからデプロイ([方法](https://github.com/expo/fyi/blob/main/first-android-submission.md))
- Play StoreのDashboardの各項目(Set up your app etc)を流れ通りに行う


## 参考
- [[EN] easを使用したplay storeへのsubmit方法](https://www.notjust.dev/blog/2022-04-11-how-to-publish-expo-react-native-app-to-google-play-store)

**Comment by Ayato-kosaka** [comment]
#425, #427
