### ISSUE TITLE
開発環境用プロジェクトを作成する

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#263]

**Comment by Ayato-kosaka** [comment]
@Takapy1 
envの扱いって決まった？
まだやったら調べてみるよ！
開発環境とわけるのにenvでやる予定やから

**Comment by Takapy1** [comment]
@Ayato-kosaka 
.env作って一旦process...で参照する様にしてる。
コンパイルすると、キー見れちゃうらしくてあんまり良くないけど、gitにpushは出来るようにした。

**Comment by Ayato-kosaka** [comment]
@Takapy1 
なるほど、そんなことができるのか。
オッケー！
一旦それでやって問題はiOSとかで動くかやけど、それはまた考えるか

**Comment by Ayato-kosaka** [comment]
@Takapy1 
[spelieve-dev](https://console.firebase.google.com/project/spelieve-dev/firestore)
新しくFirestore作った！
データベース初期化されているから気をつけて！

https://github.com/Ayato-kosaka/spelieve/pull/269
の変更を develop にマージしたから、develop から PULL すれば使えるはず！

https://docs.google.com/document/d/1UJ4Gb9jsKOQR_-VtxvsausvBRlK0sZqEEEtsiV333bo/edit
envファイルは個々に配置してる！
src/ENV.ts に貼り付ければOK！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
[spelieve-dev](https://console.firebase.google.com/project/spelieve-dev/firestore)
新しくFirestore作った！
データベース初期化されているから気をつけて！

https://github.com/Ayato-kosaka/spelieve/pull/269
の変更を develop にマージしたから、develop から PULL すれば使えるはず！

https://docs.google.com/document/d/1UJ4Gb9jsKOQR_-VtxvsausvBRlK0sZqEEEtsiV333bo/edit
envファイルは個々に配置してる！
src/ENV.ts に貼り付ければOK！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
[spelieve-dev](https://console.firebase.google.com/project/spelieve-dev/firestore)
新しくFirestore作った！
データベース初期化されているから気をつけて！

https://github.com/Ayato-kosaka/spelieve/pull/269
の変更を develop にマージしたから、develop から PULL すれば使えるはず！

https://docs.google.com/document/d/1UJ4Gb9jsKOQR_-VtxvsausvBRlK0sZqEEEtsiV333bo/edit
envファイルは個々に配置してる！
src/ENV.ts に貼り付ければOK！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
権限ないかも

**Comment by Ayato-kosaka** [comment]
@Takapy1 
うそん
これ違う？
![image](https://user-images.githubusercontent.com/53715839/197385496-b15cb58a-2a22-462c-8b5a-794175053412.png)

**Comment by Takapy1** [comment]
@Ayato-kosaka 
あってるよね

**Comment by Takapy1** [comment]
spelive-devのリンクが違うのかな

**Comment by Ayato-kosaka** [comment]
あ、権限がないっていうのは、Google docsじゃなくて、firebaseのってことか

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ごめん追加漏れてたから今追加した！
