### ISSUE TITLE
[PMC01101GoogleMapPlacesList]　Mapの範囲調整

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#274]
小田原市を選んだら小田原市全体になるように範囲調節したい（第一希望）
or
絞り込まれたピンが収まるように範囲調節したい

**Comment by Takapy1** [comment]
placesListが変わると
 PMC01101GoogleMapPlaceListのピンと地図の中心も変わるようにしたい。

問題
placesListが変更されても、PMC01101GoogleMapPlaceListが再レンダリングされない

**Comment by Takapy1** [comment]
問題
- ピンの範囲の調整

**Comment by Ayato-kosaka** [comment]
@Takapy1 
これって未対応だっけ？

**Comment by Takapy1** [comment]
@Ayato-kosaka 
数字は調節したよ！
