### ISSUE TITLE
初期language 検討

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#281]
## Why
Place Autocomplete 等初期値としてlanguageを設定する必要がある

## What
どのようにして language を取得するか検討する。

## 子issue
- [ ]

**Comment by Takapy1** [comment]
端末の言語設定の取得：[react-native-localize](https://www.npmjs.com/package/react-native-localize)

**Comment by Ayato-kosaka** [comment]
@Takapy1 
expo-localization 大賛成！
I18n とも絡めて、アプリの言語もlexpo-ocalizationで統一したいね

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ただ、初期言語も優先度そんなに高くないから、時間がかかりそうなら後回しでOK

**Comment by Takapy1** [comment]
expo localizeでi18n.t使っている部分を多言語化は簡単にできたんだけど、
PPA002にlanguage propsっていらなくない？

**Comment by Ayato-kosaka** [comment]
@Takapy1 
承知した
> PPA002にlanguage propsっていらなくない？

PCTに埋めるってことやんな？それでOKだと思う！

ちなみに、PContext から、初期言語を読む仕組みって、初期言語がprovider でグローバルstateになってる認識で大丈夫？

language をユーザーが変更出来る仕組みを作った時に、変更検知して、placeを再フェッチする仕組みになってるか気になってる、

**Comment by Takapy1** [comment]
@Ayato-kosaka 
- 言語がどこで変更されるのか
- 変更した場合どこが変わるようにするのか

などイメージがついてない部分が多いから、一旦飛ばすわ

**Comment by Ayato-kosaka** [comment]
@Takapy1 
**PHK001_GooglePlaceAPI**
```
const GooglePlaceLanguageTagFromIETFLanguageTag = (key) => {
	"ja": "ja",
	"en": "en"
}[key]
```

ja => `GooglePlaceLanguageTagFromIETFLanguageTag[i18n.locale]`

**Comment by Ayato-kosaka** [comment]
@Takapy1 
これ解決済みなら、クローズしておいて！

**Comment by Ayato-kosaka** [comment]
いや、若干残ってるのか、

**Comment by Ayato-kosaka** [comment]
@Takapy1 
終わってるからクローズします！
