### ISSUE TITLE
Context 内で画面遷移する

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#286]
## Why
同じContextを参照したい場合に、画面遷移の度にfetchし直す必要が生じるため

## What
Context 配下で画面遷移する方法を検討する

## 子issue
- [ ]

**Comment by Ayato-kosaka** [comment]
@Takapy1 
react-navigation について全然わかっていないんだけど、ContextでFetchしたデータを持続させて画面遷移って出来るかぱっとわかる？

**Comment by Takapy1** [comment]
@Ayato-kosaka 
持続は多分無理だと思う！
navigationで画面遷移すると、webのredirectと同じでpageごと変わる。

ContextはPageの中の一部だから、pageが変わればcontextも再レンダリングで、持続させるのは無理なんじゃないかな

**Comment by Ayato-kosaka** [comment]
@Takapy1 
それってめっちゃ困るんだよね、、、
Userとかだったら、画面遷移する度に再fetch、再認証とかは避けたいよね、
Contextをnavigation よりもっと上階層に配置するしかないのかな

**Comment by Takapy1** [comment]
@Ayato-kosaka 
今App.taxでnavigation 使ってて、各page内でcontextしている状態だから、上記のように無理だけど、Userとかを作っていく場合App.tsxとPageの間にもう一つコンポ挟んでそこでuserのstate管理すればよさそうかな

**Comment by Ayato-kosaka** [comment]
@Takapy1 
今
App.tsx
-> navigation
-> ->  Page
-> -> -> Context

だけど
App.tsx
-> Context(Itinerary, Place, User × One, List, Map すべて)
-> -> navigation
-> -> -> Page

にすればいいのかな？

**Comment by Ayato-kosaka** [comment]
かなり高頻度で再レンダリングされるから、useMemo, useCallbackの制御大変そうだけど、画面遷移する度にfetchする仕様よりはマシな気がする。

**Comment by Takapy1** [comment]
@Ayato-kosaka 
Reactって本来であれば、
index.ts(アプリの最上位,現在のApp.tsx)
-- App.tsx
　　　　-- 各Page
っていう構成でApp.tsxでUserとかの管理すると思うから、
- App.tsxとpageの間になにかコンポ挟む
- App.tsxの親コンポ作って、App.tsxでuser管理
のどっちかにするのがいいかな

**Comment by Takapy1** [comment]
> かなり高頻度で再レンダリングされるから、useMemo, useCallbackの制御大変そうだけど、画面遷移する度にfetchする仕様よりはマシな気がする。

そうやね、それがReactっぽい実装だと思う

**Comment by Ayato-kosaka** [comment]
@Takapy1 
なるほどぉ
Page配下にcontextの考えがそもそもミスってたのか、、、
かなり考え直さないとまずいな、、
Pageよりcontextが上になるとplaceOneとかitineraryOneはvalueがundifined許容になるね。
ちょっと全体的に考え直すわ！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
そうなるね、明日相談やな

**Comment by Ayato-kosaka** [comment]
@Takapy1 
そうやな！
一旦以下で考えてる
変更点

1. 親子関係：Page が親 -> Context が親
1. Context は、providerProps を children 以外持たない
1. `ActivityIndicator animating`の責務 ：Context -> Page
1. ContextValInterface は undifined を許容し、それを参照してreturn ActivityIndicator する（必要に応じて isLoading を ContextVal で渡す）


82ec720 でとりあえず、itineraryOneだけ実装してみた。

**Comment by Ayato-kosaka** [comment]
Pageもだいぶスッキリした！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
この方法をとると、
Page: 'Itinerary', URL: '/itinerary/1'
から
Page: 'ItineraryEdit', URL: '/itinerary/1/edit'
に遷移`navigation.navigate('ItineraryEdit', {itineraryID; 1})`した時に、
ItineraryEdit のuseEffect で ItineraryOneContext の `setItinerayID(1)` すると思うねんけど、
ItineraryOneContext の useEffect の第２引数が、itineraryID の変化をウォッチしてるけど、`setItinerayID(1)`でitineraryID に変化がないから、再フェッチは起こならいで良いよね。

**Comment by Takapy1** [comment]
@Ayato-kosaka 
そうだね、同じ値だから再fetchは起きない

**Comment by Ayato-kosaka** [comment]
じゃあクローズするね！
