### ISSUE TITLE
ContextとPageの関係性を逆にする

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#292]

**Comment by Takapy1** [comment]
問題点
- ContextProviderのコンポーネントはどこに配置するか
- Contextはどのタイミングで読み込みがされるのか？

以前まで
- Pageが読み込まれる→Context読み込み
　-　無駄なContext読み込みは起こらない

これから
- navigation Stack読み込まれる→Context全て読み込み
にならないのか？

**Comment by Takapy1** [comment]
@Ayato-kosaka 
ディレクトリ構成はどうしようか
```javascript
<PCT011MPlacesListProvider>
	<PPA001Places />
</PCT011MPlacesListProvider>
```
みたいにするには、新しいファイルが必要になるか

**Comment by Ayato-kosaka** [comment]
@Takapy1 
PlacePageNavigatorにContext入れる想定だった
うまく動かなかったら教えてー

**Comment by Ayato-kosaka** [comment]
<PCT011MPlacesListProvider>
　　<Stack.Screen name="Places" component={PPA001Places} />
</PCT011MPlacesListProvider>

**Comment by Takapy1** [comment]
@Ayato-kosaka 
その予定でProvider挟んだら、超怒られた

```
<Stack.Navigator initialRouteName="PPA001Places">
	<PCT011MPlacesListProvider>
		<Stack.Screen name="PPA001Places" component={PPA001Places} />
	</PCT011MPlacesListProvider>
	<Stack.Screen name="PPA002Place" component={PPA002Place} />
</Stack.Navigator>
```

NavigatorにはScreenとかしか入れちゃいけないらしい泣
```
Error: A navigator can only contain 'Screen', 'Group' or 'React.Fragment' as its direct children (found 'PCT011MPlacesListProvider'). 
To render this component in the navigator, pass it in the 'component' prop to 'Screen'.
```

**Comment by Takapy1** [comment]
@Ayato-kosaka 
要するにcomponentのところで指定するのはPPAPlacesとかじゃなくて、
下記をreturn するコンポじゃないといけないってことだから、PPAとは別のファイルが必要になりそうだ。
```
<PCT011MPlacesListProvider>
　　<PPA001Places />
</PCT011MPlacesListProvider>
```

**Comment by Ayato-kosaka** [comment]
@Takapy1 
え、それじゃContext間の画面遷移問題なにも解決してないやん笑

**Comment by Ayato-kosaka** [comment]
ちゃんと確認するべきやった、ミスったわ

**Comment by Ayato-kosaka** [comment]
@Takapy1 
Appp.tsx でnavigation containerより上に書いたらどうなる？

**Comment by Takapy1** [comment]
@Ayato-kosaka 
いけたー！
Appを囲むProviderみたいな層を作ってそこにContext系を集めるのがいいかな

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ありがとー！
一旦それで行こう！
Context全部集めるのナンセンスやから若干調べてみるけど、わからなかったら全部集めるでいいや、

**Comment by Takapy1** [comment]
@Ayato-kosaka 
確かにスコープとか考えるとナンセンスやな

**Comment by Ayato-kosaka** [comment]
@Takapy1 
Stacknavigator より上なら使えるみたいやから
PlacePageNavigatorにContextを入れることはできるのかな？（Pageごとにcontextを分けることはできないけど）
![image](https://user-images.githubusercontent.com/53715839/199455213-de700804-fcd7-4732-8ce5-fdcdb6c47e13.png)

**Comment by Ayato-kosaka** [comment]
<PCT011MPlacesListProvider>
<Stack.Navigator initialRouteName="PPA001Places">
	<Stack.Screen name="PPA001Places" component={PPA001Places} />
	<Stack.Screen name="PPA002Place" component={PPA002Place} />
</Stack.Navigator>
</PCT011MPlacesListProvider>

**Comment by Ayato-kosaka** [comment]
> @Ayato-kosaka 
> ディレクトリ構成はどうしようか
> ```javascript
> <PCT011MPlacesListProvider>
> 	<PPA001Places />
> </PCT011MPlacesListProvider>
> ```
> みたいにするには、新しいファイルが必要になるか
> 

そっかページごとに分けたかったらこれでいいのか

**Comment by Ayato-kosaka** [comment]
@Takapy1 
んー、↑でやるとpageの概念（urlのパラメータの処理）とcontextの概念（fetchしたデータのグローバル化）
がぐちゃぐちゃになるから、

https://github.com/Ayato-kosaka/spelieve/issues/292#issuecomment-1299943229
これか

https://github.com/Ayato-kosaka/spelieve/issues/292#issuecomment-1299923717
これがいいな、
前者がいいけど、動かないなら後者でいこう！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
なるほど、stackより上ならいけるんか

**Comment by Takapy1** [comment]
@Ayato-kosaka 
いけるね、
```
<PCT011MPlacesListProvider>
    <Stack.Navigator initialRouteName="PPA001Places">
	    <Stack.Screen name="PPA001Places" component={PPA001Places} />
	    <Stack.Screen name="PPA002Place" component={PPA002Place} />
    </Stack.Navigator>
</PCT011MPlacesListProvider>
```
これにします。

**Comment by Ayato-kosaka** [comment]
よしゃーーー！！あひがとおー！
@Takapy1

**Comment by Ayato-kosaka** [comment]
> navigation Stack読み込まれる→Context全て読み込み
にならないのか？

ご指摘の通りだから、001なら、country 002 なら、place_id + language がundefinedだったらfetchしないように useEffect で制御しないと　
@Takapy1

**Comment by Takapy1** [comment]
@Ayato-kosaka 読み込まれたわ

**Comment by Takapy1** [comment]
めも
# 構成まとめ
App
- ContextProvider
  - Stack 
    - Page (Itinerary, Placeなど)

# PPA001 
## 初期状態
PageのParamsから渡ってきたアドレスで検索
ex) 
- 普通：日本だけとか
- URLで検索してきた場合：その住所で検索

## 住所再検索
onAutoCompleteClicked動く
### 地点の場合：PPA002へ遷移
***
この関数onPlaceSelectedはどこに定義しようか??? 
PCTMPlacesListの中に入れて。グローバルで管理した方がいいと思った。
***

### 地名の場合：setSearchedAdressが動く
→PCTPlacesが再レンダリング(placesListを再取得)


## 画像押した時

# PPA002
## 初期状態
place_idに入っているidで場所を取得or作成

**Comment by Ayato-kosaka** [comment]
@Takapy1 
> この関数onPlaceSelectedはどこに定義しようか???

Controller はPage Controller に集める想定だったけど、
Context の方がいいの？

**Comment by Ayato-kosaka** [comment]
@Takapy1 

> PCT001にした（理由：PCT001はPCT002のsetPlaceIdをつかる必要性ある、逆にPCT002がPCT001の関数を呼び出す状況はない)

PPA002に遷移したらuseEffectで
setPlaceID 想定だった

**Comment by Takapy1** [comment]
@Ayato-kosaka 
①
> Controller はPage Controller に集める想定だったけど、
> Context の方がいいの？

Controllerに集めた方が、記述少なくなったから、Controllerに集めるわ

②
> PPA002に遷移したらuseEffectで
> setPlaceID 想定だった
全然思いつかなかったわ、そっちの方が良さそう、
