### ISSUE TITLE
バックエンド経由で、GoogleMapAutocompleteを利用可能にする

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#309]
## 子issue

- [ ] [[バックエンド] GoogleからPlaceデータの取得](https://github.com/users/Ayato-kosaka/projects/1/views/6#)
- [ ] [[フロント] auto-completeコンポ実装](https://github.com/users/Ayato-kosaka/projects/1/views/6#)

### input入力の際( [place autocomplete](https://developers.google.com/maps/documentation/places/web-service/autocomplete))
リクエスト: input送信
レスポンス: place nameの表示(place_idも取得)

### autocompleteの選択された場所
- さらにdetail取得([place detail](https://developers.google.com/maps/documentation/places/web-service/details))

## 参考リンク
- [placeautocomplete client lib github](https://github.com/googlemaps/google-maps-services-js/blob/master/src/places/autocomplete.ts)

**Comment by Ayato-kosaka** [comment]
@Takapy1 
proxy サーバー立てるの面倒だから、
バックエンドにAPI通すで良いと思うけどどうかな。
その場合、autoComplete と fetchDetail を実装する形になると思うけど、fetchDetail は、PBL002UpsertPlaceData と統合させて、Firestore にキャッシュさせれば、安い作りになりそう。
また、会話させて！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
速度的にプロキシ設定してどれだけ早くなるのか不明だし、
リリースファーストだからバックエンドにAPI通す方がいい気がしてきた。

**Comment by Takapy1** [comment]
@Ayato-kosaka 
  一番上の流れだと、place autocomplete取得の時と、detail取得の時で
バックエンド分けた方がいい気がする

**Comment by Takapy1** [comment]
現在のPlacesControllerのonAutoCompleteClickedはdetailsだけ引数に受け取るようにする

**Comment by Ayato-kosaka** [comment]
@Takapy1 
そうそう、

https://github.com/Ayato-kosaka/spelieve/issues/309#issuecomment-1336120828
ここでも書いたけど、
detail とautocomplete は分けるつもりだよ！
で、detailは、
PBL002	UpsertPlaceData
の戻り値を拡張させればOKだと思う！
