### ISSUE TITLE
無限fetchする

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#313]

**Comment by Takapy1** [comment]
@Ayato-kosaka 
issueにしました。

**Comment by Ayato-kosaka** [comment]
toQueryをuseEffectから消したら起きない

**Comment by Ayato-kosaka** [comment]
=toQuery が毎回変わっている
=placeCollectionRef が毎回変わっている
=> placeCollectionRef にuseMemoをつける
**治った**

**Comment by Ayato-kosaka** [comment]
でも、画面表示されない

**Comment by Ayato-kosaka** [comment]
→if(placeList.isEmpty)にelse→setIsLoading(false);がない
→追加
**治った**

**Comment by Ayato-kosaka** [comment]
バグ３
/Place/PPA001Places
でアクセスすると、永遠にローディングする

**Comment by Ayato-kosaka** [comment]
setParamsでは画面遷移出来ないみたい
→navigation.navigate で同一画面に遷移し、URLを更新
