### ISSUE TITLE
Google Map Direction API 使い方検討

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#330]
## Why
[Google Map Direction API](https://developers.google.com/maps/documentation/directions/get-directions)を使って経過時間を計算したいが、使い方がわからないため

## What
https://qiita.com/masuda-sankosc/items/9e8cf167b2e57a347ea7
↑を参考にしたがうまく行かないので、使い方を検討する

## 子issue
- [ ]

**Comment by Ayato-kosaka** [comment]
@Takapy1 
https://qiita.com/masuda-sankosc/items/9e8cf167b2e57a347ea7
を参考に
https://github.com/Ayato-kosaka/spelieve/blob/feature/IPA001itinerary/src/Itinerary/Models/IDB03Plans/Contexts/ICT031PlansMap/ModelComponents/IMC03102TrafficMovementEdit/TrafficMovementEdit.tsx#L30-L38

**Comment by Takapy1** [comment]
@Ayato-kosaka 
Itineraryの方のNavigatorをLoadScriptで囲ってみて！
多分APIが読み込まれてないからだと思う

**Comment by Takapy1** [comment]
https://github.com/Ayato-kosaka/spelieve/blob/develop/src/Place/Pages/PlacePageNavigator/PlacePageNavigator.web.tsx
```javascript
// PlacePageNavigator.web.tsx
export const PlacePageNavigator = ({ navigation }: NativeStackScreenProps<BottomTabParamList, 'Place'>) => (
	// <PCT012MPlaceOneProvider parentDocRef={undefined} initialPlaceId="" language="ja">
	<PCT011MPlacesListProvider>
		<LoadScript googleMapsApiKey={ENV.GCP_API_KEY}>  // ここ！
			<Stack.Navigator initialRouteName="PPA001Places">
				<Stack.Screen name="PPA001Places" component={PPA001Places} initialParams={{}} />
				{/* <Stack.Screen name="PPA002Place" component={PPA002Place} initialParams={{ place_id: '', language: '' }} /> */}
			</Stack.Navigator>
		</LoadScript>
	</PCT011MPlacesListProvider>
	// </PCT012MPlaceOneProvider>
);
```
