### ISSUE TITLE
英語版でPlace検索初期表示で何も表示されない

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#334]
## Why
検索地の初期値が日本語で`country=日本&administrativeAreaLevel1=神奈川県&administrativeAreaLevel2=&locality=横浜市`のため

## What
英語に対応する

## 子issue
- [ ]

**Comment by Ayato-kosaka** [comment]
@Takapy1 
バグ見つけたからとりあえず起票
備忘でItiration 6 にしているけど、いつ対応するかは検討会で考えよう

**Comment by Takapy1** [comment]
i18nに入れる
