### ISSUE TITLE
Transit での Directions が必ず "ZERO_RESULTS" を返す

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#337]
## Why
色々試みたがどのリクエストでもTransit での Directions が"ZERO_RESULTS" を返す。
別途相談するため一旦保留とする。

## What
解決方法を検討する

## 子issue
- [ ]

**Comment by Takapy1** [comment]
@Ayato-kosaka 
何でやろうな

**Comment by Ayato-kosaka** [comment]
結構調べたけどよくわからんかった、
また明日相談させて！
@Takapy1

**Comment by Ayato-kosaka** [comment]
@Takapy1 
おいおいクソじゃねぇか！
Google Map Directions API で日本国内の路線検索はできない
らしい！！！！！
https://qiita.com/seigo-pon/items/bff784040e9e46dc8a56

**Comment by Takapy1** [comment]
@Ayato-kosaka ガチかよ
困るな
