### ISSUE TITLE
ElasticSearch環境構築

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#352]
@Ayato-kosaka 
現在、野口のアカウントで14日間のトライアル期間でElastic Searchを利用している
今後を考えてspelive用のアカウントを作成し、開発・本番環境のデプロイ環境を作成する

アカウント作成すると、強制的にデプロイする必要がある

**Comment by Ayato-kosaka** [comment]
@Takapy1 

作ってクレジットカード登録しておくから、サイト教えてー

**Comment by Ayato-kosaka** [comment]
@Takapy1 

https://www.npmjs.com/package/@elastic/elasticsearch

しらべたかんじ、これ使えばオッケーだと思う！

main.jsで

const client = new Client({
  cloud: { id: '<cloud-id>' },
  auth: { apiKey: 'base64EncodedKey' }
})


して、それぞれのサービスで

client.xxx

みたいな

**Comment by Takapy1** [comment]
main.js内で上のように定義すると、
clientっていう変数をserviceで使えなくない？
export するとエラーになる、多分関数内だからかな

**Comment by Ayato-kosaka** [comment]
@Takapy1 
あー、ほんまやな、よくわからんな、、


https://www.npmjs.com/package/@nestjs/elasticsearch
この npm モジュールが、@elastic/elasticsearchをオーバーラップしてるみたいやから、これ使えば出来るかも

**Comment by Takapy1** [comment]
どうにかできそう

**Comment by Takapy1** [comment]
環境変数はprocess.envでアクセスするわ

**Comment by Ayato-kosaka** [comment]
おけー！
