### ISSUE TITLE
フロントエンドでエラーが起きたら、初期画面に戻りたいが戻れない

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#361]
フロントエンドでエラーが起きたら、初期画面に戻りたいが戻れない
[navigation.navigate が動かない](https://github.com/Ayato-kosaka/spelieve/issues/361)

**Comment by Takapy1** [comment]
引数で渡したnavigatonじゃなくて、
PPA001Places/PlacesController内みたいにuseNavigationしないと動かないのかな？

**Comment by Ayato-kosaka** [comment]
useNavigate なら動いた？
あんまり、react-navigation 理解できてないから、整理しないとダメだね
@Takapy1

**Comment by Ayato-kosaka** [comment]
経路検索に失敗したらメッセージを出したい
