### ISSUE TITLE
Elastic Search の課金原因調査

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#368]

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ラインで送ったやつ、ここで調査しよう。
俺も調査してみるけど、このまま3日で1万ペースで進んじゃうと、次の請求では10万くらいになっちゃって破産だから、早急に原因追求したい。

**Comment by Ayato-kosaka** [comment]
https://qiita.com/oieioi/items/d84707e1bb59341bca48

Searchly ってのが安いみたい

でもelastic cloudでも1600円って書いてるから謎だよね

**Comment by Ayato-kosaka** [comment]
https://qiita.com/oieioi/items/d84707e1bb59341bca48

Searchly ってのが安いみたい

でもelastic cloudでも1600円って書いてるから謎だよね

**Comment by Takapy1** [comment]
スタンダードプランとかは多分入ってなくて、elasticseRchのインスタンスのせいだとおもうんよね

**Comment by Ayato-kosaka** [comment]
@Takapy1 
そうなんだ、
それって安いのに変えれば月1500円くらいで済む？
来月見てみて高かったら、一旦tagごとやめるでもええけどなぁ

**Comment by Ayato-kosaka** [comment]
調べても全然明細が書いてなくてよくわからんのよな

**Comment by Ayato-kosaka** [comment]
とりあえず、gcp では確実に明細見れなさそう

**Comment by Takapy1** [comment]
@Ayato-kosaka 
Elasticsearchの現段階の支払い金額は
Elastic Cloudの右上の自分のアイコンClick->billingから確認可能

Total hourly rate→１時間ごとの料金
Month-to-date usage→現段階の支払い料金（１日スタート）

12/1 にまだ高いの気づかなかったから現時点で少し高くなっている
おそらく今月はこのまま設定変更しない場合、4500円くらいになると思う！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
オッケーありがとう！
