### ISSUE TITLE
フロントのenvをreleaseにする

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#385]

**Comment by Ayato-kosaka** [comment]
@Takapy1 
よく考えたら、今の環境変数の管理方法（ENV.ts で管理）だと、デプロイしたらdevelopmentの環境変数までデプロイされちゃうことに気づいた。(完全にセキュリティ事故案件だったわ、、、)

だから、ENV.ts の中でprocess.env.NODE_ENVIRONMENTで環境変数出し分ける方法はやめて、
それぞれの環境でENV.tsを使い分けるようにした


後、ELASTIC_CLOUD_IDは今回使わないから省いた

https://github.com/Ayato-kosaka/spelieve-secret/commit/7acf4472ef097ef4f07477758dc7b14650872ca3
security に関わる部分だし、念の為クロスチェックお願い！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
developmentの環境変数までデプロイされると悪用される？

**Comment by Ayato-kosaka** [comment]
@Takapy1 
develop は、APIバレない前提だと、例えばGCPのAPI全部許可したりできるの！

コミットの修正で凡ミスしてないからかるーく目視で確認してくれたら大丈夫！
