### ISSUE TITLE
Placeのstyleを追加する

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#386]
# style めも
### BottomTab 
したのBar色変更
```
<BottomTab.Navigator initialRouteName="Itinerary" barStyle={{ backgroundColor: theme.colors.primary }}>
```

### 横幅を相対化したい
子コンポーネントに`flex: x`をつける

### 正方形を作りたい([参考](https://kouhekikyozou.com/css_square))
`paddingTop` に `width`で設定した%を付与する
#### 例
```
paddingTop: '100%',
width: '100%',
```

## 参考
[zIndexはAndroidで使用できないらしい](https://stackoverflow.com/questions/47540932/how-zindex-work-in-react-native)

**Comment by Ayato-kosaka** [comment]
@Takapy1 
デザインは Instagram を参考にしてほしい！
下のbarはI白黒にしてほしい！
というか、全体的に白黒でOKだと思うよ！

**Comment by Ayato-kosaka** [comment]
PPA001 のヘッダーは非表示にしてほしい
PPA002 のヘッダーは場所の名前が出てほしい

**Comment by Ayato-kosaka** [comment]
マップのheightは全体の5/1くらいで良さそう

![Image](https://user-images.githubusercontent.com/53715839/206866953-e40f8c8e-67ad-4633-b363-9b1eaba50eff.png)


ちなにみ、画面サイズから相対的に値を指定するのはこれを参考にすると良いよ！
https://github.com/Ayato-kosaka/spelieve/commit/ffda1c41e974070fe6bd3b8a8c351c111754f462
```
heigt: WINDOW.height/5
```

**Comment by Ayato-kosaka** [comment]
@Takapy1 
できれば、今リリースしてる Spelieve みたいに、PCで横幅狭くしてほしい！

**Comment by Ayato-kosaka** [comment]
### 課題１
Pageからどう、相対的に設定するか不明

**Comment by Takapy1** [comment]
placeNameのpadding修正

**Comment by Ayato-kosaka** [comment]
@Takapy1 
PPA001
placeName のテキストにレスポンシブルなパディングを付けたい

**Comment by Ayato-kosaka** [comment]
@Takapy1 
react native paper には、デフォルトカラーついてるみたい！
テキストボックスフォーカスインしたらオレンジになる！

![Image](https://user-images.githubusercontent.com/53715839/208000430-4ef1dfb4-0f2f-417b-9379-241c9627fc0d.png)

**Comment by Ayato-kosaka** [comment]
react-navigation 関係のテーマ配色は巻き取ります

**Comment by Ayato-kosaka** [comment]
@Takapy1 
これって、ローカルブランチ切ってたよね？
途中でも良いからマージリクエスト作っておいてくれない？
後何が残ってるかとか整理したいから

**Comment by Takapy1** [comment]
@Ayato-kosaka 
切ってる！すぐやるわ

**Comment by Takapy1** [comment]
https://github.com/Ayato-kosaka/spelieve/pull/423

**Comment by Ayato-kosaka** [comment]
@Takapy1 
PPA002 の style 巻き取ります！
Google Map の style は別途教えて〜
