### ISSUE TITLE
authenticate error発生

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#403]

**Comment by Takapy1** [comment]
$ eas credentialsで証明書作成や$ eas build:configureをすると以下のエラーが発生する
```
Authentication with Apple Developer Portal failed!
    Error: You have no team associated with your Apple account, cannot proceed.
    (Do you have a paid Apple Developer account?)
```

**Comment by Takapy1** [comment]
@Ayato-kosaka 
デプロイの現状として上記のエラーが出ている
俺のAppleアカウントがチームとして認識されてないらしい
調べてみたら以下の文公式記事が小さくあった
***
Apple Developer Program に**個人**として登録した場合、他のユーザに App Store Connect のコンテンツへのアクセス権を付与できますが、この**追加ユーザは App Store Connect のアクセス権のみが付与され、Apple Developer Program の参加チームのメンバーとはみなされない**ため、他のメンバーシップリソースや特典は利用できません。

Apple Developer Program に組織として登録した場合、チームに追加できるメンバーの数に制限はなく、またすべてのユーザが、App Store Connect やその他すべてのメンバーシップリソースとメンバーシップ特典を利用できます。

[ユーザアカウントと役割の概要](https://help.apple.com/app-store-connect/#/devad498718e)から抜粋

***
アプリの登録がメンバーシップリソースに含まれるのかまだわからないから、現在調査中

**Comment by Ayato-kosaka** [comment]
@Takapy1 
野口のアカウントで無理なら、俺のアカウントでトークン発行してそれ使ってデプロイとか出来るのかな

**Comment by Ayato-kosaka** [comment]
@Takapy1 

俺のApple ID とExpo を紐づけて、Expo の Token を取得したらできそうな気がするなぁ。
https://zenn.dev/hal1986/articles/20211225-eas-build-and-submit#github-actions%E3%81%AE%E8%A8%AD%E5%AE%9A%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E8%BF%BD%E5%8A%A0

それで問題なかったら俺のAppleID と Expo 紐づけてトークン取得するから、やり方教えて〜

**Comment by Takapy1** [comment]
上記の続き
[App developerとかのメンバーシップリソース](https://developer.apple.com/jp/support/compare-memberships/)
これはApp StoreでのApp配信ふくまれてそうだ
