### ISSUE TITLE
iOS 本番環境デプロイ

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#424]
ゴール：審査してもらえるまで

# 手順まとめ

## 準備
- [x] Developer登録
- [x] eas-cliとかのinstall

## 1. アプリのビルド
1. - [x] eas buildを実行(binaryファイルの作成)
2. - [x] eas.json をsubmit部分を修正([参考](https://docs.expo.dev/submit/eas-json/))
3. - [x] App Store Connect API Key 生成、設定

## EAS→App Store Connect(ASC)へ提出
  - [ ] appleId, appleTeamId, EXPO_APPLE_PASSWORDがapp.jsonに設定されている
  - [ ] どのbinaryファイルを提出するのか(submitコマンド時に --latestすればskipされる)
5. - [ ] `$ eas submit --platform ios`の実行  

⚠️EASはASCへの提出を簡単にできるだけ！最終的な提出はASCの画面で行う

### iOS App 画面
- [x] スクショとかを撮ってupload(審査の時に使用)
- [x] プロモーション用説明
- [x] 概要(**必須**)
- [x] キーワード(**必須**): 検索時にヒットさせるため
- [x] サポートURL(**必須**): 開発者への連絡のために必要（お問い合わせフォーム的な）
- [x] 著作権設定(**必須**)
- [ ] ビルド(**必須**):　ここにビルドファイルupload

[上記項目の意味参考](https://www.bravesoft.co.jp/blog/archives/4838)

### [一般] App情報
- [x] アプリ名(**必須**)
- [x] サブタイトル(アプリのキャッチコピー)
- [x] コンテンツ配信権(**必須**)
（外部API使用しているので、最初の質問は**はい**([参考](https://kinsentansa.blogspot.com/2016/03/ios-20163.html)))
- [x] アプリの対象年齢(質問にいくつか答えるだke)
- [x] カテゴリー

### [一般] 価格および配信状況
- [x] 価格はFreeにした

### [一般] Appのプライバシー
- [ ] 

## CI使う場合
- eas.jsonに必要な情報の記述
- 環境変数

## 参考
- [[JP]公開までの流れ、App Store Connectなどの設定項目](https://zenn.dev/moutend/articles/feebf0120dce6e6426fa#%E3%81%AF%E3%81%98%E3%82%81%E3%81%AB)
- [App Store Connectの設定項目、流れ、わかりやすい](https://www.create-forever.games/unity-ios-app-store-ipa5/)

**Comment by Takapy1** [comment]
@Ayato-kosaka 
IOSデプロイのために開発者への連絡手段の登録として
**サポートURL**の項目がある
今回は適当にテスト提出で簡単に設置したいだけだから
- [Github Page](https://pengi-n.co.jp/blog/git-githubpages/)とかなら簡単に作れそう
- 今のWebのデプロイの方に設置
が考えられるかなと思うけど、どうかな?

**Comment by Ayato-kosaka** [comment]
サポートURLって問い合わせってことやんな？

今リリースしてるSpelieve にあるよ！
@Takapy1

**Comment by Takapy1** [comment]
@Ayato-kosaka 
 さんきゅ
