### ISSUE TITLE
PCO002GooglePlacesAutocomplete を改修する

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#454]
## onAutocompleteClicked で value をクリアする

**Comment by Takapy1** [comment]
@Ayato-kosaka 
このバグの内容忘れてしまったのだが、どういう挙動が問題だったか覚えてる？

**Comment by Ayato-kosaka** [comment]
@Takapy1 
まじでごめん、昨日これ、課題起票されてるって知らなくて直しちゃったわ、、
オートコンプリートクリックされてるのに検索欄の値が消えずに結果も出たままになってたから、setStateで初期化した

**Comment by Takapy1** [comment]
@Ayato-kosaka 
おけおけ、ちゃんと初期化されててやることなくて笑った

**Comment by Takapy1** [comment]
サンクス！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
間違えて対応しちゃったから、担当者変えておきます〜
