### ISSUE TITLE
style が作れたらスクリーンショットを取り直す

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#473]
ユーザに見える場所の写真

- - LP
- しおり作成画面、
- プレビュー

- Place一覧
- PlaceOne

**Comment by Ayato-kosaka** [comment]
プレビュー

![Image](https://user-images.githubusercontent.com/53715839/210790818-6919d919-4fe7-4c94-9be4-0a8b7618cd6f.png)

しおり作成画面


![Image](https://user-images.githubusercontent.com/53715839/210800211-c744e3c8-03b0-4e4d-9082-205c2966d942.png)

@Takapy1

**Comment by Ayato-kosaka** [comment]
LP

![Image](https://user-images.githubusercontent.com/53715839/210802444-e38a0090-5c08-42c2-bd90-4da69d44352f.png)

**Comment by Ayato-kosaka** [comment]
![Image](https://user-images.githubusercontent.com/53715839/210803251-2f14d143-ad11-4191-bb1d-e1fa92c80ea4.png)

**Comment by Ayato-kosaka** [comment]
![Image](https://user-images.githubusercontent.com/53715839/210804184-768a39eb-2d1a-4b2c-b63e-32269376adb3.png)

**Comment by Ayato-kosaka** [comment]
@Takapy1 
↓のサイトで簡単にアプリのストア画像作っておいた〜
https://hotpot.ai/design/ipad-pro-screenshot?id=ydXda2yLZyBZ_2048_2732
https://hotpot.ai/design/app-store-panorama-iphone-12-pro-max?id=WdGGaTCoymg5_6434_2208


![Image](https://user-images.githubusercontent.com/53715839/211035485-903be2c0-0abc-4dd1-921b-22092c203c52.png)

**Comment by Ayato-kosaka** [comment]
@Takapy1 
あと、Apple って審査始まってる？
Apple store connect 見た感じ未だっぽかったから確認お願いします〜

**Comment by Takapy1** [comment]
@Ayato-kosaka 
Expo で失敗してしまってる

**Comment by Ayato-kosaka** [comment]
@Takapy1 
成功してるように見えるけど
![image](https://user-images.githubusercontent.com/53715839/211129936-c68c6b4f-10f4-4ac2-ba4b-e66555a7bb5f.png)

**Comment by Takapy1** [comment]
@Ayato-kosaka 
ASCに出てこないんよねー
あっぷるストアコネクト

**Comment by Takapy1** [comment]
あ、あったわ！！！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
遅くなった、提出しましたー！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
あざすー！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
iOSもbuildnimberを毎回変えるからwikiに入れた

**Comment by Ayato-kosaka** [comment]
ありがとー！

**Comment by Ayato-kosaka** [comment]
![Image](https://user-images.githubusercontent.com/53715839/211320523-32a5a00c-8c56-494b-9817-0e1f9c9a482d.png)

**Comment by Ayato-kosaka** [comment]
https://play.google.com/store/apps/details?id=com.spelieve

**Comment by Ayato-kosaka** [comment]
https://apps.apple.com/jp/app/spelieve/id1660453134
