### ISSUE TITLE
android - should NOT have additional property 'versionName'

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#476]

**Comment by Ayato-kosaka** [comment]
@Takapy1 
`android - should NOT have additional property 'versionName'`
`expo start --dev-clinet` すると、上記エラーが出てきて、下記 app.config のドキュメントにも `versionName` は無いみたいだけど、追加してる理由ってあるの？
https://docs.expo.dev/versions/latest/config/app/

**Comment by Takapy1** [comment]
versionCodeのエラーに引っかかっててその残りだわ
消して問題ない

**Comment by Ayato-kosaka** [comment]
↑　@Takapy1
