### ISSUE TITLE
Android で toLocaleTimeString で second が出る

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#515]
# Bug report
## Describe the bug

https://github.com/Ayato-kosaka/spelieve/blob/a0b6eecfeb55ce963b1d723d0472c3d809b3ef07/src/Common/Components/CCO003DateTimePicker/DateTimePicker.tsx#L37
android では、上記のような js の toLocaleTimeString メソッドを使っている箇所が正常に処理されない

## To Reproduce
1. 新規しおり作成
2. 代表プランのEditPlanに遷移
3. 代表プランの開始時間を修正する

## Environment
 - [ ] Web
 - [ ] iOS
 - [x] Android

## Additional context

----------------------------------------------------------------------
# Solution result
## Roll Out
他機能への影響範囲と対応計画を記載する

ICO001ItineraryPost に3件 toLocaleTimeString を使用しているため確認する
spelieve/src/Itinerary/Components/ICO001ItineraryPost/ItineraryPost.tsx:
  40  												<Text style={styles.planTime}>
  41: 													{plan.placeStartTime.toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit' })}~
  42: 													{plan.placeEndTime.toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit' })}
  43  												</Text>

  53  														<Text>
  54: 															{plan.transportationSpan.toLocaleTimeString(undefined, {
  55  																hour: '2-digit',

**Comment by Takapy1** [comment]
@Ayato-kosaka 
やばい、expo編集した後expoで起動するのどうやってやってたっけ?
`expo start -p android`だともう実行できないよね？

`expo-dev start`みたいな感じだっけ？

**Comment by Ayato-kosaka** [comment]
@Takapy1 
後者だよー

**Comment by Ayato-kosaka** [comment]
もしかして起動しない？

**Comment by Takapy1** [comment]
@Ayato-kosaka 
いや、久しぶりで実行方法忘れてた！
やってみてる

**Comment by Takapy1** [comment]
@Ayato-kosaka 
Webも同じコマンドで実行してweb選べばいけるよね？
ENVファイル更新する以外他に何かやることあるっけ？

**Comment by Takapy1** [comment]
現状だと
`git fetch`して、バグ用のブランチ切って
`npm i`して、`expo start --dev-client`してみてWebで一旦開くと以下のエラーになっている状態


```
nativeModule.js:227 Uncaught Error: You attempted to use a firebase module that's not installed on your Android project by calling firebase.app().

Ensure you have:

1) imported the 'io.invertase.firebase.app.ReactNativeFirebaseAppPackage' module in your 'MainApplication.java' file.

2) Added the 'new ReactNativeFirebaseAppPackage()' line inside of the RN 'getPackages()' method list.
```

**Comment by Ayato-kosaka** [comment]
@Takapy1 
Web は expo web やねんけど、
バグってて治したから、develop からプルすれば起動するはずー

**Comment by Takapy1** [comment]
@Ayato-kosaka 
このandroidのバグは`expo start --dev-client`してみてandroidエミュレータで開いたら、ターミナルにエラーが出る感じかな？

**Comment by Ayato-kosaka** [comment]
@Takapy1 
Androidもバグ出てるの？
To reproduce ってどれのこと？

**Comment by Takapy1** [comment]
@Ayato-kosaka 
andorid自体でエラーは出てない！
To reproduceは一番上のコメントの「バグの起こし方」箇所のこと

このバグレポートのバグの起こし方が理解できていない状況
androidで起動して、代表プランの開始時間を修正すると秒の部分が出てきてしまっている
という認識で問題なし？

**Comment by Ayato-kosaka** [comment]
@Takapy1 
あー、このチケットのバグのことか、ごめんごめん、、

うん、そうだと思う！

普通だったら hour 2桁、minutes 2桁になるように実装してるけど、

秒が出ちゃってるバグだと思う！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
理解した！ありがとう

エミュレーターの起動に時間かかっているけど、対応してみます

**Comment by Takapy1** [comment]
@Ayato-kosaka 
後ごめん、以前こさがまとめてくれたReact nativeのデバッグ環境の資料
簡単に取り出せたら場所教えて欲しいです

**Comment by Ayato-kosaka** [comment]
@Takapy1 

https://github.com/search?q=repo%3AAyato-kosaka%2Fspelieve+%E3%83%87%E3%83%90%E3%83%83%E3%82%B0&type=issues

ここら辺だと思うんだけど、
多分できないんよねー、
いっつもデバッグ使わずにコンソールログにしてる、、

**Comment by Ayato-kosaka** [comment]
expo go だったらできたのかなぁー
使えなくなっちゃったけど笑笑

**Comment by Takapy1** [comment]
@Ayato-kosaka 
androidでexpo start --dev-client`した後に
emulator起動すると思うんだけど、emulatorの中にexpo go のインストールしてれば起動する？

したの画面になって特に動かないのと、
ターミナルには、エラーっぽいのが出るわ
もし原因わかれば教えて欲しいです

<img src="https://github.com/Ayato-kosaka/spelieve/assets/75763679/fc681ea2-cbeb-4c64-ba6f-5b737529eccc" size="70x50">

**Comment by Ayato-kosaka** [comment]
@Takapy1 
--dev-client は eas の機能だから、
Expo go じゃ起動しないよ！

Profile: develop からダウンロードしないといけない！
https://expo.dev/accounts/spelieve/projects/Spelieve/builds/334702de-8845-4bc7-b09a-49f6aff1598f

**Comment by Takapy1** [comment]
@Ayato-kosaka 
送ってくれたURL開いて、installボタン押した時に表示される
最下部のURLをandroid エミュレータ内のブラウザで開いても、installができない。謎だ

**Comment by Ayato-kosaka** [comment]
@Takapy1 
なんでだろ、、

How to install this build on Android
On devices running Android 8.0 (API level 26) and higher, you must navigate to the Install unknown apps system settings screen to enable app installations from a particular location (i.e. the web browser you are downloading the app from).
On devices running Android 7.1.1 (API level 25) and lower, you should enable the Unknown sources system setting, found in Settings > Security on your device.

ここら辺満たしてる？

**Comment by Takapy1** [comment]
@Ayato-kosaka 
ありがとう、端末変更したらできた
ただ、install後にexpo start --dev-clientすると、Spelieveが開かずにandroidのホーム画面に戻る

**Comment by Takapy1** [comment]
これってこさのandroidエミュレータでは、開けるんだよね？

**Comment by Ayato-kosaka** [comment]
試してみるわ

**Comment by Ayato-kosaka** [comment]
@Takapy1 
あかんわ、ダウンロードしてもクラッシュするなぁ、
明日対面で見るわ〜

**Comment by Takapy1** [comment]
@Ayato-kosaka 
了解です。他着手する

**Comment by Takapy1** [comment]
CHK006でdateUtilsをやる・

**Comment by Takapy1** [comment]
関数の実装まで終了
