### ISSUE TITLE
[App Reject内容]　メタデータに問題あり

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#526]
@Ayato-kosaka 
## 1/7 メタデータリジェクト
- [x] description 部分がアプリに関して、詳細情報を含んでいない（engaging app description
）
  - 完全なアプリを求めているから不完全な状態のものを公開できないらしい
- [ ] ??? lorem ipsumをバイナリ、メタデータに含まれないようにする
- [ ] placeholderスクリーンショットがない状態にする

⚠️提出したビルドファイル（アプリ本体）には問題なし
→再提出済み

[作り方参考](https://developer.apple.com/app-store/product-page/)

**Comment by Ayato-kosaka** [comment]
@Takapy1 
話それるけど、apple の metadata って Expo Project で管理できるみたい
https://docs.expo.dev/eas/metadata/config/
