### ISSUE TITLE
Google Analytics 、Firebase Analytics導入する

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#564]
# 動作確認方法
Firebase hostingのspelieve-devの方を使用

- Event追加後、gitHubにpush
- Github ActionのFirebase Hosting PreviewでUse workflow from→作業ブランチ、Deploy environment→releaseにしてRun
- Chromeの場合、[google-analytics-debugger](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en)が入れておく
- release環境のSpelieveのページに行く
  -  ⚠️これはFIrebaseのプロジェクトは[Spelieve prodのHostingページ](https://console.firebase.google.com/u/0/project/itinerary-4aee3/hosting/sites/itinerary-4aee3)のPreview channelsから遷移する
- 動作確認はEventsページかDebug View
  - ⚠️反映されるのはSpelieve-dev
  - ⚠️Eventsページは即時反映されないので、Debug Viewの方がすぐ見れる

# Firebase Analytics導入段階
## 全体手順

- [x] FIrebaseとプロジェクトの紐付け(spelieve-dev) 必要か？
  - [x]   ios
  - [x]   android
  - [x]   Web
- [x] install
- [x] Navigationに導入
- [x] onPressに導入( onPressの改修のため今回はなし）
- [x] 動作確認 Webでは確認済み
- [x] 欲しい指標の決定(今回はページ遷移のみ）

## package選択肢
これまで通りManagedの環境で使うには、expo-firebase-analytics
nativeのコードを触りたい場合は、@react-native-firebase/analyticsを使用。
しかし,[Migrating from Expo Firebase to React Native Firebase](https://github.com/expo/fyi/blob/main/firebase-migration-guide.md)にあるように、非推奨になる予定かつexpo dev client使えば簡単に操作可能であるから、
@react-native-firebase/analyticを使用する
⚠️expo @react-native-firebase/analyticと調べても,expo-firebase-analyticsを使用している記事が多い

```
With EAS Build and development builds, it is much easier to use [React Native Firebase](https://rnfirebase.io/) directly in your entire development workflow, so these expo-firebase-* packages have been deprecated and will be removed in SDK 48.
```
- [expo-firebase-analytics](https://www.npmjs.com/package/expo-firebase-analytics) 
- [@react-native-firebase/analytics](https://www.npmjs.com/package/@react-native-firebase/analytics)

## navigation導入
- [React navigation 公式ドキュメント ](https://reactnavigation.org/docs/screen-tracking/)
- [React navigation Refへの型　公式](https://reactnavigation.org/docs/typescript/#annotating-ref-on-navigationcontainer)
- [firebase 公式ドキュメント](https://rnfirebase.io/analytics/screen-tracking)

## 参考記事
[expo のAnalytics一覧ページ](https://docs.expo.dev/guides/using-analytics/)から[React Naitve Firebaseの導入ページ](https://rnfirebase.io/analytics/usage)参照
- [公式導入](https://rnfirebase.io/analytics/usage)
- [app.confgもの修正](https://rnfirebase.io/#managed-workflow)

# カスタムイベント
ユーザが各画面で何をしたのか（ボタンを押した、）を追跡する
firebase.analytics().logEvent()で作成できる

 # GA4
[参考](https://gmotech.jp/semlabo/seo/blog/google_analytics4/#:~:text=GA4%E3%81%A8%E3%81%AFGoogle%E3%82%A2%E3%83%8A%E3%83%AA%E3%83%86%E3%82%A3%E3%82%AF%E3%82%B9,%E3%82%A2%E3%83%8A%E3%83%AA%E3%83%86%E3%82%A3%E3%82%AF%E3%82%B9%E3%81%A8%E3%81%AA%E3%81%A3%E3%81%A6%E3%81%84%E3%81%BE%E3%81%99%E3%80%82)

**Comment by Ayato-kosaka** [comment]
https://docs.expo.dev/versions/latest/sdk/firebase-analytics/

**Comment by Takapy1** [comment]
各OSにFirebase用の設定ファイルが必要？？？
https://support.google.com/firebase/answer/7015592?hl=ja#zippy=%2C%E3%81%93%E3%81%AE%E8%A8%98%E4%BA%8B%E3%81%AE%E5%86%85%E5%AE%B9

**Comment by Takapy1** [comment]
導入後動作確認したいと気
https://github.com/expo/fyi/blob/main/firebase-migration-guide.mdの
https://rnfirebase.io/#expoによると

configファイルを設置して、app.configにファイルパス、pluginsの記述をするらしい
firebaseとの紐付けは、ENVでやっていると認識していたが、[@react-native-firebase/analytics](https://www.npmjs.com/package/@react-native-firebase/analytics)はNativeのレベルのライブラリだから、
ENVの設定じゃなくて、ローカルにOSごとの設定ファイルが必要なのか？

**Comment by Takapy1** [comment]
@Ayato-kosaka 
spelieve-devのanalytics見るために、れの権限をeditからadminとかに変えてみて欲しいです.
権限でブロックされているページ
https://console.firebase.google.com/u/0/project/spelieve-dev/analytics/app/android:com.spelieve/overview
付与方法
https://support.google.com/firebase/answer/7000272?hl=ja#change&zippy=%2C%E3%81%93%E3%81%AE%E8%A8%98%E4%BA%8B%E3%81%AE%E5%86%85%E5%AE%B9

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ガチ申し訳ない！
更新した！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
早急な対応ありがとう！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ちなみにspelieve-devに繋げてるのって、
開発環境だからだよね？

**Comment by Takapy1** [comment]
@Ayato-kosaka 
そう！
開発環境でfirebaseにのevent logを送れるかをテストしているからspelieve-dev使ってる

**Comment by Takapy1** [comment]
# Debug Viewに関して
普通のRNでは、Xcodeの設定からDebug Viewを可能にする設定ができるが
expoを使用した開発環境の場合、見つからないためWebで確認することにした
[Google Analytics Debugger](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna/related?hl=ja)を導入し、`expo web`してみる

**Comment by Takapy1** [comment]
[event送信　web, nativeで分ける必要性](https://github.com/expo/fyi/blob/main/firebase-migration-guide.md)

**Comment by Takapy1** [comment]
WebでのFirebaseプロジェクトとanalyticsの導入
https://stackoverflow.com/questions/60804074/how-to-get-the-measurementid-from-the-firebase-config
https://stackoverflow.com/questions/61756063/firebase-and-google-analytics-missing-measurementid
settingのページに繋げるボタンがあった

**Comment by Takapy1** [comment]
[おすすめイベント](https://support.google.com/firebase/answer/9267735?visit_id=638119607570994458-2976725652&rd=1)

**Comment by Takapy1** [comment]
@Ayato-kosaka 
AnalyticsをNavigationに導入してWebでの動作確認は完了した。
ios, androidでも動作確認したいんだけで、expo prebuildとかを使って、
xcodeでプロジェクトひらけば、できそうなんだけど、エラー起きてて苦戦中。

```bash
Your git working tree is clean
To revert the changes after this command completes, you can run the following:
  git clean --force && git reset --hard
Error downloading and extracting template package: Error: npm exited with non-zero code: 243
ENOENT: no such file or directory, stat '/private/var/folders/1_/8vzbpz7n3dg22pxnq8q8bpdr0000gn/T/ecbac0a6599c9b18a03f51f22a7580a1/android'
✖ Failed to create the native project.
You may want to delete the `./ios` and/or `./android` directories before trying again.
```

**Comment by Ayato-kosaka** [comment]
@Takapy1 
このエラーログのurl教えてー

**Comment by Takapy1** [comment]
@Ayato-kosaka 
ローカル環境でやってるから、urlない！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
EASってローカルでビルドできるの？
GitHub Action を使ってないってこと？？
使わなくても、ビルド自体はexpo.dev でされるはずじゃなかったっけ

**Comment by Takapy1** [comment]
@Ayato-kosaka 
Prebuildだからまだ、easのビルドは動いてないと思う。


iOSでアナリティクスの動作確認する方法がXcode使う方法しかなさそうで、そうすると今のexpoのreact nativeコードをネイティブのコードに変換してから、Xcodeで開く方法を使う。
このネイティブコードに変換するコマンドがexpo prebuildコマンド

**Comment by Ayato-kosaka** [comment]
@Takapy1 
なるほどねえ
それは、やったことないからどこ起因でエラー出てるかマジでわからんなぁー
