### ISSUE TITLE
【BUG】みなとみらい21 が検索できない

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#595]
# Bug report
## Describe the bug
みなとみらい21 が検索できない

## To Reproduce
1. Go to https://www.spelieve.com/Place/PPA001Places?country=%E6%97%A5%E6%9C%AC&administrativeAreaLevel1=%E7%A5%9E%E5%A5%88%E5%B7%9D%E7%9C%8C&locality=%E6%A8%AA%E6%B5%9C%E5%B8%82
2. Search "日本、神奈川県横浜市中区山下町６１ みなとみらい２１線元町中華街駅"
4. 何も起きない

## Expected behavior
画面遷移する

## Environment
 - [x] Web
 - [x] iOS
 - [x] Android

## Additional context

----------------------------------------------------------------------
# Solution result
## Cause (バグの原因)
地点を表すplace typeが
street_address
premise
establishment
の３つあり、今回の「日本、神奈川県横浜市中区山下町６１ みなとみらい２１線元町中華街駅」はpremiseのplace typeだったため、現状のeestablishmentのみの判定では、**地点**として認識されず、**地名**で認識されてしまったため。

## How to fix (どのようにして解決したか)
地点かどうかの判定でstreet_address、premiseを追加した。

### 他機能への影響範囲
- PPA001PlacesControllerのonAutocompleteClicked
- [GooglePlacesAutocompleteController.ts#L31](https://github.com/Ayato-kosaka/spelieve/blob/f6ba9bdd9287e7b057168ebae49bc46720408af0/src/Place/Components/PCO002GooglePlacesAutocomplete/GooglePlacesAutocompleteController.ts#L31)

###  PPA001PlacesControllerのonAutocompleteClicked
establishment typeは、対応後も残っているので、これまで地点として認識されていたものは、対応後も同様の動作になる
影響を考えるべきはstreet_address, premiseの追加により、**地名だったものが、地点として認識されないか**検証

#### 対応計画
→street_addressは、住所全て入力されない限り、typeに入らないので問題なし
→premiseは、建物で検索しない限り、typeに入ることはないので問題なし
打鍵テストでデグレしてないか確認

 #### 打鍵テスト
| 検索クエリ | 理想動作 | 結果 |
| --- | ---  | --- |
| 横浜市 | 地名 | 地名 | 
| 浦和区 | 地名 | 地名 | 
| 神津島 | 地名 | 地点 |  ←これは理想はどっちだ
| 東京都 | 地名 | 地名 | 
| california | 地名 | 地名 | 
| USA sanfransisco テキサス州 | 地名 | 地名 | 

### 結論と理由
 street_address|premiseにしている
地点のみ（地名は含めない）ようにしたいから
establishmentのみ、geocode含むものは以下記述する理由から要件に合わないため

### geocode含むものの問題
geocode|establishmentだと、EditPlanの方で地名(東京都など）が出てくる
→geocodeに引っかかる
→地点だけで検索できていない 

### establishmentのみの問題
「東京都渋谷区神泉2-5-26-202」などの**住所**打ってもautocompleteでZERO RESULTが戻る
→フル住所で場所として認識されない！
- 出発地点を入れたい時に、自分の住所入れる人いそう
- または「自分の家」打つかも！？
  - Google Mapに登録されているわけではないので、establishmentだともちろん出てこない

## その他調査
- #616

**Comment by Takapy1** [comment]
### PPA001PlacesControllerのonAutocompleteClicked関数は呼ばれている
### onAutocompleteClicked内の以下の記述で地点、地名の分岐をしているが、地名の方が動いている
→isIncludes(sendedDataTypes, addressType)でfalseになっている
```
const isIncludes = (arr: AddressType[], target: AddressType[]) => arr.some((el) => target.includes(el));
		const addressType: AddressType[] = [AddressType.establishment];
		const sendedDataTypes: AddressType[] = data.types;

		if (isIncludes(sendedDataTypes, addressType)) { // 地点
			onPlaceSelected(data.place_id);
		} else { // 地名
                   ...
```
### sendedDataTypesとaddressTypeを出力してみる
  - 確かにaddressTypeの要素がsendedDataTypesにはないため、falseになる
```
sendedDataTypes:  ['premise', 'geocode']
addressType:  ['establishment']
```

### sendedDataTypesに'establishment'はなぜないのか?
本来、地点は以下のようになる
```
// 東京ディズニーランドの例
sendedDataTypes: ['lodging', 'point_of_interest', 'establishment']
 addressType:  ['establishment']
```

**Comment by Ayato-kosaka** [comment]
@Takapy1 
#456 で検討したはずやけど、解決してなかったから、デグレとか起きないか要注意したい。

いろいろ打鍵してみて大丈夫か、確認してほしい！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
デグレって何？

**Comment by Ayato-kosaka** [comment]
@Takapy1 
打鍵テストで、神津島がNGになってるのは、
https://github.com/Ayato-kosaka/spelieve/issues/456#issuecomment-1368714427
↑と同様でしょうがないよねって整理したやつだよね？

**Comment by Ayato-kosaka** [comment]
@Takapy1 

establishment で検索掛けたら、[GooglePlacesAutocompleteController.ts#L31](https://github.com/Ayato-kosaka/spelieve/blob/f6ba9bdd9287e7b057168ebae49bc46720408af0/src/Place/Components/PCO002GooglePlacesAutocomplete/GooglePlacesAutocompleteController.ts#L31)も引っかかったから、同様に修正しなくてよいか確認お願い！
https://github.com/search?q=establishment+user%3AAyato-kosaka&type=code&ref=advsearch

**Comment by Takapy1** [comment]
> @Takapy1 
> 
> 打鍵テストで、神津島がNGになってるのは、
> 
> https://github.com/Ayato-kosaka/spelieve/issues/456#issuecomment-1368714427
> 
> ↑と同様でしょうがないよねって整理したやつだよね？
> 
> 
@Ayato-kosaka 
そう！これはしょうがないやつ

**Comment by Takapy1** [comment]
@Ayato-kosaka 
承知した。明後日確認する

**Comment by Takapy1** [comment]
> establishment で検索掛けたら、[GooglePlacesAutocompleteController.ts#L31](https://github.com/Ayato-kosaka/spelieve/blob/f6ba9bdd9287e7b057168ebae49bc46720408af0/src/Place/Components/PCO002GooglePlacesAutocomplete/GooglePlacesAutocompleteController.ts#L31)も引っかかったから、同様に修正しなくてよいか確認お願い！
について、

PCO002GooglePlacesAutocompleteは
- IPA003EditPlan
- PPA001Places
の２つで使用される想定

PPA001Placesでの使用時は、地点、地域両方で検索可能
IPA003EditPlanは地点のみで検索可能

onChangeInput関数のPlaceHttpPostのtypesは、地点だけで検索とかを指定している場所
方法は,
```javascript
PlaceHttpPost<Omit<PlaceAutocompleteRequest['params'], 'key'>, PlaceAutocompleteResponse>('PBL004', {
	input,
	language: GooglePlaceLanguageTagFromIETFLanguageTag[i18n.locale],
	types: onlySpot ? ('geocode|establishment' as unknown as PlaceAutocompleteType) : undefined,
})
```


## メモ
- PBL004PlaceAutocompleteService: ユーザが入力して、下に候補を出すのが責務
- PBL002UpsertPlaceDataService: autocompleteの候補をユーザが押した時に、データを取得しにいく
