### ISSUE TITLE
【BUG】場所の画像が時間が立つと消えてる可能性あり

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#596]
# Bug report
## Describe the bug
場所画像が非表示になっている

## To Reproduce
1. Go to http://localhost:19006/PPA001Places?country=%E6%97%A5%E6%9C%AC&administrativeAreaLevel1=%E7%A5%9E%E5%A5%88%E5%B7%9D%E7%9C%8C&administrativeAreaLevel2=&locality=%E6%A8%AA%E6%B5%9C%E5%B8%82
2. 画像が表示されない

## Screenshots
![image](https://user-images.githubusercontent.com/53715839/217559693-6320740f-da95-46d7-a607-116e6a030dad.png)

## Environment
 - [x] Web
 - [ ] iOS
 - [ ] Android

## Additional context

画像が永続化されていないのかな、、、
だとしたら大問題から要確認

----------------------------------------------------------------------
# Solution result
## Roll Out
他機能への影響範囲と対応計画を記載する

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ちょっと触ってたら、場所の画像が永続化されてない説が出てきた。
本番環境は影響ないみたいだけど、上記が事実だったら、本番環境に影響出るのも時間の問題だから 2.2 リリースまでに解決したいかも！

**Comment by Takapy1** [comment]
# 調査
- そもそもなぜ全てワールドポーターズなのか?

**Comment by Takapy1** [comment]
@Ayato-kosaka 
なんでワールドポーターズがいくつかあるんだ笑

**Comment by Ayato-kosaka** [comment]
@Takapy1 
Devのデータベースだから、狂ってるだけだと思うよ！
データ全削除して、作り直せば、綺麗になると思うよ

**Comment by Ayato-kosaka** [comment]
4つ目のやつが綺麗なのは今作り直したからかな？
よく分からんな

**Comment by Ayato-kosaka** [comment]
恐らくGoogleから画像が消えたから。
恐らく検知できないから、一旦クローズ
