### ISSUE TITLE
Venture Capital について調べる

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#606]

**Comment by Takapy1** [comment]
## やるべきこと
- ビジネスモデルの見直し
- ビジョンなどの見直し

**Comment by Ayato-kosaka** [comment]
投資家を探す方法はさまざまありますが、Facebookで投資家を探すことは一般的にはあまり効果的ではありません。

Facebookは、主に個人的な交流やコミュニケーションに使用されるため、ビジネスのプロフェッショナルが活動するプラットフォームとしては、LinkedInなどのビジネス特化型のSNSの方が適していると言えます。

投資家を探す場合は、以下のような方法が有効です。

投資家が集まるオンラインプラットフォーム（例えば、AngelListなど）を活用する
投資家が参加するピッチイベントやカンファレンスに参加する
ベンチャーキャピタルやシードファンドなどの投資家を紹介してくれる専門家やアドバイザーに相談する
メールや電話などを活用して、投資家に直接アプローチする
これらの方法を組み合わせて、投資家を探すことができます。ただし、投資家と出会うことは簡単なことではなく、時間と労力が必要であることを忘れずに、焦らずじっくりとアプローチすることが重要です。

**Comment by Ayato-kosaka** [comment]
登録するところまで

**Comment by Takapy1** [comment]
@Ayato-kosaka 
これはメモかな？

**Comment by Ayato-kosaka** [comment]
@Takapy1 
どうやっけ笑
覚えてない笑

**Comment by Takapy1** [comment]
@Ayato-kosaka 
多分そうだと思う！
サンクス
