### ISSUE TITLE
課題の再定義

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#622]

**Comment by Ayato-kosaka** [comment]
@Takapy1 
課題・解決策のパワポ初版作ったのでレビューをお願いします。
投資家から指摘される前にガンガン指摘入れてほしいです！

↓p.2~3
https://docs.google.com/presentation/d/1NWF2jpO0IaeUGWCoiXM9b-yuBc3_zQUC7SRXXiJMfBM/edit#slide=id.g20ec8236305_0_54

↓を参考に作ったからパクリ感出てるからそこも含めて指摘ほしい
https://tumada.medium.com/3-min-pitch-airbnb-203021531522

**Comment by Takapy1** [comment]
@Ayato-kosaka 
おっけー！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
[レビュー中なので無視でOK]

- 「旅程を立てるのは旅行を楽しむ上では必須だ」は別スライドの方がいいのでは？
- 理由：旅程は課題ではなく、手段だから

流れ
旅行は人生で重要な役割
→成功されないといけない
旅行における成功とは、失敗とは、価値を最大化するには？（定義）
成功させるためには「しおりの作成」最も効率的←**ここがさっきの旅程を立てるのは旅行を楽しむ上では必須だの部分**

成功されるには
旅行前の計画立て、旅行中の計画変更、旅行後の思い出化の３段階での工夫が必要

現状の課題(今のP２の内容）
- 計画立てがダルい
- 計画変更した時の扱いが面倒
- 思い出化をするには(クラウドに写真を保存し続けるのが、本当に思い出化なのか？）

解決策(P3の内容）

**Comment by Ayato-kosaka** [comment]
@Takapy1 
パワポ1~4ページで事業価値作りましたので、レビューをお願いします。
話したい要点は、一旦日本語でメモ欄に書いてる〜

**Comment by Takapy1** [comment]
@Ayato-kosaka 
おけー！
