### ISSUE TITLE
長期計画

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#631]

**Comment by Ayato-kosaka** [comment]
直近で旅行系
その後時系列SNSに

顧客数と収益数も盛り込む

**Comment by Takapy1** [comment]
一旦大枠を作ったので確認お願いです。
https://docs.google.com/presentation/d/1NWF2jpO0IaeUGWCoiXM9b-yuBc3_zQUC7SRXXiJMfBM/edit#slide=id.g2108e4edba1_0_128

**Comment by Takapy1** [comment]
@Takapy1 
aaa
