### ISSUE TITLE
ピッチ資料作り(リンクなど)

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#642]
[[EN] ピッチ資料リンク](https://docs.google.com/presentation/d/1NWF2jpO0IaeUGWCoiXM9b-yuBc3_zQUC7SRXXiJMfBM/edit#slide=id.g2108e4edba1_0_128)

**Comment by Ayato-kosaka** [comment]
@Takapy1

**Comment by Takapy1** [comment]
@Ayato-kosaka 
遅くなりました。レビューしたので確認によろしくです！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
修正ありがとう！
```
閲覧側の話はしてないよね。
どう盛り込むかは、別途検討しよう！
```
のやつだけ、修正後にクローズします。
他は問題なかったですー！

**Comment by Ayato-kosaka** [comment]
おけー！ありがとー！
