### ISSUE TITLE
株式による経営権の面で今出資してもらって、問題がないのかの検討

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#650]
## 気になる点
- **求めている出資額が、自分たちの出資額より上回ることあるのか?**
- 出資してもらう=自分たちの発行している株式を買ってもらう
- →俺らの資本金10万で90万出資してもらうとすると、トータル100万
- 株式会社設立の手続きが必要
- →時間かからないか?

株式会社設立して、プロダクト(ソースコードなど)は会社のものになるので、仮に悪いエンジェルに出資してもらい、
事業開始直後に、エンジェルの議決権が上回っているから、プロダクトだけ奪われることにならない？

## 参考記事
- https://coralcap.co/2019/12/seed-finance-02/
- [無議決権株式の説明](https://hgand.co.jp/vol-7%E3%80%80%E5%87%BA%E8%B3%87%E3%81%99%E3%82%8B%E3%81%A8%E3%81%8D%E3%80%81%E3%81%97%E3%81%A6%E3%82%82%E3%82%89%E3%81%86%E3%81%A8%E3%81%8D%E3%81%AE%E7%95%99%E6%84%8F%E7%82%B9/)

**Comment by Ayato-kosaka** [comment]
[16 Things Startups Must Do Beforehand](https://www.upcounsel.com/how-to-get-venture-capital-16-things-startups-must-do-beforehand)

株式企業にしないと行けない気がしてきた。

**Comment by Takapy1** [comment]
@Ayato-kosaka 
だよね

**Comment by Takapy1** [comment]
# 現在の問題
- どの資金調達においても、株式会社の設立が必要
- 計画では、元の会社をやりながら、Spelieveやり収益出てから辞める予定なので、設立は後にしたい


# 考えられる選択肢
- 資金調達を諦め、クラファンで集める
- 株式会社設立して、資金調達をする方針で進める

## 資金調達を諦め、クラファンで集める
### メリット
- 基本的にエンジェルからの出資準備とやることは変わらない
- ニーズがあるのか、お金を使わずに把握できる

### デメリット
- 出資額が少なくなる
- 目標計画、スケジュールの大幅な変更が必要

## 設立の場合
### メリット
- スケジュール、目標計画は変更なし
設立のためのプロセスが必要になるので、2ヶ月で

### デメリット
- 働きながら、設立してバレる可能性→対策方法を考える必要あり
