### ISSUE TITLE
Thumbnail.aspectRatio に index を降る

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#658]

**Comment by Ayato-kosaka** [comment]
@Takapy1 
開発環境の firestore index を本番環境にデプロイ使用としたら、MPlace の所で衝突したんだけど、開発環境と本番環境のどっちが正かの事実確認お願いします〜
```
there are 2 indexes defined in your project that are not present in your firestore indexes file. To delete them, run this command with the --force flag.
```

**Comment by Takapy1** [comment]
developmentブランチとmainブランチってことだよね？
エラーのファイルはMPlaceのどこかわかる？

それかこのエラー分

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ソースじゃなくて、fire store のindexだよ！

MPlaceの検索のために振ったんじゃないの？

**Comment by Takapy1** [comment]
@Ayato-kosaka 
あ、理解した。
見てみるわ

**Comment by Takapy1** [comment]
@Ayato-kosaka 
開発環境indexの中にクエリにlanguageがないものがあったから、修正しました。
一度これで試してみて欲しいです。

**Comment by Ayato-kosaka** [comment]
@Takapy1 

おけー、ありがとう！

後で確認するわ！

次回から、開発環境のindexで本番環境のindexを上書きする作りにするから、本番環境のindex変える時は開発環境も変えるようにお願い！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
おけーです！
ほんま申し訳ない

**Comment by Ayato-kosaka** [comment]
@Takapy1 
デプロイ出来たーありがとー
