### ISSUE TITLE
expo でデプロイできない

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#678]
## Description
EAS の不具合でデプロイができないため、対応方針を検討する

**Comment by Ayato-kosaka** [comment]
@Takapy1 
サブミットは成功したんだけど、Appstoreconnect のビルドに入ってないみたいだから確認をお願い出来ないかな、、

**Comment by Takapy1** [comment]
@Ayato-kosaka 
ビルドの追加対応しました。確認して問題なければ、App Store Connectの右上のボタンから審査に提出できます。
Wikiの提出手順の方に説明は追加済み

**Comment by Ayato-kosaka** [comment]
@Takapy1 
追加作業が必要だったのか！
ありがとう！！
review submision した！
