### ISSUE TITLE
クラファン投稿文章検討

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#683]
- [ ] 投稿文章HTML化
- [x] 目標金額設定
- [ ]

**Comment by Takapy1** [comment]
https://www.indiegogo.com/
INDIEGOGOにこさが登録できる？
Spelieveって名前で登録だめっぽい

**Comment by Ayato-kosaka** [comment]
@Takapy1 
登録したー

**Comment by Takapy1** [comment]
投稿内容

Spelive is an free application that allows you to create, modify, and save travel itinerary easily and efficiently.

Current Spelive is the first stage of our vision - to give everybody, everywhere an amazing tool for free, and We would like to transform Spelieve into a Chronological SNS, not just a travel itinerary.
That's why we need your help.

## What is Chronological SNS
Traditional social networking sites do not allow you to get a deep insight into people's lives, as a special day, a year, or a lifetime cannot be represented in a single post. However, with chronological posting, you can post your life in chronological order and express it as a story. This allows you to express yourself more richly and share it with people around the world. This new social networking service can differentiate your life and change the world. For example, there are many ideas for posting your wedding, travel memories, daily events, seasonal changes, etc. With this new social networking site, you can express your life in a richer way and share it with people all over the world.

![Image](https://user-images.githubusercontent.com/75763679/232774076-7f59d293-975b-4088-a3ec-31d354417f99.png)

## What can you do with Spelieve now?
Creating itinerary easily.
Calculation time automatically.
Create your own thumbnails from the images you have taken in Traveling
(TODO: ほかに機能あれば)

You can download the prototype at…
iOS: https://apps.apple.com/us/app/spelieve/id1660453134
Android: https://play.google.com/store/apps/details?id=com.spelieve

(TODO: 　<Play Store 画像>追加)


![Image](https://user-images.githubusercontent.com/75763679/232774245-c1a1eee8-2dea-413a-846f-9d6ec618695a.png)

## What do we need the money for?
​​The money you invest will be used primarily for marketing and development to improve functionality. The following is a breakdown of the funds.

## Our Team
