### ISSUE TITLE
クラウドファウンディングを実施する

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#688]
# Product Plan

## Business Goal (why)
=== Write the value and benefit for the business of the Product ===
ラウドファウンディングを通じて資金調達を行い、アプリ開発やマーケティング活動の資金を確保することができる。
また、製品への関心を高めることができる。

## Task Goal (what)
=== Determin the goal of the task of the Product ===
クラウドファウンディングのキャンペーンを成功させ、資金調達と広報活動を同時に達成する。

## Child Sprint backlog items
=== Make child issues on Sprint planning ===
- [ ] #XXX

---
**Labels の付け方**  
* マーケティング => 「Promotion」  
* 開発 => サービスに合わせて選択。どれにも属さない場合は、「Sysetem」を選択。

**Comment by Ayato-kosaka** [comment]
@Takapy1 
Ver 2.1 で対応するプロダクトバックログ作成したので、補足あれば追記をお願いします。

**Comment by Takapy1** [comment]
@Ayato-kosaka 
2.2だよね？

**Comment by Ayato-kosaka** [comment]
@Takapy1 
間違えたっ！！
