### ISSUE TITLE
しおりの表紙画像テンプレート投稿システム検討

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#69]
[Google Slide](https://docs.google.com/presentation/d/1dRJEMZM9FvphT8S7BVKGMo2KNnhd0ttXe34cvGVUe8c)
[Google Spreadsheet](https://docs.google.com/spreadsheets/d/107f2L_2REDahiB-T8hWvKK8tHgqPog-_GM_DrS0aWYs/edit#gid=205982254)
### 画像・動画・図形
- [ ] #574
- [ ] #571
- [ ] #579
- [ ] #580
- [ ] #581
- [ ] #582
=> CSSでOK
### テキスト
- [ ] #573
- [ ] #567
- [ ] #568
- [ ] #578
=> CSSでOK
## 共通
- [ ] #569
- [ ] #566
- [x] #570
- [ ] #572
- [x] #575
- [x] #576
- [ ] #577

## 参考 Git
https://github.com/salgum1114/react-design-editor

**Comment by Ayato-kosaka** [comment]
Picsart のテキストエディタ機能を利用する？
https://picsart.io/

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ERDに直結するから、優先的に対応してほしい！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
## [canva](https://www.canva.com/developers/)
### メリット
- 導入方法とか未確認
### デメリット
- **Web**だけで画像を編集したりすること

## [Pixo](https://pixoeditor.com/)
### メリット
- 画像編集のテンプレートがアプリに導入できそう
- web, mobileアプリにも導入できそう,
- 導入楽
### デメリット
導入が本当に楽なのかはまだ未確認なので、document読む必要あり

## [photo-editor](https://github.com/prscX/react-native-photo-editor)
### メリット
- APIではなく、packageとしてテンプレート化機能ができる
- React-nativeから使用可能
### デメリット
- Instagramのような多機能ではない

その他
[PhotoKit](https://developer.apple.com/documentation/photokit)：iOSとかのみ対応(Apple公式)
[Photoeditor](https://github.com/burhanrashid52/PhotoEditor)：Android(Java, kotolinのみ)

**Comment by Takapy1** [comment]
調べ方
- Photo Editor SDK react native

APIというよりSDKだからこのような調べ方をした

**Comment by Takapy1** [comment]
[Photo-editor SDK](https://img.ly/photo-sdk?utm_campaign=Projects&utm_source=Medium&utm_medium=Side_Projects&utm_content=React-Native-Demo&utm_term=Tutorial_Blog_Post) with React native

[導入方法の例](https://medium.com/imgly/photoeditor-sdk-react-native-15179c589a55)

**Comment by Ayato-kosaka** [comment]
@Takapy1 
https://github.com/Ayato-kosaka/spelieve/issues/69#issuecomment-1229399951
おお、インスタのやつまさにこれじゃん！
文字フォント、色、サイズ、配置のテンプレート作れるか？とか
文字列をアプリ側から渡せるか、作った画像をアプリ側に返せるか。とかわかる？

**Comment by Ayato-kosaka** [comment]
処理の流れ

1. ユーザーが画像選択をクリック
2. 画像を選択する
3. エフェクトを選ぶ（これは要らないかな）
4. **テンプレートを選択して文字が自動で配置される**
5. 微調整する


この流れで行くと、ERD的には、imageURLさえ持てば問題なさそう。
※一度画像を編集し終われば画像化されるので、文字の微調整とかは2. からやり直しの想定

**Comment by Ayato-kosaka** [comment]
いや、↑の考慮だと
画像を作る→title を変更する
で、表紙画像とtitleに乖離が起きる。
だから、↓のどれかになりそう

- title を修正したら画像も修正される（そんなの可能なのか）
- titleを画像編集画面でしか編集できないようにする（titleはDBには持ちたいから、SDKから返す必要がある）
- title を編集したら画像が初期化される（これはこだわってる人からすると相当痛い）

**Comment by Ayato-kosaka** [comment]
Instagram のフィルターは、[meta spark](https://sparkar.facebook.com/ar-studio/learn/tutorials/)っていうのを使っ値ているみたい。
meta spark に入っているフィルターをAPI経由で使えるようにしたいけど、調べてみ感じ無理っぽい

**Comment by Ayato-kosaka** [comment]
Image Effect と言っても、詳細に明るさとか調整する系のフィルターは導入したくない。

要件
フレーム？的なのを入れる
![image](https://user-images.githubusercontent.com/53715839/206861882-bbe4fb30-c21a-4661-9708-dec24cd297a7.png)

ぼかす
![image](https://user-images.githubusercontent.com/53715839/206861907-613e2c85-7e1c-41b2-bda6-3207fa37a27e.png)

**Comment by Ayato-kosaka** [comment]
https://pqina.nl/pintura/?affiliate_id=343520371&ref=madewithreactjs.com
これ超強いけど、$179 / yearはさすがにやばい

**Comment by Ayato-kosaka** [comment]
[8 Best Free and Open-Source JavaScript Image Editors](https://code.tutsplus.com/articles/best-free-and-open-source-javascript-image-editors--cms-39897)

**Comment by Ayato-kosaka** [comment]
promero がサムネテンプレートで最適
https://jp.cyberlink.com/products/promeo-post-designer-promotional-video-editing-app/features_ja_JP.html

**Comment by Ayato-kosaka** [comment]
~01/14検討分 bk

[Google Slide](https://docs.google.com/presentation/d/1dRJEMZM9FvphT8S7BVKGMo2KNnhd0ttXe34cvGVUe8c)
## image editor
https://github.com/prscX/react-native-photo-editor
or
https://www.npmjs.com/package/@baronha/react-native-photo-editor

## Image Effect
※検討中
[Pintura Image Editor](https://pqina.nl/pintura/?affiliate_id=343520371&ref=madewithreactjs.com)
→機能が超豊富
→$179 / year
要検討
テンプレートか出来るかは未確認

[img.ly](https://img.ly/pricing/configure-your-product)
→line挿入できないから微妙
年60万（無理）

→とりあえず、Ver2.1 では、photo frame のみにする

### photo frame
https://pqina.nl/pintura/docs/v8/installation/react-native/
![image](https://user-images.githubusercontent.com/53715839/206861882-bbe4fb30-c21a-4661-9708-dec24cd297a7.png)

### ~~エフェクト・モザイク~~
今回は不要とする
![image](https://user-images.githubusercontent.com/53715839/206861907-613e2c85-7e1c-41b2-bda6-3207fa37a27e.png)


## Text Effect
※検討中
https://reactnativeexample.com/react-native-drag-text-editor-for-photo-editing-manipulation-cases/
↑、縁入文字入れられないか

**超こだわって多様化したい！**

**Comment by Ayato-kosaka** [comment]
https://github.com/software-mansion/react-native-gesture-handler/blob/main/example/src/App.tsx
