### ISSUE TITLE
【BUG】経路自動計算が適切にされない

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#692]
# Bug report
## Describe the bug
経路計算が明らかに誤っている

## To Reproduce
1. Go to https://www.spelieve.com/Itinerary/TopTab/ItineraryEdit?itineraryID=L3lL5IjACrEZ1Dix9gJC

## Expected behavior
じどりや穏座と白鬚神社の間の経路が30分程度になるはず

## Screenshots
![image](https://user-images.githubusercontent.com/53715839/232322848-39f192d8-2e5d-4f2b-8a87-c5a63e29cc66.png)

## Environment
 - [x] Web
 - [ ] iOS
 - [ ] Android

## Additional context

経路自動計算系怪しいから見直したい
例えば、経過時間変更で再計算されない

----------------------------------------------------------------------
# Solution result
## Roll Out
他機能への影響範囲と対応計画を記載する

**TODO**
モンキーテストで経路自動計算系の不具合は全て洗い出す

**Comment by Takapy1** [comment]
レビュー提出期限: 6/16中

**Comment by Takapy1** [comment]
@Ayato-kosaka 
このバグもう一度新しいしおりで自動車選択してやると、
24分くらいになって再現できないんだけどどうしよう

**Comment by Ayato-kosaka** [comment]
### 前準備
1. 浮御堂
2. じどりやおんざ
3. 白鬚神社

の順で予定作成
↓
じどりやおんざを代表プランにする
↓
移動方法を自動車にする

### 代表プランの開始時間を変更する or 代表プランの滞在時間を変更する
→自動計算されない
[Spelieve-旅のしおり簡単作成アプリ-.webm](https://github.com/Ayato-kosaka/spelieve/assets/53715839/670a8090-f7d9-4b99-a6c1-ac7ce9585846)

**Comment by Ayato-kosaka** [comment]
↑ @Takapy1

**Comment by Takapy1** [comment]
@Ayato-kosaka 
ありがとう！！！やってみる

**Comment by Takapy1** [comment]
@Ayato-kosaka 
あれ、上手くいく
他に見つけたバグがあって、これと同じ原因な気がするんだけど
https://github.com/Ayato-kosaka/spelieve/issues/828

**Comment by Ayato-kosaka** [comment]
@Takapy1 
上手く行くの？（笑）
なんでだろ、

>他に見つけたバグがあって、これと同じ原因な気がするんだけど
https://github.com/Ayato-kosaka/spelieve/issues/828

読んだけどそれと一緒っぽい！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
２つとも同じ原因の可能性高そう

動画も見たけど、やっぱり代表プランの滞在時間や開始時間の変更が
他のプランに反映されてなさそうやね！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
おっけい！
モンキーテストも行ったけど、問題なかった！！
