### ISSUE TITLE
キャンペーンタイトル、目標金額決める

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#695]
きめるべきこと
https://blog.btrax.com/jp/cf-6/

**Comment by Takapy1** [comment]
@Ayato-kosaka 
目標金額を決めたい

**Comment by Ayato-kosaka** [comment]
@Takapy1 
![image](https://user-images.githubusercontent.com/53715839/233223422-329f98a7-0f79-40e9-b0f4-c08158547193.png)

ココらへんは欲しいかも（クラファンって広告費にお金出すと言うより開発費にお金出す人が多そう←個人的な感想）
60K$ くらいかな〜と思いつつ、、

でも、クラファンで800万円とか現実的じゃないよね
もう少し見積もり精緻化して低く概算させるかとかやなぁ〜
