### ISSUE TITLE
クラファン動画作成

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#696]
期限：4/22までに初版⭕️
期限：4/30 午前に完成
残課題
- [x] ロゴの修正
- [ ] 日本語のしおりの画像が出ているので、英語版の計画を作成し、写真載せる

[編集場所](https://animoto.com/play/wV0o12fu3Ri4EfZ9GVJLsQ)

## 動画構成
- アプリの概要：アプリアイコンタップ Lets Start的な
- 現在の状態は旅アプリです
- LP開く
- 使い方
- その他の機能簡単に紹介: 今紹介した

**Comment by Takapy1** [comment]
## 使用ツール
[Animoto](https://animoto.com/builder/qTAr6WgLcpkI4fY4ovRBXw)
⚠️ログイン情報はシークレット参照

**Comment by Takapy1** [comment]
@Takapy1

**Comment by Ayato-kosaka** [comment]
@Takapy1 ほい！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
大丈夫でした

**Comment by Takapy1** [comment]
@Ayato-kosaka 
ドライブに自動作成した動画設置した
自分で編集するの面倒なのと、音声入れるのとかメインの欲しい機能がupgradeしないと使えないから
画像uploadするだけで自動作成してくれるものを使ってる。

**Comment by Ayato-kosaka** [comment]
@Takapy1 

**ロゴについて**
ロゴって、
https://drive.google.com/drive/folders/1kqSecP8YqWR5c4VWXBk--ayv42A-owOU
のフォルダで正式なものを管理してて、

今回の動画に使っている、square icon は、
正式なロゴを アプリのアイコンに適用するために、臨時で無理やり正方形に変換してるから
違和感満載なのよね。
だから、
https://drive.google.com/file/d/1shc6mG3pizD3WdbOexhPrSMZFzg5Hh7k/view?usp=share_link
を使いたい！


**アプリ内画像について**
出雲大社のお散歩旅について（ごめん、これ俺送ったやつだね）とか、
Place の画像とか、
日本語だから違和感満載だね。
もし簡単に変えれるなら、琵琶湖の方に変えたいかも

**Comment by Takapy1** [comment]
@Ayato-kosaka 
動画を修正したので確認お願いします。
[動画保存場所](https://drive.google.com/file/d/1wtKVqEez4mJwxQ3xozcIACqISXMspgy3/view?usp=share_link)

**Comment by Ayato-kosaka** [comment]
@Takapy1 
おけーい
中身確認した！

**Comment by Takapy1** [comment]
ありがとう😊
