### ISSUE TITLE
Admob API

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#698]
ゴール Admobから売上データなど取得しスプレッドシートに出力
期限　4/23(Sun)

[まとめドキュメント場所](https://docs.google.com/document/d/1Eksot-bdur0ySjcYQMhSD22Q0s4IeEjak69Fbq2kz7Q/edit#heading=h.30td6exki96b)

***

[公式Admob API](https://developers.google.com/admob/api/v1/getting-started)

[エラーになった記事](https://qiita.com/yo1106/items/6c9167f84b49253f8a29)

CLIENT_IDはApp　ScriptのScript Propertiesに入れる

**Comment by Takapy1** [comment]
## 手順
- GCPでAdmob APIを有効化
-

**Comment by Takapy1** [comment]
わからないこと
- GASとGCPの連携が必要？
- OauthのクライアントIDが必要？
-

**Comment by Ayato-kosaka** [comment]
API token じゃなくて　OAuth で認証するのかな、、
結構だるそうだね

**Comment by Takapy1** [comment]
@Ayato-kosaka 
上に貼ってるエラーになった記事が古くて、今はAdmob APIをしないといけないから
OAuth認証が必要になったっぽい

結構だるそうだし、俺まだ理解で来てないから一旦後回しにして、
俺が毎日売上確認して日報LINEに流すわ

**Comment by Ayato-kosaka** [comment]
了解した！
