### ISSUE TITLE
クラファン投稿内容磨き上げ

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#699]
[[EN] クラファン投稿文章](https://docs.google.com/document/d/1Eb1cWZJkUQJEjLijFylL8KlkrcGbCKkE1EH5jPoUyxg/edit#heading=h.pl5nrwghcmfx)

[時系列説明画像作成場所](https://docs.google.com/presentation/d/1DhU2BqD1uWWzCra2cx6MAFCvW66x1Yiy-WUJ_3N9QSQ/edit#slide=id.g21ea3d0fd09_0_8)

**Comment by Takapy1** [comment]
@Ayato-kosaka 
クラファン文章のレビューお願いします。

**Comment by Ayato-kosaka** [comment]
@Takapy1 
レビューしましたので、ご確認をお願いします！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
ありがとう！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
指摘事項修正しました。
Campaign Tagline *, Campaign Card Image *, Tagsが何かわからないから、[INDIEGOGO](https://www.indiegogo.com/)で確認してもらいたい

**Comment by Ayato-kosaka** [comment]
@Takapy1 

↓らしい〜

---

Campaign Tagline *
Provide a short description that best describes your campaign to your audience.

---

Campaign Card Image *
Upload a square image that represents your campaign. 
640 x 640 recommended resolution, 220 x 220 minimum resolution.

これはサムネイルのことかな


---

Tags *
Enter up to five keywords that best describe your campaign. These tags will help with organization and discoverability.

**Comment by Takapy1** [comment]
@Ayato-kosaka 
確認ありがとう

**Comment by Ayato-kosaka** [comment]
@Takapy1 
レビュー2回目実施しましたので確認をお願いします！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
画像内部の英語かのために
App Storeの最初の端末にSpelieveのしおり作成画面が表示されている画像はどうやって作ったんだっけ
ツール覚えてたら教えて欲しい

時系列SNSの説明部分の画像orスライド画像か
未着手

**Comment by Ayato-kosaka** [comment]
@Takapy1 

https://github.com/Ayato-kosaka/spelieve/issues/473#issuecomment-1373728758

これだったと思う！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
ありがとう！

**Comment by Takapy1** [comment]
[画像自動作成](https://www.bing.com/images/create/please-draw-a-picture-of-clean-cream-miniature-dac/6449212d6ddf440d95316197f7e5cec1?FORM=GENCRE)

**Comment by Ayato-kosaka** [comment]
@Takapy1 
そのMicrosoftのやつ試したことないけど、
ガチでAIの画像生成こだわるなら↓がおすすめだと思う〜

https://youtu.be/EiRB_M9_02w

**Comment by Takapy1** [comment]
@Ayato-kosaka 
ありがとう！
まぁMicrosoftもイラスト系の画像作成は割と良かった。
本当の人間は顔が崩れてた😂
