### ISSUE TITLE
チャネル 19 * コスト1 で評価を行う

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#700]

**Comment by Ayato-kosaka** [comment]
@Takapy1 
https://docs.google.com/spreadsheets/d/1lD-fjR-GIuYwKuMCc-lWEf5kR7Vk0XALQ3_s5s8z4FU/edit#gid=0
一旦上4つ施策アイデア調査とチャネルの評価してみたから軽く目を通しておいて〜

**Comment by Takapy1** [comment]
@Ayato-kosaka 
確認した！まだあまり思いつかないけど、少しだけ提案をコメント入れた
内容は理解したから思いついたら適宜追加する

**Comment by Ayato-kosaka** [comment]
ありがとー！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
施策アイデアの追加もありがたいんだけど、
突然レビュー依頼しちゃって、
見て欲しいポイントの擦り合わせが必要かなと思ったから、
次の打ち合わせで会話させて欲しい！

**Comment by Ayato-kosaka** [comment]
トラクションの整理のビジョンは、完全なマーケティング指向開発を確立させることで、
マーケティング指向開発のビジョンは、全てのタスクにおいて優先度付をすることが出来るようになること。
↑かなり整理に苦戦している所。

まずは、トラクション整理で、
このチャネルとこのチャネルの違いが分かりづらいや、
このタスクはどこのチャネルに該当するの？
を明確にして、ビジョンと現実のギャップを洗い出したい。
