### ISSUE TITLE
出資者へのリターンを検討

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#702]
## Description
出資者の出資金額に応じたリターンを何にするか決める
（まずは合計金額に対するチケットをどう切るか検討)

## Solution
メッセージを送る

**Comment by Ayato-kosaka** [comment]
一旦調べるところから
今週中決まるかは少しびみょい

**Comment by Takapy1** [comment]
有効な選択肢が何があるのかを調べる必要がある
Tシャツ？とか

**Comment by Takapy1** [comment]
アプリ内での広告非表示：出資者には、アプリ内での広告を非表示にする権利を提供することができます。

有料機能の解除：アプリ内で有料の機能がある場合、出資者には有料機能の解除を提供することができます。

プレミアムコンテンツの提供：出資者には、アプリ内でのプレミアムコンテンツ（例えば、独占的な動画や音楽など）にアクセスする権利を提供することができます。

特別なアバター、アイコン、エンブレムなど：出資者には、アプリ内で使用できる特別なアバターやアイコン、エンブレムなどを提供することができます。

限定アイテムの提供：出資者には、限定アイテム（例えば、Tシャツ、マグカップ、ステッカーなど）を提供することができます。

ライブイベントへの招待：出資者には、アプリの開発者が主催するライブイベントに招待する権利を提供することができます。

アーリーアクセス：出資者には、アプリの新機能やアップデートにアーリーアクセスする権利を提供することができます。

謝罪メッセージ：プロジェクトが失敗した場合、出資者には謝罪メッセージを送ることができます。また、将来的なプロジェクトに優先的に参加する権利を提供することもできます。

**Comment by Ayato-kosaka** [comment]
メッセージ
