### ISSUE TITLE
#688 Chronological SNS についての詳細説明

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#711]
ゴール：画像作成し、ドキュメントの草案をレビューに出す
期限：4/30 ~12:00

残課題
- [x] 画像を投稿と分かりやすく
- [x] Instaっぽさを画像から無くす

**Comment by Takapy1** [comment]
@Ayato-kosaka 
Tags, Tagline, Chronological SNS についての詳細説明の３点だけ確認して欲しい

残課題
- 動画の写真に日本語のしおり画像になっている→英語版しおりに変更
-

**Comment by Ayato-kosaka** [comment]
@Takapy1 

ありがとう！！
確認した〜

---
Instagram の模型、海画像、温泉画像
は商用利用OKで大丈夫？
![image](https://user-images.githubusercontent.com/53715839/235294964-64a089d3-8941-4ff6-b1f2-76e9fae4c2fe.png)

---
TODO にしている所って今回は対応しない想定でOK？
紫色にしておいたから必要なかったら削除しておいて〜

**Comment by Takapy1** [comment]
@Ayato-kosaka 
海、温泉は俺のとフリーのやつだから問題なし

インスタの模型は確認してない！やばいかも

**Comment by Takapy1** [comment]
TODO確認します

**Comment by Takapy1** [comment]
@Ayato-kosaka 
インスタの模型って
ハートマークとか消しておけば、いいかな?

**Comment by Takapy1** [comment]
@Ayato-kosaka 
TODは一番初期段階でつけていただけで、もう必要ないものだった。

**Comment by Ayato-kosaka** [comment]
@Takapy1 

> インスタの模型って
ハートマークとか消しておけば、いいかな?

それでいいと思う！！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
おけーい！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
投稿完了までにやるべきことが他にないか確かめたいから、
現時点で、素材は集まったと思うから、「投稿する」っていう直前までいけるかINDIEGOGOでお手隙にやってみて欲しい！

[投稿内容や調達金額、出資額の割り振りなど](https://docs.google.com/document/d/1Eb1cWZJkUQJEjLijFylL8KlkrcGbCKkE1EH5jPoUyxg/edit#)

[画像関連](https://drive.google.com/drive/u/0/folders/1BUQ59UBipYR-6_RqdU-wlDb5zp1zl9DM)

よくわからない箇所あれば、その都度連絡して欲しいです。
***

いまからもらったレビューします

**Comment by Ayato-kosaka** [comment]
@Takapy1 

:warning: :warning: :warning: :warning: :warning: :warning: 
ごめん、結構漏れてたかも、、、、 :sweat_drops: 


Campaign Title、Campaign Tagline にコメント入れてるからDOCS確認して〜

---

FAQ
*
The FAQ section should provide the most common details that backers are looking for when evaluating your campaign. We will also provide common answers to questions about crowdfunding and how Indiegogo works.

---

お返し関連結構書くことある
![image](https://user-images.githubusercontent.com/53715839/235333179-90fb1316-2a7c-46dc-971e-d33be3f368e3.png)

---

銀行は俺の口座でいいのかな？

![image](https://user-images.githubusercontent.com/53715839/235333250-45326e92-f170-48ba-ac38-209375677f6b.png)

---

Extra とかあった、、、、

![image](https://user-images.githubusercontent.com/53715839/235333273-13a466c4-478f-4548-be68-1f2cf3433d38.png)

---

In Demand ってなんだろ

![image](https://user-images.githubusercontent.com/53715839/235333302-641440e8-af61-4c81-9d81-087bb41d0e0f.png)

**Comment by Takapy1** [comment]
@Ayato-kosaka 
確認がありがとう、みてみます

**Comment by Takapy1** [comment]
@Ayato-kosaka 
コメント入れてくれたやつが、文字数制限と、使ってる文字種類の問題でコメントできてないから確認できる？
[クラファン投稿資料](https://docs.google.com/document/d/1Eb1cWZJkUQJEjLijFylL8KlkrcGbCKkE1EH5jPoUyxg/edit#)

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ゴメン、コメントしたエラーが出たっていう意味だった.... :bow:

**Comment by Takapy1** [comment]
@Ayato-kosaka 
そういうことか! docsのエラーかと思った笑
確認します。

**Comment by Takapy1** [comment]
@Ayato-kosaka 
投稿のために追加で必要になった項目は、以下のissue切ったので、
問題なさそうなら、このissueクローズして欲しい！
