### ISSUE TITLE
#688 Campaign Card Image を作る

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#713]
目標：最低３枚作成し、こさに提案
期限：4/30

size: Campaign card images: should be square. 
The recommended size is 640x640 px and the minimum size is 220x220 px.

[Canva](https://www.canva.com/)

**Comment by Takapy1** [comment]
メイン画像　
- テクノロジーの進化というイメージを出したい(新しい発想きたーって感じ）
- 
-

**Comment by Takapy1** [comment]
生成AIで画像生成してみようと思って、
こさが教えてくれた方法
でやってみたら現在[midjourneyが無料トライアル停止](https://gigazine.net/news/20230331-midjourney-stop-free-trials/)しているみたいです

**Comment by Ayato-kosaka** [comment]
@Takapy1 
がちか〜〜〜〜〜〜〜〜
App store とかもそれ使いたかったのに〜〜〜

**Comment by Ayato-kosaka** [comment]
@Takapy1 
https://drive.google.com/file/d/1AH7Z_E_GlEHasn8ip3o2feS_0ZkTJ6kW/view?usp=share_link
で コミュニティ構築用にサムネイル作ったけど、それに合わせて Cloud Founding のサムネイルも作ろうか？

（canva 共有しようと思ったら変な招待送っちゃたかもゴメン）

**Comment by Takapy1** [comment]
@Ayato-kosaka 
できればお願いしたい。
作ってみたけど、クオリティが壊滅的
https://drive.google.com/file/d/1KkN76pi839PWDYl3cFa_fmARnG2Cjc79/view?usp=share_link

**Comment by Ayato-kosaka** [comment]
@Takapy1 
こんな感じでどう？
![2](https://user-images.githubusercontent.com/53715839/235333719-5b6c566a-4883-470a-8505-8bbbb9e7e27c.png)

**Comment by Takapy1** [comment]
@Ayato-kosaka 
内容とか配置はいいと思う！
タイトルはもう少し大きい方が、インパクトありそう？

**Comment by Ayato-kosaka** [comment]
@Takapy1 
こんな感じ？
![Spelieve (1)](https://user-images.githubusercontent.com/53715839/235335105-32c44b90-2c7c-470e-8d36-c5a9b93a84b7.png)

**Comment by Takapy1** [comment]
@Ayato-kosaka 
うん、いい感じだと思う！
