### ISSUE TITLE
#686 既存プラットフォームで施策を実施する

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#716]
[Existing Platforms テスト実施](https://docs.google.com/document/d/18oRMo1Qwl6dBR0TYW3eR2SI5y5jMjksfpITpeACkI0k/edit#)
[ASO施策立案](https://docs.google.com/document/d/1t-TwJcodny2MxsnkVi8saJ2dyG-HgwzkzMA2XZN6tRI/edit)

**Comment by Ayato-kosaka** [comment]
@Takapy1 
Existing Platforms も上記2ドキュメントで施策立案までやったから、レビューをお願いします。
ASO施策は若干こだわりたいから濃いめにレビューお願い！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
おけーです

**Comment by Takapy1** [comment]
@Ayato-kosaka 
ASO対策、Existing Platforms のレビュー見ました。
コメント入れてます。

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ありがとう！
対応しました！
TODOのところはタスクチケット切ったら別途対応します :bow:

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ロゴアンケート！！

①将来的にデザイナーに作り変えてもらうことを想定して無難に黒


![Image](https://user-images.githubusercontent.com/53715839/235823058-a6dd8d74-643d-4a28-9d1b-e95722c0a5ad.png)

②アプリ内のカラーと合わせてオレンジ！


![Image](https://user-images.githubusercontent.com/53715839/235823134-46cdc178-d716-4a70-89fa-3d72b4a41b13.png)

③[その他](https://www.remove.bg/upload)


![Image](https://user-images.githubusercontent.com/53715839/235823380-8f23efe1-f41d-4df1-858c-88e8db0d2687.png)



↓参考

![Image](https://user-images.githubusercontent.com/53715839/235822956-0a143ae2-e689-4288-a7a3-153a79bf198e.png)

**Comment by Ayato-kosaka** [comment]
グラデーションも出来るから、色が決まればて機能にグラデーション欠けるわ

![Image](https://user-images.githubusercontent.com/53715839/235824303-58e5e991-77b3-48f9-bbb0-7f8e5a2e002c.png)

**Comment by Ayato-kosaka** [comment]
@Takapy1 
[ASO施策立案](https://docs.google.com/document/d/1t-TwJcodny2MxsnkVi8saJ2dyG-HgwzkzMA2XZN6tRI/edit)
サムネイルの説明文と英語版のスクリーンショット作ったからレビューをお願いします。

**Comment by Takapy1** [comment]
@Ayato-kosaka 
おけーです。
今日パソコン触れないから明日11時までにやるー！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
おけーい
投票は↓からやってくれると助かる〜
https://twitter.com/neighborteacher/status/1653706578300895233

**Comment by Takapy1** [comment]
> @Takapy1 ロゴアンケート！！
> 
> ①将来的にデザイナーに作り変えてもらうことを想定して無難に黒
> 
> ![Image](https://user-images.githubusercontent.com/53715839/235823058-a6dd8d74-643d-4a28-9d1b-e95722c0a5ad.png)
> 
> ②アプリ内のカラーと合わせてオレンジ！
> 
> ![Image](https://user-images.githubusercontent.com/53715839/235823134-46cdc178-d716-4a70-89fa-3d72b4a41b13.png)
> 
> ③[その他](https://www.remove.bg/upload)
> 
> ![Image](https://user-images.githubusercontent.com/53715839/235823380-8f23efe1-f41d-4df1-858c-88e8db0d2687.png)
> 
> ↓参考
> 
> ![Image](https://user-images.githubusercontent.com/53715839/235822956-0a143ae2-e689-4288-a7a3-153a79bf198e.png)

オレンジかなー

**Comment by Takapy1** [comment]
@Ayato-kosaka 
画像はこのままでいいと思った！
サムネイルの説明文は、１つ提案したから確認お願いです！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
この英語版の画像をクラファン

**Comment by Ayato-kosaka** [comment]
オレンジ青で3パターンくらい作ってみる

**Comment by Ayato-kosaka** [comment]
@Takapy1 
青オレンジのパターン何パターンか作ってみたけど、どんな感じが良いとかある？

## 82b1ff
![image](https://user-images.githubusercontent.com/53715839/236658742-9514ca76-99e6-4d7a-8738-dde52fe8ec58.png)

## 448aff
![image](https://user-images.githubusercontent.com/53715839/236658731-a7e663ca-8a33-410d-992e-4711339ab10e.png)

## 2979ff
![image](https://user-images.githubusercontent.com/53715839/236658698-95b4bfa7-8104-4927-9470-d180f73ee849.png)

## 2962ff
![image](https://user-images.githubusercontent.com/53715839/236658682-2ea6ff22-a095-4a9f-a151-ef2de86ec228.png)

## 1558d6
![image](https://user-images.githubusercontent.com/53715839/236658668-6c08ad3c-852d-40b3-8dca-17d57325a5ed.png)

---
![image](https://user-images.githubusercontent.com/53715839/236658655-94e2e972-1f7a-40f2-8794-cae6a42828af.png)

**Comment by Ayato-kosaka** [comment]
2962ff で決定！
