### ISSUE TITLE
#686 コミュニティ構築施策を実施する

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#717]
[コミュニティ構築施策 テスト実施](https://docs.google.com/document/d/11xXVPs8b-EQnwWZGAdZ5NMMEImMJ6_iZVT8jD6PzIaE/edit)

**Comment by Ayato-kosaka** [comment]
@Takapy1 
上記資料でコミュニティ構築戦略練ってみてテスト実施してみたから目を通しておいて！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
明日中に確認します

**Comment by Takapy1** [comment]
@Ayato-kosaka 
facebookはとりあえず俺が入った
