### ISSUE TITLE
#688 お返しの値段と説明文を考える

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#718]

**Comment by Takapy1** [comment]
@Ayato-kosaka 
報酬の値段の割り振りしてみたのレビューお願いします。
https://docs.google.com/spreadsheets/d/1Rb53Q_GjTWz1zuzGsEaS4dFl4UyKNM6260h7BC7znIo/edit#gid=0

緑色にしてるセル（１口あたりの金額とその枚数）を特にみて欲しい

いくつかコメントでなんでその枚数にしたのか書いてある。

**Comment by Ayato-kosaka** [comment]
@Takapy1 
閲覧権限付与お願い！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
これでどうかな？

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ありがとー！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
問題ないと思う〜
