### ISSUE TITLE
SNSシェア検討

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#72]
SNSシェアのライブラリを検討する
InstagramやTwitterで利用されているもの
![image](https://user-images.githubusercontent.com/53715839/181126652-edc3d543-2a3f-4728-951c-8a7560cf9ace.png)

**Comment by Ayato-kosaka** [comment]
react-social-sharebuttons
が有力？

**Comment by Takapy1** [comment]
react-social-sharebuttons以外の選択肢がなかなか見つからない

**Comment by Ayato-kosaka** [comment]
react native の標準に↓がある。webに対応しているかはわからない
https://reactnative.dev/docs/share

**Comment by Ayato-kosaka** [comment]
247 に統合
