### ISSUE TITLE
Perks（リターン）の詳細文章検討

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#720]
## お礼メッセージ種類
金額が上がるとともによりプロジェクトに参加している間を出す
- １回限りの感謝のお礼
- 活動報告（１ヶ月おき）
- 活動報告（１週間おき）
- FaceBookグループへの招待

## その他
- 電話でお礼

[リターン参考記事](https://camp-fire.jp/academy/articles/article-7)

**Comment by Takapy1** [comment]
お返し関連結構書くことある
![image](https://user-images.githubusercontent.com/53715839/235333179-90fb1316-2a7c-46dc-971e-d33be3f368e3.png)

**Comment by Ayato-kosaka** [comment]
![image](https://user-images.githubusercontent.com/53715839/235452932-a3fcab62-b598-443f-b6d4-7ef589498f18.png)

**Comment by Takapy1** [comment]
@Ayato-kosaka 
[クラファンのリターンシート](https://docs.google.com/spreadsheets/d/1Rb53Q_GjTWz1zuzGsEaS4dFl4UyKNM6260h7BC7znIo/edit#gid=0)に
各金額に応じたTitle, description文章の草案作りました。
レビューお願いします！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
大体いい感じだと思うけど、
お返しのところなんだけど、facebook Group って招待しないと入れなくするってこと？

**Comment by Takapy1** [comment]
@Ayato-kosaka 
そういう意図で設定した！

ただ、コミュニティのトラクションでそういう風にしない方針であれば、Facebookグループへの招待はなしで大丈夫！
$20と50が同じリターンになるけど、それは問題ないと思う。

**Comment by Takapy1** [comment]
Facebookへの招待は差別化のために割と強引に設定したから、あくまで1案として検討余地あり

**Comment by Ayato-kosaka** [comment]
@Takapy1 
おけーい
なるほど、方針了解した！

> コミュニティのトラクションでそういう風にしない方針

トラクションでは特に何も考えてないから大丈夫！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
Facebookグループの集客法がよく分からないから、クラファンと連携する的な方法もあるのかなと思った感じです
