### ISSUE TITLE
コミュニティ構築 テスト実施でコミュニティにメンバーが入らないリスク

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#722]
リスクの特定:
Facebook グループでコミュニティ作ってみたけど、全くメンバー入る気がしない
施策を練らないと。。。
地道に少しづつ投稿していくべきなのか？？

リスクの評価:

リスクの軽減:

リスクの監視:

**Comment by Takapy1** [comment]
@Ayato-kosaka 
地道にやる感じだよねおそらく

**Comment by Ayato-kosaka** [comment]
@Takapy1 
そうやんなぁー、なかなか大変やなぁー

**Comment by Ayato-kosaka** [comment]
技術面のサポート募集にも繋がるから、

技術面、マーケティング面など幅広く投稿する
