### ISSUE TITLE
【BUG】サムネイルの画像投稿するとクラッシュ

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#723]
# Bug report
## Describe the bug
サムネイル編集画面で、画像を追加し、左上の❌ボタン押して、保存ボタン押すと、アプリが落ちる

## To Reproduce
1. Go to サムネイル編集画面
2. Click on 右上から画像追加
3. Click on 左上の❌ボタン
4. Click on 保存ボタン
6. クラッシュ

## Environment
 - [ ] Web
 - [x] iOS
 - [ ] Android

## Additional context

----------------------------------------------------------------------
# Solution result
## Roll Out
他機能への影響範囲と対応計画を記載する
サムネイルに限定されているため影響なし

**Comment by Ayato-kosaka** [comment]
@Takapy1 
どのSprintで対応するか計画立てれていないので、Sprint backlog からは消しておきます〜

**Comment by Ayato-kosaka** [comment]
試してみると、何故か直ってる、、

**Comment by Ayato-kosaka** [comment]
@Takapy1 
これ再現するか見て欲しい！
再現しなければクローズしたい！

**Comment by Ayato-kosaka** [comment]
開発環境でも再現した。
[こちら](https://stackoverflow.com/questions/72005800/react-native-upload-image-to-firebase)のエラーが出る
[こちら](https://github.com/firebase/firebase-js-sdk/issues/5848) の解決策に従うと、
firebase/storage から React Native Firebase に変更すべき？

**Comment by Ayato-kosaka** [comment]
[こちら](https://github.com/firebase/firebase-js-sdk/issues/5848#issuecomment-1767426167)の意見によると、画像のResize の問題っぽい

**Comment by Ayato-kosaka** [comment]
*Thumbnail 画像を upload する処理を追ってみる*
TPA001LeaveDialogController#[onSaveClicked](https://github.com/Ayato-kosaka/spelieve/blob/3a17a922c273afec67ea9c22487ba0802a964f38/src/Thumbnail/Pages/TPA001ThumbnailEditor/Controller/LeaveDialogController.ts#L53) で2回呼び出されている

元の画像＋ダミー画像
```
const captureURI = await viewShotRef?.current?.capture?.();
const downloadURL = captureURI && (await CHK005StorageUtils.uploadImageAsync(storage, captureURI));
```

**Comment by Ayato-kosaka** [comment]
![image](https://github.com/Ayato-kosaka/spelieve/assets/53715839/b6c73583-7691-49d9-8918-1b861fa53487)
Figure を追加しまくると固まるけど、performance は至って正常。
原因がよくわからん
