### ISSUE TITLE
【BUG】英語版でPlace 一覧画面で初期表示されない

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#724]
# Bug report
## To Reproduce
1. Go to https://www.spelieve.com/Place/PPA001Places?country=United%20States&administrativeAreaLevel1=New%20York&administrativeAreaLevel2=New%20York%20County&locality=New%20York
2. See error

※英語で起動すること

## Expected behavior

それなりに場所が表示される

## Screenshots
![image](https://github.com/Ayato-kosaka/spelieve/assets/53715839/cdbc5f6d-4a8e-4c3d-b9d2-dfdb8e818631)

## Environment
 - [x] Web
 - [x] iOS
 - [x] Android

## Additional context

----------------------------------------------------------------------
# Solution result
## Roll Out
初期値を投入する機能＋言語分投入が必要なのは、この機能のみ。
言語が追加された場合は、このタスクを実施する必要があるため、PBI #791 に対応要の旨を記載

**Comment by Ayato-kosaka** [comment]
@Takapy1 
実際に対応する時に読んで！

単なるデータの登録漏れだったら、オートコンプリートで適当に登録すれば最低限は入るはず！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
ありがとー！

**Comment by Takapy1** [comment]
期限: ~6/17レビュー提出

**Comment by Takapy1** [comment]
トップ画面の４つの四角の
文字列を中央揃えにしたい

**Comment by Takapy1** [comment]
@Ayato-kosaka 
USA NYがデフォルトなので、それで10個場所作成した！
確認お願いしますー

**Comment by Takapy1** [comment]
@Ayato-kosaka 
NYやで

**Comment by Ayato-kosaka** [comment]
@Takapy1 
実装どこかわかる？

**Comment by Takapy1** [comment]
/src/Place/Hooks/PHK002InitialPlaceParam.tsに
デフォルトの場所設定してる！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
あー、そうだったね！
ありがとう！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
Roll out 記載したから、問題なければクローズしちゃってください！
