### ISSUE TITLE
【BUG】○日目が日本語になっている

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#725]
# Bug report
## Describe the bug

⚪︎日目の翻訳漏れ

## To Reproduce
1. 英語版で開く
1. Itinerary Preview に遷移する
1. 不具合を確認

## Expected behavior

Day 1とかになる

## Screenshots

![image](https://github.com/Ayato-kosaka/spelieve/assets/53715839/98f8bbda-a64d-447d-b921-47807ae195e8)

## Environment
 - [x] Web
 - [x] iOS
 - [x] Android

## Additional context

----------------------------------------------------------------------
# Solution result
## Roll Out
他機能への影響範囲と対応計画を記載する

spelieve-code-analysis# npx ts-node [./src/extractJsxText.ts](https://github.com/Ayato-kosaka/spelieve-code-analysis/blob/master/src/extractJsxText.ts)             
https://github.com/Ayato-kosaka/spelieve/blob/develop/src/Common/Pages/ModalScreen.tsx#L24-L24 Modal
https://github.com/Ayato-kosaka/spelieve/blob/develop/src/Itinerary/Components/ICO001ItineraryPost/ItineraryPost.tsx#L32-L32 日目
https://github.com/Ayato-kosaka/spelieve/blob/develop/src/Itinerary/Components/ICO001ItineraryPost/ItineraryPost.tsx#L41-L42 ~
https://github.com/Ayato-kosaka/spelieve/blob/develop/src/Thumbnail/Pages/TPA001ThumbnailEditor/TextEditDialog/TextEditDialog.tsx#L59-L59 FontFamily: 
https://github.com/Ayato-kosaka/spelieve/blob/develop/src/Place/Contexts/PCT012MPlaceOne/ModelComponents/PMC01201GoogleMapPlaceOne/GoogleMapPlaceOne.web.tsx#L24-L25 ;

**Comment by Ayato-kosaka** [comment]
@Takapy1 
横点で5箇所追加したから、対応する時に i18n に追加お願い〜
eslint に追加したかったけど、難易度高そうだったから一旦諦め。

**Comment by Takapy1** [comment]
@Ayato-kosaka 
了解です
