### ISSUE TITLE
#691 セキュリティルール実装

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#727]
[FirestoreSecurityRules設計方針](https://docs.google.com/document/d/1ouP3YNfxuzzeyiDlWwoyKogo2e1AVKjKiLX561eBWSk/edit)

**Comment by Ayato-kosaka** [comment]
@Takapy1 
[spelieve-firebase](https://github.com/Ayato-kosaka/spelieve-firebase) に招待したからはいって〜

**Comment by Takapy1** [comment]
@Ayato-kosaka 
入ったー

**Comment by Ayato-kosaka** [comment]
@Takapy1 
[FirestoreSecurityRules設計方針](https://docs.google.com/document/d/1ouP3YNfxuzzeyiDlWwoyKogo2e1AVKjKiLX561eBWSk/edit)書き終えたから軽く見て欲しい！
FirestoreSecurityRules は半自動生成することにした〜

--- 

デプロイする前にテストがちゃんとできてるかは確実に抑えたくて、クロスチェックして欲しい！
お願いしたい項目は2項目で

①テスト設計が仕様として問題ないか
↓のテスト項目をテストしたんだけど、これって仕様としてまずってないか確認して欲しい！
```
Itineraries
    ✓ get: 無条件で get 可能 (876 ms)
      at logWarn (../node_modules/@firebase/firestore/src/util/log.ts:69:15)
    ✓ list: 無条件で list 不可能 (132 ms)
    ✓ create: 無条件で create 可能 (79 ms)
    ✓ delete: 無条件で delete 不可能 (73 ms)
    update
      ✓ isImmutable フィールドが true の場合、update 不可能 (397 ms)
      ✓ 上記以外の場合、update 可能 (100 ms)
  PlanGroups
    ✓ get: 無条件で get 可能 (94 ms)
    ✓ list: 無条件で list 可能 ([112](https://github.com/Ayato-kosaka/spelieve-firebase/actions/runs/4879639151/jobs/8706393957?pr=7#step:6:113) ms)
    create
      ✓ Itineraries の isImmutable フィールドが true の場合、create 不可能 (78 ms)
      ✓ 上記以外の場合、create 可能 (90 ms)
    update
      ✓ Itineraries の isImmutable フィールドが true の場合、update 不可能 (77 ms)
      ✓ 上記以外の場合、update 可能 (63 ms)
    delete
      ✓ Itineraries の isImmutable フィールドが true の場合、delete 不可能 (87 ms)
      ✓ 上記以外の場合、delete 可能 (69 ms)
  Plans
    ✓ get: 無条件で get 可能 (90 ms)
    ✓ list: 無条件で list 可能 (57 ms)
    create
      ✓ Itineraries の isImmutable フィールドが true の場合、create 不可能 (61 ms)
      ✓ 上記以外の場合、create 可能 (55 ms)
    update
      ✓ Itineraries の isImmutable フィールドが true の場合、update 不可能 (62 ms)
      ✓ 上記以外の場合、update 可能 (67 ms)
    delete
      ✓ Itineraries の isImmutable フィールドが true の場合、delete 不可能 (57 ms)
      ✓ 上記以外の場合、delete 可能 (55 ms)
  MPlace
    ✓ get: 無条件で get 可能 (81 ms)
    ✓ list: 無条件で list 可能 (58 ms)
    ✓ create: 無条件で create 不可能 (58 ms)
    ✓ update: 無条件で update 不可能 (47 ms)
    ✓ delete: 無条件で delete 不可能 (48 ms)
  MThumbnail
    ✓ get: 無条件で get 可能 (82 ms)
    ✓ list: 無条件で list 可能 (59 ms)
    ✓ create: 無条件で create 可能 (44 ms)
    ✓ update: 無条件で update 不可能 (39 ms)
    ✓ delete: 無条件で delete 不可能 (47 ms)
  Decorations
    ✓ get: 無条件で get 可能 (77 ms)
    ✓ list: 無条件で list 可能 (58 ms)
    ✓ create: 無条件で create 可能 (62 ms)
    ✓ update: 無条件で update 不可能 (49 ms)
    ✓ delete: 無条件で delete 不可能 (58 ms)
  MMaskShape
    ✓ get: 無条件で get 可能 (76 ms)
    ✓ list: 無条件で list 可能 (45 ms)
    ✓ create: 無条件で create 不可能 (42 ms)
    ✓ update: 無条件で update 不可能 (49 ms)
    ✓ delete: 無条件で delete 不可能 (39 ms)
```


②test実装が設計通りになっているか
https://github.com/Ayato-kosaka/spelieve-firebase/pull/7/files で実装したんだけど
test/firestore.spec.ts
のファイルがテストファイルになっていて、JESTっていうパッケージ使っているんだけど、
上からクロスチェックで眺めるだけ見て欲しい！
jest 慣れてないからムズいだろうけど出来る範囲で大丈夫！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
↑リマインド

**Comment by Ayato-kosaka** [comment]
@Takapy1 
セキュリティルール、ミスってデプロイしちゃったらかなりぶっ壊れるから、クロスチェックはしたいんだけど、、、

見れないって言ってるのは、今週？それとも今スプリント？

**Comment by Takapy1** [comment]
@Ayato-kosaka 
今週の木曜日まで時間が取れない

**Comment by Ayato-kosaka** [comment]
@Takapy1 
おけー、じゃあその後で大丈夫

**Comment by Takapy1** [comment]
@Ayato-kosaka 
申し訳ない！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
Itinerariesのlistが無条件でget不可能なのはなんでだっけ？

**Comment by Ayato-kosaka** [comment]
@Takapy1 
> Itinerariesが無条件でlist不可能なのはなんでだっけ？

しおりは、n件取得する要件が無いから閉じてる〜

セキュリティルールは、必要なものを開ける方針でやってるから、必要のないものは必然的に閉じてるって考えて問題ない〜

もっと言えば、list開けちゃうと、自分が作ったしおり以外のdoc_id が流出するから、
他人のしおりを編集できるようになるため、セキュリティの観点からNG
(user 機能とか導入して他の人のしおりを見れるようになったらここを考えないといけない)

> あとisImutableフィールドの説明簡単にしてくれるとありがたい！

isImutable は最近追加したフィールドで、しおりが編集不可であることを示すフィールド！
しおりをupdateする際に、しおりの isImutable フィールドが true だったらupdateは拒否される仕組みになってる

ごめん、chage 管理に書くの漏れてたから経緯とか↓に書いておく
isImutable を追加した経緯は、instagram とかで一般向けに共有する時に、編集される可能性があるから
isImutable をフロントで編集する方法はないから、instagram に投稿する時に、isImutable Firebase console で手動で変える予定

**Comment by Takapy1** [comment]
@Ayato-kosaka 
LPにある自分が作ったしおり一覧の場所は、listには含まれないないのか

**Comment by Ayato-kosaka** [comment]
@Takapy1 
LPの自分が作ったしおりは、ローカルストレージに配列格納しているだけだから、firestore から取得してないの！！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
ちょっと理解できてない部分ありそうだから後で確認させて！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
それ以外はセキュリティルール大丈夫だと思った！
