### ISSUE TITLE
686 計測指標を決定する

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#740]
[KPI レポート検討](https://docs.google.com/document/d/1gksWdbPox-8-aKlFcsCHMQ1AOUmeqmjV5TkY7o3a2o0/edit#heading=h.f8lvoxy11qvd)

**Comment by Ayato-kosaka** [comment]
@Takapy1 

ねね、↓の設定でAdmob とFirebase analytics を連携させようとしたら、権限エラーになったんだけど、
野口の方で途中まで対応してたとかある？？
https://support.google.com/admob/answer/6383165?sjid=10963213979043355129-AP

**Comment by Takapy1** [comment]
@Ayato-kosaka 
俺も2週間前くらいにやった時に、Firebaseの権限エラーになって、作業中断した覚えがある！

**Comment by Ayato-kosaka** [comment]
```
Google Analyticsは、ウェブサイトやアプリのユーザーエンゲージメントやトラフィックソースを分析するためのツールですが、直接的にApp Storeからのトラフィックソースを特定することはできません。
```
