### ISSUE TITLE
687 時系列SNSとコンセプトの似たSNS探し

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#741]
ゴール: 
有名なSNSの中にないかどうか見たい(なければないでいい)
理由：独占市場かどうか、ユーザを勝ち取れないのが一番の脅威

[競合調べまとめ](https://docs.google.com/document/d/1b8oXXjm2NrAmk3sdx99NzdyBLetQNcaq43ABULrG7Tw/edit#)

**Comment by Takapy1** [comment]
@Ayato-kosaka 
## 現時点の調査状況
- 世界の有名な投稿系SNSの中には時系列のものはなさそう→時系列SNS市場は自体は独占市場、レッドオーシャンではない
  - TikTokのような画像、動画投稿系は流行ってそうだけど
- 旅のしおり系アプリはたくさんあってこのあたりが時系列SNSをやり始めると、競合になりそう

(各国のメッセンジャーアプリはたくさんある)

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ありがとう！！

> 旅のしおり系アプリはたくさんあってこのあたりが時系列SNSをやり始めると、競合になりそう

だよね、旅のしおり系アプリでSNSやってるの結構ありそう。
特にブログ機能もけてるのは結構あるはず。

https://github.com/Ayato-kosaka/spelieve/discussions/715
↑のやつとかありそう
