### ISSUE TITLE
しおりを共有した時にpreview 画面に飛ぶようにする

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#754]
# Product Plan

## Business Goal (why)
=== Write the value and benefit for the business of the Product ===

共有したくても出来ない -> 当たり前品質不足
	また、他のトラクションにも密に関係しており、コスパが高いから取り入れたい

## Task Goal (what)
=== Determin the goal of the task of the Product ===

表題の通り

## Child Sprint backlog items
=== Make child issues on Sprint planning ===
- [ ] #XXX

---
**Labels の付け方**  
* マーケティング => 「Promotion」  
* 開発 => サービスに合わせて選択。どれにも属さない場合は、「Sysetem」を選択。

**Comment by Ayato-kosaka** [comment]
@Takapy1 
これ担当者野口に変更した〜

**Comment by Takapy1** [comment]
@Ayato-kosaka 
サンキュー！
