### ISSUE TITLE
ミッションに賛同する人がいないリスク

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#766]
リスクの特定:
クラファンが現状全く成功していない
ミッションに問題があるのか、そもそもインプレッションがないのか、課題の切り分けが大事

リスクの評価:

リスクの軽減:

リスクの監視:

**Comment by Ayato-kosaka** [comment]
@Takapy1 
平均20人くらいで計62人入ってるみたいだけど、
全くアクションないから、コンテンツ自体に問題がありそうだね

![image](https://github.com/Ayato-kosaka/spelieve/assets/53715839/e2300235-43f3-4168-aabf-569b55515a86)

**Comment by Ayato-kosaka** [comment]
おそらくミッションに問題があるから対策考えます

**Comment by Takapy1** [comment]
@Ayato-kosaka 
なるほどぅ、見てる人はいるのか

**Comment by Ayato-kosaka** [comment]
クラファン自体の戦略に失敗している可能性もある。
成功するクラファンの戦略が出来ていない可能性もある。
