### ISSUE TITLE
アプリストアレビューでエラー発生

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#774]
## Description
Appストアで下記エラーが出て解決方法がわからない
This build is missing export compliance information.

**Comment by Ayato-kosaka** [comment]
@Takapy1 
今回のリリースでもこの課題出たんだけど、これって結論どれ選択すればよかったんだっけ、、
![image](https://github.com/Ayato-kosaka/spelieve/assets/53715839/9ec03286-c8b8-4229-8680-4a7681f2d9cc)

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ごめん、Wikiにかいてあったね、、、 :sweat_drops: 
一番下だね、、

**Comment by Takapy1** [comment]
@Ayato-kosaka 
すまんー！もうちょいわかりやすく場所に書いとくべきやった笑笑

**Comment by Ayato-kosaka** [comment]
🙏
