### ISSUE TITLE
【BUG】予定の順番変更が出来ない

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#788]
# Bug report
## Describe the bug
予定の順番変更が出来ない

## To Reproduce
1. しおり新規作成を選択
2. 場所を2つ追加する
3. 並び替えが出来ない（＝一番上に予定を立てれない）

## Expected behavior

予定の順番は変更できることが仕様としては必要（＝当たり前品質）

## Environment
 - [x] Web
 - [x] iOS
 - [x] Android

## Additional context

----------------------------------------------------------------------
# Solution result
## Cause (バグの原因)

アプリレビュー等で必ず指摘される仕様不具合

## Roll Out
他機能への影響範囲と対応計画を記載する

firebase/firestore#query が使用されている箇所を検索し、PlansMap以外順番変更不要であることを確認

spelieve-code-analysis# npx ts-node ./src/findFunctionCalls.ts query firebase/firestore
https://github.com/Ayato-kosaka/spelieve/blob/develop/src/Itinerary/Contexts/ICT021PlanGroupsList/PlanGroupsList.tsx#L87-L87
=> PlanGroup は代表プランの開始日時でソートしているため順番変更不要
https://github.com/Ayato-kosaka/spelieve/blob/develop/src/Itinerary/Contexts/ICT031PlansMap/PlansMap.tsx#L61-L61
=> 今回対応範囲
https://github.com/Ayato-kosaka/spelieve/blob/develop/src/Place/Contexts/PCT011MPlacesList/MPlacesList.tsx#L82-L82
=> PlaceList の並び替えは不要
https://github.com/Ayato-kosaka/spelieve/blob/develop/src/Place/Contexts/PCT012MPlaceOne/MPlaceOne.tsx#L36-L40
=> Placeid と language で1件に特定するためのquery のため、横展開対象外
https://github.com/Ayato-kosaka/spelieve/blob/develop/src/Thumbnail/Contexts/TCT012MThumbnailList/MThumbnailList.tsx#L38-L43
=> MThumbnailList の並び替えは不要
https://github.com/Ayato-kosaka/spelieve/blob/develop/src/Thumbnail/Contexts/TCT032MMaskShapeList/MMaskShapeList.tsx#L34-L34
=> MMaskShapeList の並び替えは不要

**Comment by Ayato-kosaka** [comment]
設計から必要、個人的には案③が良い

案① Funliday のドラッグ・アンド・ドロップ
一度検討して簡単には出来ないことを確認している。
![image](https://github.com/Ayato-kosaka/spelieve/assets/53715839/0c9855f0-4281-4450-b88d-67d57ef2822f)


案② Wanderlog の Rearrange ボトムシートのドラッグ・アンド・ドロップ
存在の認識が難しそうだから、それが出来るんだったら案①で良い気がする。

案③ 上へボタン、下へボタン
一番ミニマムに作れて、バグも少なそう。
今ゴミ箱ボタン担っているところを、･･･にして、ボトムシートで上へ、下へ、削除
とかにすれば良さそう

**Comment by Takapy1** [comment]
PlanGroupEditで以下の表示すると、
console.log("plans", planGroups.plans);と同じ、順番になっている
→planGroups.plansは表示されている順番通りになっている
```
draxItemList.map(({ planID, index, beforeAfterRepresentativeType, dependentPlanID }) => {
					console.log("planID, index", planID, index)
```
