### ISSUE TITLE
Web でのサムネイルキャプチャでどうしてもCORSエラーを回避できない

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#796]
## Description

html2canvas を用いて html をキャプチャしているが画像だけ映らない
かなり悩んだが解決方法が浮かばない

## 参考

**Comment by Ayato-kosaka** [comment]
@Takapy1 
できたーー
https://html2canvas.hertzen.com/configuration
html2canvas のコンフィグ設定してなかったーーーーーー

https://github.com/Ayato-kosaka/react-native-view-shot-with-web-support/commit/57527ab567b35fd245f285ab87b63d99cf77aea0
で対応した！

![image](https://github.com/Ayato-kosaka/spelieve/assets/53715839/f50c78a2-264c-4cb8-9c8a-485319d2b5b4)

**Comment by Takapy1** [comment]
@Ayato-kosaka 
おーすげーー！！
CORSとかじゃないのか

**Comment by Ayato-kosaka** [comment]
@Takapy1 
あ、このコンフィグのuseCORSってのをtrueにしたら写った！
