### ISSUE TITLE
DLの動作確認を開発環境でどうやるか

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#831]
## Description
DLの作成するリンクが開発環境のリンクではなく、本番環境へのリンクになる
→その場合動作確認はどうやるのか

**Comment by Ayato-kosaka** [comment]
@Takapy1 
iPhone で Spelieve のアプリ消して、リリース環境の start-dev で起動する Expo の build をダウンロードすると、
本番環境じゃなくて、リリース環境のアプリが起動するはずだから、それで動作確認できるかも！

**Comment by Ayato-kosaka** [comment]
https://spelieveuser.page.link/6RQi 
を利用する

**Comment by Ayato-kosaka** [comment]
Internal Distribution を利用すると出来る。
