### ISSUE TITLE
配属後、平日で作業時間が取れない

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#850]
リスクの特定:
研修が終わり、業務中の自己研鑽時間がなくなったので毎日最低30分は取れていた作業時間が消えた

リスクの評価:

リスクの軽減:

リスクの監視:

**Comment by Ayato-kosaka** [comment]
@Takapy1 
あれ、もう研修終わったの？

**Comment by Takapy1** [comment]
@Ayato-kosaka 
グループ全体研修終わってシステムになったらヤバくなった！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
あ、そういうことかぁー
了解したわ！

**Comment by Ayato-kosaka** [comment]
最近は時間取れてるから大丈夫
