### ISSUE TITLE
UI/UXを刷新する

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#863]
子チケット
 - [ ] LPを当たり前品質にする
 - [x] #865 
 - [ ] #866
 - [ ]

**Comment by Ayato-kosaka** [comment]
Tourism characters. Tour group vacation, people with photo and map looking around. Happy travellers, friends together vector scene
![image](https://github.com/Ayato-kosaka/spelieve/assets/53715839/e186e145-8baf-492e-9bb0-ca081c391f2c)

**Comment by Ayato-kosaka** [comment]
@Takapy1 

これ良くない！？

Microsoft bing image creator で作った！

```
a woman making a travel itinerary using map and iPhone on a desk. 
vector scene.
```
![image](https://github.com/Ayato-kosaka/spelieve/assets/53715839/dc99eee7-b7b6-4786-8aa0-dd16090353ae)

**Comment by Takapy1** [comment]
@Ayato-kosaka 
え、これ生成AIやんな？
だとしたらめちゃ良い！！！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
そうそうそう、生成AI!!

**Comment by Ayato-kosaka** [comment]
TODO
* How To Use App の構成を考える（特に代表プラン） → @Ayato-kosaka 
* How To Use App の画像の構成を考える → @Ayato-kosaka 
* 特徴の文章精緻化 → @Takapy1 
* 特徴の画像を生成する → @Takapy1 
* 実装する → 後で

**Comment by Takapy1** [comment]
画像生成方法は考えないといけないと思った。

「特徴」画像作成を試みているけど、Walicaみたいなアプリ画像っぽい画像にならないし、
LP内で画像の色や雰囲気を一貫させたいけど、生成する画像の雰囲気が生成のたびに変わるからむずかしいねー！

もっと入力方法を工夫すればいける気がするけど！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
そうだね、「こう言うの作りたい」ってのがガッチリ決まれば、入力文を詳細化することで思った様な画像生成できると思うよ！
今、あんまり何も決まってない状態でAI生成使うと辺な画像ばっか出てきて時間かかるから、
一旦叩き台は、拾い画か、イメージを文章で記載するだけのほうが良いと思うー！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
念の為共有
LPの特徴欄の作成には以下のドキュメント作成してますー
https://docs.google.com/document/d/1bs9QB9d5o3-kI5S_XIsehFRGPNPlHXAKFSIJiwVVLSw/edit

**Comment by Takapy1** [comment]
@Ayato-kosaka 
LPの画像だけ外注する？

**Comment by Ayato-kosaka** [comment]
> @Ayato-kosaka 
> 
> 念の為共有
> 
> LPの特徴欄の作成には以下のドキュメント作成してますー
> 
> https://docs.google.com/document/d/1bs9QB9d5o3-kI5S_XIsehFRGPNPlHXAKFSIJiwVVLSw/edit

権限なくて見れないから、Spelieve のフォルダに格納して欲しいー　@Takapy1

**Comment by Ayato-kosaka** [comment]
> @Ayato-kosaka 
> LPの画像だけ外注する？


@Takapy1 
画像は自分で作る想定でいたけど、外注したほうがいいの？
外注するにしても、コンサル料的なのを払わない限り、細かくどう作って欲しいかは指示しないと思い通りのものにならないと思うから、言語化どうせするなら、生成AIで良いかなと思ってた

**Comment by Takapy1** [comment]
@Ayato-kosaka 
選択肢としてはアリかなって。

相場をまだ調べてないのでなんとも言えないけど、LPの画像は割と大事だから料金とクオリティ的にいい感じなら、外注してもいいかなって

**Comment by Ayato-kosaka** [comment]
サムネ↓みたいなイメージが良さそう
https://service-cdn.coconala.com/resize/1220/1240/service_images/original/e96735b3-4729869.jpg

**Comment by Ayato-kosaka** [comment]
How To Use App の構成を考える（特に代表プラン）

**Comment by Takapy1** [comment]
@Ayato-kosaka 
Miroに画像とか作成して貼ってみたから時間ある時に確認お願いします。
https://miro.com/app/board/uXjVOqfg7vM=/?share_link_id=207220851569

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ありがとう！
画像が揃ってきたから、全体感を見た画像テイストの議論が出来るね！

俺の感想として、
自分が選んだやつも含めて画像がシンプルじゃないのが多いから、タイトルと合っていない感じがする。
なんか、ごちゃごちゃしているイメージ、、、

* 配色を合わせたい（オレンジ＋グレー）
* 人/モノ が多いからシンプルにしたい
* 最後の「旅行を楽しむ」はごちゃごちゃしてても良いと思うけど、それ以外かなりシンプルにしても良いかも？

**Comment by Ayato-kosaka** [comment]
@Takapy1 
How to use の画像イメージ 作ったので、気になることあったらコメント頂戴〜

**Comment by Takapy1** [comment]
@Ayato-kosaka 
How to use確認した！
使ってるアプリ内の場所の画像はいいと思う！
