### ISSUE TITLE
Google Admob ポリシー違反対応

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#864]
## Description
以下の画像のようにポリシー違反しているから直せというアラートが来ている
<img width="1092" alt="スクリーンショット 2023-09-30 11 13 52" src="https://github.com/Ayato-kosaka/spelieve/assets/75763679/af1abfc6-b6cd-41f5-84ba-c70ce0ae1f92">

違反している項目がわからないので調査中

## 調査
以下の記事では、広告の上にマージンを少し追加して審査リクエストしたら承認された（マージン追加しても広告フレームのサイズをいじっているわけではないので、ポリシー違反を指摘された本質的な問題解決をしたわけではないのに通ったということ）
[「広告フレームのサイズを変えるように広告コードが変更されています」の修正 ](https://qyu555.blogspot.com/2022/01/admob-sdk-banner.html)

## Solution
#867 で修正済み
（本番環境で問題なく表示されるかは試せていないので、リリース時に確かめる）

**Comment by Ayato-kosaka** [comment]
あれ、どういうことやろ
変なスタイルが入ってしまってるのかな

**Comment by Takapy1** [comment]
@Ayato-kosaka 
明日調べるわ！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
調べてみると、広告フレームのサイズを変更してないのにポリシー違反きたりするらしいから
一旦何も周せずに、審査リクエストしてみました。

再度、ポリシー違反で警告されたら対処する方針でいきます。

**Comment by Ayato-kosaka** [comment]
@Takapy1 
了解した！
でも、iPhoneで開くと確かに高校の大きさ変な時あるよ？
Install の文字が切れてる！

![image](https://github.com/Ayato-kosaka/spelieve/assets/53715839/9592d3f5-4bbc-4634-a322-036bd359bfb0)

**Comment by Takapy1** [comment]
@Ayato-kosaka 
ほんやま、俺のやつ広告何も映らなくなってるのよね

**Comment by Takapy1** [comment]
@Ayato-kosaka 
こちら、Admobから広告表示は制限されていないけど、
表示が壊れていて、誰も押さなくなっていて収益が０になってます。

数十円でももったいないので、本日から修正対応してもいい？
