### ISSUE TITLE
How To Use App の構成を考える（特に代表プラン）

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#865]
How To Use App の構成を考える（特に代表プラン）

_Originally posted by @Ayato-kosaka in https://github.com/Ayato-kosaka/spelieve/issues/863#issuecomment-1745879128_

**Comment by Ayato-kosaka** [comment]
案１（旅程作成のイメージを全て説明するパターン）
タイトル：Spelieve の使い方
サブタイトル：旅のしおりを簡単に作成できます！
１枚目：しおり作成し、サムネイル入力
２枚目：行きたい場所を入力
３枚目：その前後に行きたい場所を入力
４枚目：友達にURLをシェア
５枚目：旅行を楽しむ！！！


案２（自動計算の仕組みに特化させるパターン）
タイトル：旅程自動計算の使い方
サブタイトル：シンプルで柔軟な旅程作成が出来ます！
１枚目：行きたい場所を入力
２枚目：その場所の滞在時間を入力
３枚目：その前後に行きたい場所を入力すると開始時間が自動計算される
４枚目：プラン間の移動手段を選択すると移動時間が自動計算される
５枚目：代表プランの予定を変更するとその他の予定が追従する
６枚目：代表プランの変更や予定の並べ替えも可能

**Comment by Ayato-kosaka** [comment]
@Takapy1 
How To Use App の構成のところ、一旦たたき台作れたから意見ほしい！

今まで考えてきたのが、案１の流れけど、
考えてるうちに、案２の流れにしないと代表プランの説明が無理だなって思い始めて悩んでる、、、
案１の後に案２をAdvanced みたいな感じで加えるか、そもそも案１が要らないか、、かなと現時点では思ってる、

**Comment by Takapy1** [comment]
@Ayato-kosaka 

パターン1がLPには適していると思う。
LPでのHow to useは「使いやすさ」をメインに伝えた方がいいと思うから。

使いやすさを重視する理由
- 新規ユーザはどんなアプリか一瞬で判断するから、LPに長々と説明文を書いてめんどくさいと思われたくない
- すぐにアプリ内に入ってきて欲しい
- LPがシンプルになるから

特徴でサムネイル、自動計算は紹介しているから、アプリ内のUIUXをあげることでLPに自動計算などの説明書かずとも機能理解させる方法を検討した方がいいかな！？
例えば、直感的にサムネイル登録編集できるのがわかるとか、代表プランを目立たせるとか

ただ、Advanced説明は別であった方がいいと思う！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ありがとう！！！！！

> LPでのHow to useは「使いやすさ」をメインに伝えた方がいいと思うから。
これその通りだと思うわ、LPに難しいこと書くと離脱しそうだね。

一方で、
> アプリ内のUIUXをあげることでLPに自動計算などの説明書かずとも機能理解させる方法を検討した方がいいかな！？
UIUX で、代表プラントそれに紐付くプランの説明するのってかなりむずそう


ちょっともう一回考え直してみる！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
そしたら、こんなイメージかな？
* ホーム画面では、広く浅くシンプルに使い方を説明
* 代表プランの説明は一切省く（代表プランの説明は別途要検討 :warning:  ）
![image](https://github.com/Ayato-kosaka/spelieve/assets/53715839/f04b1130-75d2-4305-b57c-685bef5e565b)

代表プランの説明をホーム画面でやらない整理にすると、
使い方を見てもらう優先度が下がるので、全体的なイメージ感が変わってくるね。
* 特徴上、使い方下で良さそう
* 横スクロール消しても良さそう
  * 実装コストがかかる
  * walica でも使ってないし

**Comment by Takapy1** [comment]
@Ayato-kosaka 
特徴の下にする、横スクロールなしにする
→そっちの方がいいと思う。

**Comment by Ayato-kosaka** [comment]
Miro 最新化したからクローズ
代表プランの説明は別チケット切り出し #866
(cc @Takapy1 )
