### ISSUE TITLE
Instagram を始めれるくらいの品質に持っていく

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#876]
■ 取りまとめ
https://docs.google.com/spreadsheets/d/1FbkHTiRWEjSkW6xUkNTKhEBhp-KysZkgdd8Kg-rR-Xc/edit#gid=0

■ 対応予定タスク
- [x] #879
- [x] #882 
- [x] #884
- [x] #886
- [x] #898
- [x] #723 
- [x] #887
- [x] #889

**Comment by Ayato-kosaka** [comment]
@Takapy1 
https://docs.google.com/spreadsheets/d/1FbkHTiRWEjSkW6xUkNTKhEBhp-KysZkgdd8Kg-rR-Xc/edit#gid=0
スプシはここ！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
昨日教えてくれた、アプリの気になる所、忘れちゃったから起票しておいて！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
とりあえず、モンキー打鍵して、アプリ使用感の洗い出し完了した！
改修できる所から始めだすから、アプリ使用感で何か気になる所あれば新規起票しておいて！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
パソコンさわれないから、一旦ドキュメントで共有します

https://docs.google.com/document/d/113dOiXFv2hNmr8EYfWJYYvwrIJtXFyWN4cgB-emyDzs/edit

**Comment by Ayato-kosaka** [comment]
ありがとう！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
昨日重要度と難度見て対応順序するタスク決めるって行ってたけど、やっぱり重要度大（当たり前品質）だけ対応して、
早めに品質確保して、次のフェーズ（インスタとか）に進めるようにしたほうが良い気がしてきた！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
返信できてなかった！
了解です
