### ISSUE TITLE
Preview に URL で飛ぶと、Edit に遷移できなくなる

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#884]

**Comment by Ayato-kosaka** [comment]
*デグレ検知*
Create Itinerary を2回行うと1回目が残っている

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ちょっと次の打ち合わせで相談させて欲しい、、

↓で整理しているけど、かなり根深そう。。
https://docs.google.com/spreadsheets/d/148SwXNGl5tc4HASBQrhUfb0t0FwoSpvR-10nULA8xhI/edit#gid=0

問題は、「しおり選択後新規作成」と「Preview から遷移」で同じ、下記初期値になること
* route.params.itineraryID is null
* itineraryDocSnap?.id is not null

ここを切り分けるには、下記2対策が考えられる
1. route.params に isCreate を持たせる
2. ItineraryEdit と ItineraryPreview で、route.params.itineraryID を共有する

1 は、難易度低いけど、パラメータ増えるから避けたい。
2 は、難易度が高そう。。

ちょっと要検討そう

**Comment by Ayato-kosaka** [comment]
案3 しおり選択からホーム画面に戻るとstate の itineraryID クリアする

案4 createItinerary で、Stack ごと新しくする→つまり、Context が初期化される（そんなことできるのかは不明）

案4が一番あるべきに近そう。
そうすると、以下の優先順で初期化できる
1. Context の itineraryID
2. Route の itineraryID
3. CreateItinerary

**Comment by Takapy1** [comment]
@Ayato-kosaka 
時間とってちゃんと確認してから返信します！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
内容理解にめちゃ苦戦してる！
あしたのMtg までにもう少し俺もコード理解深めてみるけど　
理解不十分だったらごめん！！！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
打ち合わせで説明するから大丈夫だよ！🙆

**Comment by Ayato-kosaka** [comment]
だめだ、、、
ItineraryPageNavigator 直下に Context があるから、案4 で ItineraryTopTabNavigator のStack新しくしてもState 持ったままだ、、
![image](https://github.com/Ayato-kosaka/spelieve/assets/53715839/3b498e1d-46c8-466b-814f-28c108b52205)

**Comment by Ayato-kosaka** [comment]
本来の画面遷移から考えると↓にならないといけないが、

 - Group
   - HelloSpelieve
   - Group
     - ItineraryPreview
     - Group
       - ItineraryEdit
       - EditPlan

↓になっているのがおかしい
 - Group
   - HelloSpelieve
   - EditPlan
   - Group
     - ItineraryEdit
     - ItineraryPreview

**Comment by Ayato-kosaka** [comment]
対応内容 memo
* IPA003EditPlan を INV002ItineraryTopTabNavigator 直下から INV002ItineraryTopTabNavigator 直下に移動
* ICT011ItineraryOneProvider, ICT031PlansMapProvider, ICT021PlanGroupsListProvider を INV002ItineraryTopTabNavigator 直下から INV002ItineraryTopTabNavigator 直下に移動
* PCT012MPlaceOneProvider を INV002ItineraryTopTabNavigator 直下から IPA003EditPlan 直下に移動
* IPA001ItineraryEditController での 初期化処理を、[こちら](https://docs.google.com/spreadsheets/d/148SwXNGl5tc4HASBQrhUfb0t0FwoSpvR-10nULA8xhI/edit#gid=0)の整理を基に修正

**Comment by Ayato-kosaka** [comment]
## 課題
react navigation を使って EditPlan に遷移すると、ヘッダが 3つ出る。
あまりに大きいのと、Edit Plan からの遷移は ItineraryEdit だけで良い。
理想はモーダル化して、ItineraryEdit に選択した Place を渡したい。
ただ、Edit Plan は Plan を update する処理が入っているので、Context の管理下かから外れることが出来ない。
つまり、Context の階層関係と、 react navigation の階層関係で合わない。

**Context の階層関係**
* HelloSpelieve
* Context
  * ItineraryEdit
  * ItineraryPreview
  * EditPlan

**react navigation の階層関係**
* HelloSpelieve
* EditPlan
* Group
  * ItineraryEdit
  * ItineraryPreview

じゃあどうするべきか、と考えると
* Context の階層関係は破る事は物理的にできでない
* Context の階層関係を破る場合は Context 複製になる。ソースが複雑になりすぎる、、
* Context の階層関係を守らないと今回のような不具合が発生するから優先したい！！！
* react navigation の階層関係も見方によっては不自然
* [ここ](https://github.com/Ayato-kosaka/spelieve/issues/884#issuecomment-1783695772)で述べているのがあるべき姿。
* なぜ、上記のような階層関係にしなければならないかと言うと、EditPlan -> ItineraryEdit に限定（モーダル化等）させるにはそうするしか無い。

**Comment by Ayato-kosaka** [comment]
**nacigation events を使って無理やりモーダルみたいにしてみる**


**react navigation で親の screen options を setOptions するにはどうするか**
* [Screen options with nested navigators](https://reactnavigation.org/docs/screen-options-resolution/#setting-parent-screen-options-based-on-child-navigators-state) ここらへんっぽい
* Show screens without tab bar: a tab navigator contains a stack and you want to hide the tab bar on specific screens (not recommended, see [Hiding tab bar in specific screens](https://reactnavigation.org/docs/hiding-tabbar-in-screens) instead)
* これだ！
* でも、これ見ると、やはり、react navigation の指向で階層関係書けって書いてるなぁ、（モーダルだったらトップ階層で別にする）
* その場合、Context どうするんだろ、、

**Comment by Ayato-kosaka** [comment]
ちょっと考えてみたけど、Context 指向じゃないと無理そうだから無理やり非推奨の実装する。
今の所困りそうにないけど、後々困ったらまた考える。

**Comment by Ayato-kosaka** [comment]
一回 react navigation のドキュメント全部読もうかな、、
そうしないとイマイチ動きがわからんなぁ、、

**Comment by Ayato-kosaka** [comment]
* navigation.navigate は、履歴になければ追加、あれば履歴に戻る

**Comment by Ayato-kosaka** [comment]
react navigation のドキュメントは完全にネストは最小限にすべきで、レイアウト指向でネストを決定すべきって書いてるなぁ、、
じゃあ、Context の考え方を再整理したほうが良いのかなぁ、

**Comment by Ayato-kosaka** [comment]
方針としては、
* レイアウト指向でネストを決める
* モーダルは Context を使わずに、更新処理を実装する

**Comment by Ayato-kosaka** [comment]
↑を対応するとなると EditPlan の実装が大まかにか分かるからかなりの実装修正が必要になる。。
対応すべきか？
→ 今後のデータコンセプトの修正で必要なくなるかもだけど、まずは当たり前品質改善 -> インスタ だから対応する

**Comment by Ayato-kosaka** [comment]
UT でバグ検知。
PlanEdit 画面で Representative Plan の開始時間を変更しても、 ItineraryEdit 画面に戻ると反映されていない。

起因
①PlanEdit 画面で開始時間を変更 → DB の PlanGroup を更新
②上記を ItineraryEdit 画面で検知して useEffect が発射し、DB の plan の startTime が更新
③戻るボタン押下時にDB の plan をPlanEdit 画面の画面保持情報で上書きするため、元の値で上書きされる。

原因
ItineraryEdit 画面 はリアルタイムに DB をウォッチし、DB を直接更新する仕組み。
PlanEdit 画面は、画面情報を保持しておき、RemovePage で一括DB更新する仕組み。

なのに、起因①のように、PlanGroup だけその場で更新しているため障害となる。

対策
PlanGroup も画面で情報を保持しておき、画面離脱時に更新するようにする。

**Comment by Ayato-kosaka** [comment]
UT でバグ検知。
Plan のサムネイル画像作成後、 ItineraryEdit に戻り、再度 PlanEdit に入ると場所の画像に更新される。

原因
plan.imageUrl 更新処理の設計不備。
place.imageUrl を監視して更新している。

解決策
place.place_id を監視し、place が plan が持っているものから更新された場合、 title, imageUrl を更新する
