### ISSUE TITLE
ノルウェーの google play でダウンロードできない

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#887]

**Comment by Ayato-kosaka** [comment]
ここ全選択にしたら出来そう
![Uploading image.png…]()

**Comment by Ayato-kosaka** [comment]
@Takapy1 
設定完了したからリリース後確認するわ！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
ありがとうー！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ノルウェーの google play で出たのでクローズします！
https://play.google.com/store/apps/details?id=com.spelieve&hl=no&gl=US
