### ISSUE TITLE
サンプルしおりの作成

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#894]
## Description
LP内の「サンプルしおりを参照」ボタンを押した際の、遷移先の作成
作ってみたいと思わせるような「見本となるしおり」の作成が必要

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ハルシュタットで英語版はできるはず！
日本語版は新しく作らないとかもね、

**Comment by Takapy1** [comment]
@Ayato-kosaka 
なるほど、それで設定するわ！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
ちなみに、i18n.t()を使用している部分を抽出する方法が前にあったと思うけど、
どうやったっけ？

**Comment by Ayato-kosaka** [comment]
@Takapy1 

https://github.com/Ayato-kosaka/spelieve/issues/467#issuecomment-1370754420

↑かな？
npm run grepI18n
で取れるかも！

**Comment by Takapy1** [comment]
@Ayato-kosaka ありがとうー、
