### ISSUE TITLE
ネイティブアプリ移行検討

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#91]
## What
React と互換性をもたせながらネイティブアプリ化する方法を検討する

## TODO
- [x] #246
- [ ] #247
- [x] #248
- [ ] #249
- [ ] #250
- [ ] Webページで開いた時に画面サイズを制限する

**Comment by Ayato-kosaka** [comment]
React と React Native では、画面サイズ、コンポーネントの互換がない可能性がある。

React Native を web にデプロイすることも可能なため、React Native で作成する？等検討する必要あり。

**Comment by Ayato-kosaka** [comment]
まだ環境構築とかまではできてないけど、
React native と React app やと、ロジックの共有はできそう、
ただ、view の共有はほぼ不可能に近そう、、、
▼参考

https://qiita.com/whitphx/items/7c66691fe6cc244053de

**Comment by Ayato-kosaka** [comment]
Logic が共有できると仮定すると、viewだけreact native に移行すれば native アプリ化はできそう。

そこで、方針としては以下2通りが考えられる。
1. ver1.2の段階でreact native化をし、react native でwebにもデプロイする。
　メリット:総合的に見て手間が少ない
　　　　　　web, native app でviewコードが統一できるからメンテが楽
　デメリット:ver1.2が確実に押す
　　　　　　　今までReactでやってきてたのに急に移行すると知見とか含めてディスアドバンテージがすごい

2. ver4リリース後にリファクタリング含め、react native 化を行う。

**Comment by Ayato-kosaka** [comment]
@Takapy1 
↑の整理かなと思ってて、
Spelieve はwebでも、完全にスマホ向けやし、普通に考えたらreact native 1本にするべきやけど、
急にフレームワーク移行するのすげえ怖いけど
どう思う？（もちろん、実際に動かしてみて最終的に考えるけど、、、）

**Comment by Ayato-kosaka** [comment]
![image](https://user-  images.githubusercontent.com/53715839/183233043-4247668f-4af9-495f-8d2c-804f39440695.png)

ネイティブ開発はFlutterが強いんよな、、、
Flutter はjsですはないけど、笑

**Comment by Ayato-kosaka** [comment]
![image](https://user-images.githubusercontent.com/53715839/183243242-e5600a30-3e07-4f69-a5e1-59a7469f582d.jpeg)

**Comment by Ayato-kosaka** [comment]
react native vs flutter
**reactで培った知見を無駄にしたくない+もしこだわりを貫くならそもそもクロスプラットフォームにしないのが正解だから、react native を利用する**

**Comment by Takapy1** [comment]
> react native vs flutter **reactで培った知見を無駄にしたくない+もしトレンドを貫くならそもそもクロスプラットフォームにしないのが正解だから、react native を利用する**
そうしよう、学び直しはきつい

**Comment by Takapy1** [comment]
@Ayato-kosaka 
リポジトリは作り直すと、Issueとか作り直しでだるくなるけど、
整理されるから作り直しの方がいいか

**Comment by Takapy1** [comment]
一旦１４日まで、ロジックの方をTypescript化
その後React Native化の流れって感じ？

**Comment by Ayato-kosaka** [comment]
**LINEで共有した時の画像、タイトル、説明文が適切に表示されない**

**Comment by Ayato-kosaka** [comment]
【要検討】iOS, Android へのデプロイ
