### ISSUE TITLE
テンプレートの後に変更が困難になる要素を決定する

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#918]
## 固めたいこと
- [x] font-family
- [x] 文字/行間隔
- [x] 代表3色
- [x] 副色
- [x] レイアウト
- [x] 画像テイスト（編集方法）

## 確認したいこと
- 画像の集め方相談

## 提供するもの
- 依頼の目的とゴール
- Instagram 運用の目的とゴール
- アカウントのジャンル（便益性と独自性）
- 投稿済みの Hallstatt のポスト
- 参考にしているもの（ポストやaruco等）
- 投稿の構成
- Hallstatt の Rewrite
- Marina Bay
- 京都（表紙のみ）
- プロフィール投稿欄
- その他確認したいこと

**Comment by Ayato-kosaka** [comment]
■ 依頼の目的とゴール
目的：Instagramの運用を本格的に始めるにあたり、デザインの専門家の助言を得て、Instagram投稿用のテンプレートを確立すること
ゴール：後に変更が困難になる以下の要素を決定したい
・ レイアウト
・ 色彩
・ 画像スタイル
・ フォントファミリー
・ 文字間隔・行間隔

■ Instagram 運用の目的とゴール
目的：Spelieveへのユーザー流入を促進すること
ゴール：Instagram上でフォロワーを獲得し、インプレッションを増加させること

■ アカウントのジャンル（便益性と独自性）
便益性：海外旅行、特に女子旅に焦点を当て、おしゃれでユニークな体験を提案する。
独自性：具体的なモデルプランを用い、どのようにその場を楽しむかを示す。この分野ではまだ少ない、世界を対象にした情報まとめを提供。

■ 投稿の構成
Spelieveのコンセプトに沿い、編集された画像を用いて、旅行プラン作成アプリとしての価値を示したい。
若い世代や旅行が好きなファッショナブルな女性をターゲットにし、国内外にわたる幅広いアプローチを目指したい。
言語は英語を使用し、世界規模の旅行体験を提供したい。

1枚目：表紙
2~7枚目：訪れる場所の画像
8枚目：マップを用いたサマリ
9枚目：Spelieve へ流入する CTA
10枚目：フォローに繋げる CTA

■ デザインの参考にしているもの
英語の情報まとめ系のポストが少ないため、以下の日本の投稿を参考にしています。

[参考Instagram投稿](https://www.instagram.com/p/Cu4MQ2_vUdJ)
また、「aruco magazine」や「るるぶ」もデザイン参考にしています。

■ 投稿済みのポスト
[お試しで投稿したポスト](https://www.instagram.com/p/Cr7-l7mry6r)

■ Hallstatt の Rewrite
■ Marina Bay
■ 京都（表紙のみ）
■ プロフィール投稿欄
■ 発見欄での見え方 ← 要らないかな？ :thinking: 
■ その他確認したいこと

**Comment by Ayato-kosaka** [comment]
## 相談相手探し
ココナラで調査してみた結果、以下全部に該当させようと思うと流石にヒットしない。
・既存デザインに対する相談
・Instagram の投稿向けのデザイン
・コンセプトが合致している（そもそも 海外旅行 ✕ 女子 はいないから、女子で絞るしかなさそう）

となると、Instagram の投稿向けのデザイン 関連の依頼を受け付けていて、コンセプトがある程度合致しているユーザを探して、既存デザインに対して添削をお願いできるか直談判してみるしか無いかな。

**Comment by Takapy1** [comment]
> はじめまして。この度は「[canvaでインスタグラム投稿画像制作します](https://coconala.com/services/2391638?ref=service_recommend_provider)」というサービスに目を留め、ご連絡させていただきました。私のプロジェクトに対し、ななさんのデザインセンスと技術が大変合致すると感じております。

はじめまして。この度は「[canvaでインスタグラム投稿画像制作します](https://coconala.com/services/2391638?ref=service_recommend_provider)」というサービスに目を留め、ご連絡させていただきました。**私のプロジェクトと**ななさんの**デザインセンスや技術**が大変合致すると感じております。


> まずは、具体的な依頼内容をご案内し、それに基づく見積もりをお願いしたく思います。

まずは、**こちらから**具体的な依頼内容をご案内し、**それに基づき**見積もりをお願いしたく存じます。
具体的な依頼内容の案内はこっち
見積もりを相手にして欲しい事を明確にするため

> ■ 依頼の目的とゴール
> 目的：運用中のInstagramを再構築するにあたり、デザインの専門家の助言を得て、3色展開の投稿用テンプレートを作成すること
> ゴール：後に変更が困難になる以下の要素を決定したい
> ・ テンプレートのレイアウト
> ・ 色彩
> ・ 画像フィルタ
> ・ フォントファミリー
> ・ 文字間隔・行間隔

Good！


> ■ Instagram 運用の目的とゴール
> 目的：私が運用するアプリ「Spelieve」へのユーザー流入を促進すること
> ゴール：Instagram上でインプレッションを増加させること、QRコードから Spelieve へ流入するチャネルを開放すること

■ Instagram 運用の目的とゴール
目的：私が運用するアプリ「Spelieve」へのユーザー流入を促進すること
ゴール：Instagram上でインプレッションを増加させること、QRコードから Spelieve へ流入するチャネルを開放すること
■ アカウントのジャンル
便益性：海外女子旅に特化し、おしゃれかつユニークな体験を提案
独自性：具体的なモデルプランを使用し、楽しみ方を示す。この分野ではまだ少ない、世界を対象とした情報を提供。

■ 現在の運用状況
Instagramアカウント @spelieve で、試験的に2つのポストを行いました。
[お試しで投稿したポスト](https://www.instagram.com/p/Cr7-l7mry6r)

■ 再構築後の投稿の構成
Spelieveのコンセプトに沿い、編集された画像を用いて、旅行プラン作成アプリとしての価値を示したい。
若い世代や旅行が好きなファッショナブルな女性をターゲットにし、国内外にわたる幅広いアプローチを目指したい。
言語は英語を使用し、世界規模の旅行体験を提供したい。

1枚目：表紙
2~7枚目：訪れる場所の画像
8枚目：マップを用いたサマリ
9枚目：Spelieve へ流入する CTA
10枚目：フォローに繋げる CTA

■ テンプレートのレイアウトについて
1種類のテンプレートを3色で展開し、プロフィール投稿一覧が美しく映るようにしたいです。以下に、試作したテンプレートのデザインを示します。
[テンプレートデザイン](https://www.canva.com/design/DAF2dlNbLh8/PtQW40fM6ZF1mVZb5TWTgA/edit)
デザインの添削をお願いします。

＜参考にしているレイアウト＞
英語の情報まとめ系のポストが少ないため、以下の日本の投稿を参考にしています。

・[参考Instagram投稿](https://www.instagram.com/p/Cu4MQ2_vUdJ)
・「aruco magazine」および「るるぶ」

■ 色彩
3色のパターンを以下のように検討しています。

1. ピンク系: 自然・郊外エリア
2. 青系: 都市・都会エリア
3. 黄・オレンジ系: 歴史的・文化的エリア

仮の色を以下に示しますが、色の相性や発見タブでの目立ち具合、アカウントのコンセプトとの相性を考慮し、最適なHEX色を提案していただければ幸いです。
[プロフィール投稿欄イメージ](TODO:投稿欄)

■ 画像のフィルタ
現状、画像にフィルタはかけていません。統一感のあるフィルタをCanvaで選定していただきたいです。

■ フォントファミリーについて
現在は「Alice」を暫定的に使用していますが、海外女子旅をイメージする適切なフォントの選定をお願いします。

■ 文字間隔・行間隔
現在の設定について、最適な数値の決定をお願いします。

ご検討のほどよろしくお願いいたします。

**Comment by Ayato-kosaka** [comment]
![image](https://github.com/Ayato-kosaka/spelieve/assets/53715839/2b8c4579-a48e-4f3d-8625-4473f3f48f99)

**Comment by Ayato-kosaka** [comment]
# font-family 検討 
## 本文のフォント
かっこ良くて、作りたい世界観に合っているから Alice でいきたい。
洗練されたしおりという印象を出しやすい。

## 表紙 のフォント
は以下の案がある。
案① Instagram の雰囲気を出すメイン CanvaSans ＋ ヘッダは主張を減らす Oswald
案② ボディに合わせて Alice でいく。
案③ Instagram の雰囲気を出すために全体的にCanvaSans

![Image](https://github.com/Ayato-kosaka/spelieve/assets/53715839/f5ea91f1-cc88-4e58-b342-6b146ca0196f)

照らし合わせた時に、発見欄で見やすい点と、見欲しい文章を強調できて出したい世界観を出せてて、表紙の画像テイストに合う案①を採用する。
