### ISSUE TITLE
Instagram 投稿内容コンセプト定義

### ISSUE THREAD

**Issue by Ayato-kosaka** [Ayato-kosaka/spelieve#929]
## ターゲットの悩みの理解
海外旅行は、文化や言葉の違いによる不安、限られた時間と予算の中で最高の体験をしたいというプレッシャーからハードルが高くなっている。
また、多くの人々にとって、旅行計画において、どこに行くべきか、何をするべきかという点で不安を感じている。

## ターゲットの悩みを解決する投稿コンセプト
真似するだけで幸せになれる細部までこだわったモデルプランの「レシピブック」 を提供する。

## もってもらいたいイメージ明確化
細部にこだわったモデルプランを見て、人生で一度は訪れたいと感じる。
海外旅行に行くことで得られる体験をインスピレーションでき、背伸びしてでも行きたいも感じる。
世界中のさまざまな文化を経験し、自己発見の旅をすることで、人生がより豊かになる。
「レシピブック」を通じて、どんな旅行者でも素晴らしい体験ができるという信頼感。

**Comment by Ayato-kosaka** [comment]
## これまで整理した内容の振り返り
### アカウントコンセプト（[こちら](https://docs.google.com/document/d/1bPc5FGO-IA3glksTouUepcjqn9TvAm90djKiZIuZa9Y/edit#heading=h.ftbyd09dgw1t)から引用）
```
メインイベントから始まる、モデルプランのレシピブック
メインイベントを軸とした周辺の周り方を含めた時系列のモデルプランで提供
```
### ターゲット（旅マエ（旅行具体的計画段階））の顧客層　（※ https://github.com/Ayato-kosaka/spelieve/issues/926#issuecomment-1872460729 から引用）

#### ペルソナ設定:
- **名前**: 高橋 健太（ケンタ）
- **年齢**: 35歳
- **職業**: 自営業
- **興味・関心**: 効率的な旅行計画、地元の体験、オフビートな目的地。
- **海外旅行に対する態度**: 海外旅行先は決めており、その国の詳細な情報や具体的な旅行計画を求めている。
- **メディア利用**: スマートフォンでの検索、旅行専門のアプリ、SNS、口コミサイト。

#### 顧客層の特徴:
- 顧客は旅行先やコンセプトは決まっている。
- 旅行先で絶対やりたいことを決めたい。
- 各日のメインイベントを決めたい。
- 2~3時間単位での旅程を決めたい。

#### Spelieve インスタを利用するカスタマージャーニー
1. ケンタは韓国に5泊6日での友達との旅行の計画を立てるため、インスタグラムを見ています。
2. ケンタは計画中の旅行先についての具体的な情報を探している際に、友人のリコメンドや検索を通じてあなたの投稿を見つけます。
3. 彼はあなたの投稿で提供されているメインイベントとその周辺旅程に興味を持ちます。
4. ケンタは彼の旅行計画に役立つ投稿を保存し、質問をコメントをします。
7. ケンタはあなたのアカウントで得た情報を基に、宿泊施設の予約、観光スポットの選択、現地でのアクティビティ計画など、具体的な旅行の手配を行います。
8. 次回の旅行計画のため、アカウントをフォローします。


## ターゲットの悩みの理解
旅先で具体的に何をするかについてビビっとくるものがない。

## 解決するための1メッセージ検討

## 解決策を投稿化する方法

## もってもらいたいイメージ明確化

**Comment by Ayato-kosaka** [comment]
Spelieve が目指している、「どこに行くか」という観点ではなく、「どう周る旅行にするか」という観点の新しい表現方法を、 Instagram を表現するために、
「どう周る旅行にするか」が例えばどんな内容で、旅のしおりへどう再現出来て、投稿としてどう表現するかを明確にする必要がある。
そうすることで、Instagram 投稿内容コンセプト定義 される。

**Comment by Ayato-kosaka** [comment]
![image](https://github.com/Ayato-kosaka/spelieve/assets/53715839/4df828b4-94ec-48ff-aafd-580e950426cd)

🗻🚗✨ 忘れられない旅：友情と自然の中での富士山ドライブ 🌄
朝から夜まで、最高の仲間と最高の景色を楽しんだ一日。朝のレンタカーでのピックアップから始まり、河口湖でのBBQ、湖での楽しい時間、温泉でのリラックス、そして富士山の息をのむような夕日。最後には、ちょっぴり酔いつぶれながら美味しい食事で締めくくり。🍖🍺🛀
#富士山 #ドライブ #友達と旅行 #日本の自然 #BBQ #温泉 #夕日 #美食 #旅の思い出

**Comment by Ayato-kosaka** [comment]
例えば↑みたいな感じ。
目的地だけでなく旅そのものの体験を重視する旅行を表現できている。
後は、それを旅のしおりへどう再現出来て、投稿としてどう表現するかを明確にする必要

**Comment by Ayato-kosaka** [comment]
**目的地だけでなく旅そのものの体験を重視する旅行** を洗い出してみる。
- 友情と自然に浸る忘れられない富士山ドライブ
- 野生との一体感を味わう星空の下でのサファリキャンプ
- 自転車で巡る歴史を感じる古い町並み旅
- 自給自足を感じる農園体験と採れたての地元の食材を使った料理体験旅
- マリンスポーツとビーチで楽しむ夜のパーティー
- 自然の中で鳥を観察し、自然との調和を楽しむ森林でのバードウォッチング
- 忘れ去られた場所を訪れ、独特な写真を撮る廃墟探訪
- ワイナリーでの葡萄畑巡りとワインテイスティング

**Comment by Ayato-kosaka** [comment]
## 目的地だけでなく旅そのものの体験を重視する旅行
野生との一体感を味わう星空の下でのサファリキャンプ

## 再現出来る旅のしおりへの表現
### 1. 旅の始まり：自然への準備と移動
- **自然に近い宿泊地への移動**
  - 都市部からサファリ地点への移動。
  - 途中の風景を楽しむための休憩所でのストップ。

### 2. メインイベント：サファリキャンプ
- **野生動物との出会い**
  - 専門のガイドと共にサファリツアー。
  - 野生動物の観察と写真撮影。

- **キャンプ地での夜**
  - 星空の下でのキャンプファイア。
  - 地元の料理と夜のアクティビティ。

- **星空観察**
  - 専門家による星空解説。
  - 星座観察や夜間の自然音の体験。

### 3. 旅の終わり：自然との別れ
- **サンライズハイキング**
  - 日の出を見るための早朝ハイキング。
  - 自然の美しさと静けさを感じる時間。

- **地元の村訪問**
  - 地元の村に立ち寄り、文化交流。
  - 地元の工芸品や食べ物の体験。

- **帰路とまとめ**
  - キャンプ地からの帰路。
  - 旅のハイライトと感想の共有。

## 投稿としての表現
![image](https://github.com/Ayato-kosaka/spelieve/assets/53715839/1fffc928-d32d-4389-aed1-b5491582b4fe)
```
🌟🏕️🐘 自然の雄大さを体感：星空の下のサファリキャンプ 🌌
私たちの素晴らしいサファリの冒険は、野生の動物たちとの一体感と、星空の下でのキャンプファイヤーから始まりました。この旅では、自然の美しさと野生の魅力を存分に感じることができます。サバンナの中での夜は、静寂に包まれながらも、生命のエネルギーに満ちています。この壮大な景色と、野生動物たちとの遭遇は、一生の思い出になること間違いなしです！
#サファリキャンプ #星空 #野生との一体感 #冒険旅行 #自然体験 #旅の思い出
```
※旅程の詳細は、Bay Sans のような構成の投稿で表現する

**Comment by Ayato-kosaka** [comment]
@Takapy1 
Instagram の投稿内容のコンセプトを定義するために、発信内容を整理したから違和感ないかレビューしてほしいです :bow: 
https://github.com/Ayato-kosaka/spelieve/issues/929#issue-2063161533

**Comment by Ayato-kosaka** [comment]
ターゲットの悩みの理解
メインイベントの周辺でプチイベントを見つけるのが面倒だし難しい

ターゲットの悩みを解決する投稿コンセプト
メインイベントを軸とした周り方を紹介する

もってもらいたいイメージ明確化
ぷちイベントが増えることの発見

**Comment by Ayato-kosaka** [comment]
## Instagram 投稿の新コンセプト検討 (2024/01/13)

### 問題点
- アカウントコンセプトとの乖離
- 顧客の悩みを完全には理解できていない
- 投稿のインスピレーションが沸かない

### 不変の要件
- Spelieveの「しおり作成機能」で作成された旅程を時系列で投稿すること（ブランド認識の強化に繋げることが Instagram のビジネス目標のため）
- Spelieve の理念を継承すること
  * メインイベントだけでなく、その前後の出来事にもこだわることで、他人と差別化出来る旅行になる。
  * 自分の価値観や人生の優先順位を見つめ直す機会を提供し、自分自身や周囲にポジティブな影響をもたらす。

### メモ
ターゲットの悩みの理解

ターゲットの悩みを解決する投稿コンセプト

もってもらいたいイメージ明確化

**Comment by Ayato-kosaka** [comment]
@Takapy1 
申し訳ないけど何処かで時間作って以下の対応してほしいです :bow: 

■ 困っていること
Spelieve のコンセプトを継承する Instagram の発信コンセプトを言語化したいが言語化出来ない（※[Miro](https://miro.com/app/board/uXjVOqfg7vM=/?moveToWidget=3458764574019177289&cot=14)）

■ お願いしたいこと
Instagram の発信コンセプトを決める上での、以下の内容を野口の中での考えをまとめて欲しい。
* ターゲットの悩み
* ターゲットの悩みを解決する発信コンセプト
* ターゲットにもってもらいたいイメージ

それを叩き台に違和感を議論しながらブラッシュアップさせたい、、

**Comment by Takapy1** [comment]
@Ayato-kosaka 
おけです！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
これ今日中じゃないときびい？

**Comment by Ayato-kosaka** [comment]
@Takapy1 
今日コンセプト決めたかったから今日中が嬉しいけど、難しそうだったら連絡して〜

**Comment by Takapy1** [comment]
@Ayato-kosaka 
ごめん！きびしい！
明日の午前中に送る！

**Comment by Ayato-kosaka** [comment]
@Takapy1 
わかった！

**Comment by Ayato-kosaka** [comment]
案１（プレ旅マエターゲットパターン）
* コンセプト: メインイベントから始まる、モデルプランの「レシピブック」
* メッセージ: **主要イベント（トマト祭り、浴衣街歩き）のモデルプランを紹介**
* 時系列と絡めるとなると、タイトルは「**浴衣で過ごす**京町並みの一日」とかになる。
* 投稿の本文を見て、浴衣を何処で借りてどう周るのが楽しいか知ることになる。

案２（旅マエターゲットパターン）
* メインイベントを軸とした,、こだわりのあるぷちイベントを含む周り方を紹介する
* メッセージ: **周り方をこだわることで、主要イベントの楽しみ方がグレードアップする**
* タイトルは、「京町並みの浴衣での**周り方**」とかになる。
* 投稿の本文を見て、しおりを作成して周り方を考えることで旅行のグレードがアップすることを感じる

モヤモヤ
* アカウントコンセプトと発信内容の乖離
* 発信内容を刺さるように固めるか絞るかしないと発信量不足で価値がなくなる

**Comment by Takapy1** [comment]
@Ayato-kosaka 
依頼もらったコンセプトの件で少し議論をしたいのでミーティングお願いします。

Meet
https://meet.google.com/btd-fuiv-weu

**Comment by Takapy1** [comment]
ちょいトイレ

**Comment by Ayato-kosaka** [comment]
野口に書いてもらったものは↓に追加

https://docs.google.com/document/d/1bPc5FGO-IA3glksTouUepcjqn9TvAm90djKiZIuZa9Y/edit#heading=h.11ot7lo353zv
