### ISSUE TITLE
理想的なサムネイル機能の仕様の決定

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#946]
【Miro】
https://miro.com/app/board/uXjVOqfg7vM=/?moveToWidget=3458764575229654599&cot=10

【機能一覧】
https://docs.google.com/spreadsheets/d/15HDArMW7cq-V2xIIGdeFtJiyXDW7_Crnj2uxA2geH8Q/edit#gid=0

**Comment by Takapy1** [comment]
@Ayato-kosaka 
レビューしてもらった内容に基づいてサムネイルの仕様を修正しました。
確認お願いします！

【Miro】
https://miro.com/app/board/uXjVOqfg7vM=/?moveToWidget=3458764575229654599&cot=10

**Comment by Ayato-kosaka** [comment]
@Takapy1 
ありがとう！
解消を確認しました！
その他指摘なりません！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
確認ありがとう！
仕様を一旦スプシでまとめて、以下の点わかるようにする。
- 新しい機能
- 消えた機能
- 改善された機能

**Comment by Ayato-kosaka** [comment]
@Takapy1 
了解！

**Comment by Takapy1** [comment]
@Ayato-kosaka 
一旦、旧機能と新機能でどこが残って、どこがなくなったからのリストを作りました。
増減の部分を確認してほしい！

【機能一覧】
https://docs.google.com/spreadsheets/d/15HDArMW7cq-V2xIIGdeFtJiyXDW7_Crnj2uxA2geH8Q/edit#gid=0

**Comment by Ayato-kosaka** [comment]
表の何処が信用できて何処がブレ有りかがイメージ出来なかったから、表を作った方法を軽く連携して欲しい！
Miro の付箋から改修後の仕様を洗い出して、既存にあるかをソース上でチェックした感じかな？

[既存のフッター](https://docs.google.com/spreadsheets/d/1BPeKHqCv-_5kgNvtpAC83pegNnN0g19VU8vYzMKiqEU/edit#gid=0)を基に漏れている所追加しています。（No.1だけ）
https://github.com/Ayato-kosaka/spelieve/issues/785 https://github.com/Ayato-kosaka/spelieve/issues/69 とかも見比べて仕様行追加しています。（No.28~44。今回対応では不要だけど仕様一元管理するため。）

また、仕様について、「改修工数」「優先度」「チケット（既に切られてたもの）」を記載しています。

**Comment by Ayato-kosaka** [comment]
↑メンション漏れ: @Takapy1

**Comment by Takapy1** [comment]
@Ayato-kosaka 
確認ありがとう！
表の作成方法は、以下の通りです！

既存
アプリ使用して、存在する機能を手動で確認

新規
Miroの付箋で確認

**Comment by Ayato-kosaka** [comment]
@Takapy1 
りょーかいした！
