### ISSUE TITLE
野口のサムネイル機能の実装速度が遅くなる

### ISSUE THREAD

**Issue by Takapy1** [Ayato-kosaka/spelieve#949]
## Description
**React Nativeの実装が久しぶり**なので、野口のサムネイル実装に時間かかるまくる可能性あり

## Solution
初歩的なところ〜細かいところまでめちゃ聞くとおもうけど、許してください

## 参考

**Comment by Ayato-kosaka** [comment]
@Takapy1 
問題ないよ〜
